const NOMES_DOS_SANTOS_EM_OUTRAS_LINGUAS = {
  'sagrada-familia': ['The Holy Family','La Sagrada Familia'],
  'miguel': ['Saint Michael the Archangel','San Miguel Arcángel'],
  'gabriel': ['Saint Gabriel the Archangel','San Gabriel Arcángel'],
  'rafael': ['Saint Raphael the Archangel','San Rafael Arcángel'],
  'agostinho': ['Saint Augustine of Hippo','San Agustín de Hipona'],
  'tomas-aquino': ['Saint Thomas Aquinas','Santo Tomás de Aquino'],
  'teresa-avila': ['Saint Teresa of Ávila','Santa Teresa de Ávila','Santa Teresa de Jesús'],
  'antonio-padua': ['Saint Anthony of Padua','San Antonio de Padua'],
  'francisco-sales': ['Saint Francis de Sales','San Francisco de Sales'],
  'catarina-sena': ['Saint Catherine of Siena','Santa Catalina de Siena'],
  'jeronimo': ['Saint Jerome','San Jerónimo'],
  'ambrosio': ['Saint Ambrose of Milan','San Ambrosio de Milán'],
  'joao-crisostomo': ['Saint John Chrysostom','San Juan Crisóstomo'],
  'gregorio-magno': ['Saint Gregory the Great','San Gregorio Magno'],
  'boaventura': ['Saint Bonaventure','San Buenaventura'],
  'alberto-magno': ['Saint Albert the Great','San Alberto Magno'],
  'joao-da-cruz': ['Saint John of the Cross','San Juan de la Cruz'],
  'hildegarda': ['Saint Hildegard of Bingen','Santa Hildegarda de Bingen'],
  'afonso-ligorio': ['Saint Alphonsus Liguori','San Alfonso María de Ligorio'],
  'joao-henry-newman': ['Saint John Henry Newman','San John Henry Newman'],
  'joao-paulo-ii': ['Saint John Paul II','San Juan Pablo II'],
  'francisco-assis': ['Saint Francis of Assisi','San Francisco de Asís'],
  'jose': ['Saint Joseph','San José'],
  'padre-pio': ['Saint Padre Pio of Pietrelcina','San Pío de Pietrelcina (Padre Pío)'],
  'faustina': ['Saint Faustina Kowalska','Santa Faustina Kowalska'],
  'dulce-pobres': ['Saint Dulce of the Poor','Santa Dulce de los Pobres'],
  'teresa-calcuta': ['Saint Teresa of Calcutta','Santa Teresa de Calcuta','Mother Teresa','Madre Teresa'],
  'bernadete': ['Saint Bernadette Soubirous','Santa Bernardita Soubirous'],
  'joana-darc': ['Saint Joan of Arc','Santa Juana de Arco'],
  'lourenco': ['Saint Lawrence','San Lorenzo'],
  'inacio-loyola': ['Saint Ignatius of Loyola','San Ignacio de Loyola'],
  'francisco-xavier': ['Saint Francis Xavier','San Francisco Javier'],
  'vicente-paulo': ['Saint Vincent de Paul','San Vicente de Paúl'],
  'bento-nursia': ['Saint Benedict of Nursia','San Benito de Nursia'],
  'cecilia': ['Saint Cecilia','Santa Cecilia'],
  'sebastiao': ['Saint Sebastian','San Sebastián'],
  'judas-tadeu': ['Saint Jude Thaddeus','San Judas Tadeo'],
  'jorge': ['Saint George','San Jorge'],
  'cristovao': ['Saint Christopher','San Cristóbal'],
  'cosme-damiao': ['Saints Cosmas and Damian','Santos Cosme y Damián'],
  'rita-cassia': ['Saint Rita of Cascia','Santa Rita de Casia'],
  'isabel-hungria': ['Saint Elizabeth of Hungary','Santa Isabel de Hungría'],
  'monica': ['Saint Monica','Santa Mónica'],
  'expedito': ['Saint Expeditus','San Expedito'],
  'barbara': ['Saint Barbara','Santa Bárbara'],
  'jose-anchieta': ['Saint José de Anchieta','San José de Anchieta'],
  'madre-paulina': ['Saint Pauline of the Agonizing Heart of Jesus','Santa Paulina del Corazón Agonizante de Jesús'],
  'edith-stein': ['Saint Teresa Benedicta of the Cross (Edith Stein)','Santa Teresa Benedicta de la Cruz (Edith Stein)'],
  'joao-bosco': ['Saint John Bosco','San Juan Bosco'],
  'frei-galvao': ['Saint Anthony of Saint Anne Galvão (Friar Galvão)','San Antonio de Santa Ana Galvão (Fray Galvão)'],
  'teresinha': ['Saint Thérèse of the Child Jesus','Saint Thérèse of Lisieux','Santa Teresita del Niño Jesús','Santa Teresa de Lisieux'],
  'clara-assis': ['Saint Clare of Assisi','Santa Clara de Asís'],
  'carlo-acutis': ['Saint Carlo Acutis','San Carlo Acutis'],
  'chiara-luce': ['Blessed Chiara Luce Badano','Beata Chiara Luce Badano'],
  'pier-giorgio': ['Saint Pier Giorgio Frassati','San Pier Giorgio Frassati'],
  'domingos-savio': ['Saint Dominic Savio','Santo Domingo Savio'],
  'maria-goretti': ['Saint Maria Goretti','Santa María Goretti'],
  'jose-sanchez-rio': ['Saint José Sánchez del Río','San José Sánchez del Río'],
  'kateri-tekakwitha': ['Saint Kateri Tekakwitha','Santa Kateri Tekakwitha'],
  'pastorinhos-fatima': ['Francisco and Jacinta Marto','Francisco y Jacinta Marto'],
  'laura-vicuna': ['Blessed Laura Vicuña','Beata Laura Vicuña'],
  'solanus-casey': ['Blessed Solanus Casey','Beato Solanus Casey'],
  'miguel-pro': ['Blessed Miguel Pro','Beato Miguel Pro'],
  'basilio-magno': ['Saint Basil the Great','San Basilio Magno'],
  'isabel-ana-seton': ['Saint Elizabeth Ann Seton','Santa Isabel Ana Seton'],
  'andre-bessette': ['Saint André Bessette','San Andrés Bessette'],
  'raimundo-penafort': ['Saint Raymond of Peñafort','San Raimundo de Peñafort'],
  'hilario-poitiers': ['Saint Hilary of Poitiers','San Hilario de Poitiers'],
  'antao-grande': ['Saint Anthony the Great','San Antonio Abad'],
  'ines-roma': ['Saint Agnes of Rome','Santa Inés de Roma'],
  'conversao-paulo': ['The Conversion of Saint Paul the Apostle','Conversión de San Pablo Apóstol'],
  'angela-merici': ['Saint Angela Merici','Santa Ángela Merici'],
  'sao-bras': ['Saint Blaise','San Blas'],
  'santa-agueda': ['Saint Agatha','Santa Águeda'],
  'paulo-miki': ['Saint Paul Miki and Companions','San Pablo Miki y compañeros'],
  'josefina-bakhita': ['Saint Josephine Bakhita','Santa Josefina Bakhita'],
  'cirilo-metodio': ['Saints Cyril and Methodius','San Cirilo y San Metodio'],
  'pedro-damiao': ['Saint Peter Damian','San Pedro Damián'],
  'policarpo': ['Saint Polycarp','San Policarpo'],
  'cassimiro': ['Saint Casimir','San Casimiro'],
  'perpetua-felicidade': ['Saints Perpetua and Felicity','Santas Perpetua y Felicidad'],
  'joao-de-deus': ['Saint John of God','San Juan de Dios'],
  'francisca-romana': ['Saint Frances of Rome','Santa Francisca Romana'],
  'sao-patricio': ['Saint Patrick','San Patricio'],
  'cirilo-jerusalem': ['Saint Cyril of Jerusalem','San Cirilo de Jerusalén'],
  'turibio-mogrovejo': ['Saint Turibius of Mogrovejo','Santo Toribio de Mogrovejo'],
  'francisco-paula': ['Saint Francis of Paola','San Francisco de Paula'],
  'isidoro-sevilha': ['Saint Isidore of Seville','San Isidoro de Sevilla'],
  'vicente-ferrer': ['Saint Vincent Ferrer','San Vicente Ferrer'],
  'joao-batista-lasalle': ['Saint John Baptist de La Salle','San Juan Bautista de La Salle'],
  'estanislau': ['Saint Stanislaus','San Estanislao'],
  'anselmo': ['Saint Anselm','San Anselmo'],
  'fidelis-sigmaringen': ['Saint Fidelis of Sigmaringen','San Fidel de Sigmaringa'],
  'marcos-evangelista': ['Saint Mark the Evangelist','San Marcos Evangelista'],
  'jose-operario': ['Saint Joseph the Worker','San José Obrero'],
  'atanasio': ['Saint Athanasius','San Atanasio'],
  'filipe-tiago': ['Saints Philip and James, Apostles','Santos Felipe y Santiago, apóstoles'],
  'matias-apostolo': ['Saint Matthias the Apostle','San Matías Apóstol'],
  'isidro-lavrador': ['Saint Isidore the Farmer','San Isidro Labrador'],
  'bernardino-sena': ['Saint Bernardine of Siena','San Bernardino de Siena'],
  'beda-veneravel': ['Saint Bede the Venerable','San Beda el Venerable'],
  'filipe-neri': ['Saint Philip Neri','San Felipe Neri'],
  'justino-martir': ['Saint Justin Martyr','San Justino Mártir'],
  'carlos-lwanga': ['Saint Charles Lwanga and Companions','San Carlos Lwanga y compañeros'],
  'bonifacio': ['Saint Boniface','San Bonifacio'],
  'barnabe-apostolo': ['Saint Barnabas the Apostle','San Bernabé Apóstol'],
  'luis-gonzaga': ['Saint Aloysius Gonzaga','San Luis Gonzaga'],
  'tomas-more': ['Saint Thomas More','Santo Tomás Moro'],
  'nascimento-joao-batista': ['The Birth of Saint John the Baptist','Natividad de San Juan Bautista'],
  'ireneu-lyon': ['Saint Irenaeus of Lyon','San Ireneo de Lyon'],
  'pedro-paulo-apostolos': ['Saints Peter and Paul, Apostles','San Pedro y San Pablo, apóstoles'],
  'junipero-serra': ['Saint Junípero Serra','San Junípero Serra'],
  'tome-apostolo': ['Saint Thomas the Apostle','Santo Tomás Apóstol'],
  'henrique-imperador': ['Saint Henry','San Enrique'],
  'lourenco-brindes': ['Saint Lawrence of Brindisi','San Lorenzo de Brindis'],
  'maria-madalena': ['Saint Mary Magdalene','Santa María Magdalena'],
  'brigida-suecia': ['Saint Bridget of Sweden','Santa Brígida de Suecia'],
  'joaquim-ana': ['Saints Joachim and Anne','San Joaquín y Santa Ana'],
  'marta-maria-lazaro': ['Saints Martha, Mary and Lazarus','Santos Marta, María y Lázaro'],
  'joao-maria-vianney': ['Saint John Mary Vianney','San Juan María Vianney'],
  'domingos-gusmao': ['Saint Dominic de Guzmán','Santo Domingo de Guzmán'],
  'maximiliano-kolbe': ['Saint Maximilian Kolbe','San Maximiliano Kolbe'],
  'bernardo-claraval': ['Saint Bernard of Clairvaux','San Bernardo de Claraval'],
  'pio-x': ['Saint Pius X','San Pío X'],
  'rosa-lima': ['Saint Rose of Lima','Santa Rosa de Lima'],
  'bartolomeu-apostolo': ['Saint Bartholomew the Apostle','San Bartolomé Apóstol'],
  'luis-ix-franca': ['Saint Louis IX of France','San Luis IX de Francia'],
  'pedro-claver': ['Saint Peter Claver','San Pedro Claver'],
  'cornelio-cipriano': ['Saints Cornelius and Cyprian','San Cornelio y San Cipriano'],
  'sao-januario': ['Saint Januarius','San Jenaro'],
  'andre-kim-taegon': ['Saint Andrew Kim Taegon and Companions','San Andrés Kim Taegon y compañeros'],
  'mateus-apostolo': ['Saint Matthew the Apostle','San Mateo Apóstol'],
  'anjos-guarda': ['The Holy Guardian Angels','Santos Ángeles Custodios'],
  'sao-bruno': ['Saint Bruno','San Bruno'],
  'margarida-maria-alacoque': ['Saint Margaret Mary Alacoque','Santa Margarita María de Alacoque'],
  'lucas-evangelista': ['Saint Luke the Evangelist','San Lucas Evangelista'],
  'joao-brebeuf': ['Saint John de Brébeuf and Companions','San Juan de Brébeuf y compañeros'],
  'joao-capistrano': ['Saint John of Capistrano','San Juan de Capistrano'],
  'martin-porres': ['Saint Martin de Porres','San Martín de Porres'],
  'carlos-borromeu': ['Saint Charles Borromeo','San Carlos Borromeo'],
  'leao-magno': ['Saint Leo the Great','San León Magno'],
  'martinho-tours': ['Saint Martin of Tours','San Martín de Tours'],
  'josafat': ['Saint Josaphat','San Josafat'],
  'frances-cabrini': ['Saint Frances Xavier Cabrini','Santa Francisca Javier Cabrini'],
  'gertrudes': ['Saint Gertrude','Santa Gertrudis'],
  'andre-dung-lac': ['Saint Andrew Dung-Lac and Companions','San Andrés Dung-Lac y compañeros'],
  'catarina-alexandria': ['Saint Catherine of Alexandria','Santa Catalina de Alejandría'],
  'andre-apostolo': ['Saint Andrew the Apostle','San Andrés Apóstol'],
  'sao-nicolau': ['Saint Nicholas','San Nicolás'],
  'juan-diego': ['Saint Juan Diego','San Juan Diego'],
  'santa-luzia': ['Saint Lucy','Santa Lucía'],
  'pedro-canisio': ['Saint Peter Canisius','San Pedro Canisio'],
  'estevao-protomartir': ['Saint Stephen, Protomartyr','San Esteban, protomártir'],
  'joao-evangelista': ['Saint John the Evangelist','San Juan Evangelista'],
  'tomas-becket': ['Saint Thomas Becket','Santo Tomás Becket'],
  'charbel-makhlouf': ['Saint Charbel Makhlouf','San Chárbel Makhlouf'],
  'gianna-molla': ['Saint Gianna Beretta Molla','Santa Gianna Beretta Molla'],
  'damiao-molokai': ['Saint Damien of Molokai','San Damián de Molokai'],
  'paulo-vi': ['Saint Paul VI','San Pablo VI'],
  'joao-xxiii': ['Saint John XXIII','San Juan XXIII'],
  'oscar-romero': ['Saint Óscar Romero','San Óscar Romero'],
  'josemaria-escriva': ['Saint Josemaría Escrivá','San Josemaría Escrivá'],
  'camilo-lelis': ['Saint Camillus de Lellis','San Camilo de Lelis'],
  'roberto-belarmino': ['Saint Robert Bellarmine','San Roberto Belarmino'],
  'gemma-galgani': ['Saint Gemma Galgani','Santa Gema Galgani'],
  'gerardo-majela': ['Saint Gerard Majella','San Gerardo Mayela'],
  'leopoldo-mandic': ['Saint Leopold Mandić','San Leopoldo Mandić'],
  'maria-mazzarello': ['Saint Mary Dominic Mazzarello','Santa María Dominica Mazzarello'],
  'luis-orione': ['Saint Louis Orione','San Luis Orione'],
  'edwiges': ['Saint Hedwig','Santa Eduvigis'],
  'zita': ['Saint Zita','Santa Zita'],
  'teresa-dos-andes': ['Saint Teresa of the Andes','Santa Teresa de los Andes'],
  'pedro-eymard': ['Saint Peter Julian Eymard','San Pedro Julián Eymard'],
  'nha-chica': ['Blessed Nhá Chica','Beata Nhá Chica'],
  'albertina-berkenbrock': ['Blessed Albertina Berkenbrock','Beata Albertina Berkenbrock'],
  'catarina-laboure': ['Saint Catherine Labouré','Santa Catalina Labouré'],
  'isabel-portugal': ['Saint Elizabeth of Portugal','Santa Isabel de Portugal'],
  'nuno-alvares': ['Saint Nuno of Saint Mary','San Nuno de Santa María'],
  'joao-de-britto': ['Saint John de Britto','San Juan de Brito'],
  'charles-foucauld': ['Saint Charles de Foucauld','San Carlos de Foucauld'],
  'grignion-montfort': ['Saint Louis-Marie Grignion de Montfort','San Luis María Grignion de Montfort'],
  'tarcisio': ['Saint Tarcisius','San Tarsicio'],
};
