// ============================================================
//  LUMINA SANCTI — Perguntas das crianças em espanhol
// ============================================================
// Tradução do trilhas-kids.js, com as mesmas chaves (um capítulo por
// chave), a mesma ordem e a mesma quantidade de atividades.

window.ATIVIDADES_KIDS_TRADUZIDAS = window.ATIVIDADES_KIDS_TRADUZIDAS || {};
window.ATIVIDADES_KIDS_TRADUZIDAS.es = Object.assign(window.ATIVIDADES_KIDS_TRADUZIDAS.es || {}, {
  'francisco-1': [
    {"tipo":"multipla","enunciado":"¿En qué ciudad nació San Francisco?","opcoes":["Asís","Roma","Lisboa"],"correta":0,"explicacao":"Francisco nació en Asís, un pueblito precioso de Italia."},
    {"tipo":"vf","enunciado":"Cuando era joven, Francisco soñaba con ser caballero.","correta":true,"explicacao":"Quería ser un caballero famoso, pero Dios tenía para él un sueño todavía más grande."},
    {"tipo":"multipla","enunciado":"¿Qué vendía el papá de Francisco?","opcoes":["Telas","Pan","Zapatos"],"correta":0,"explicacao":"El papá de Francisco vendía telas bonitas y era muy rico."},
    {"tipo":"vf","enunciado":"Francisco nació en una familia pobre.","correta":false,"explicacao":"Su familia era rica; Francisco eligió ser pobre por amor a Jesús."},
    {"tipo":"multipla","enunciado":"¿Qué hizo Francisco cuando encontró a un hombre muy enfermo en el camino?","opcoes":["Le dio un abrazo","Salió corriendo","Hizo como que no lo veía"],"correta":0,"explicacao":"Francisco abrazó al enfermo, porque veía a Jesús en quien sufría."},
    {"tipo":"vf","enunciado":"Francisco le devolvió a su papá hasta la ropa que llevaba puesta.","correta":true,"explicacao":"Quiso mostrar que, desde entonces, su único tesoro era el Padre del Cielo."},
    {"tipo":"multipla","enunciado":"¿Qué tipo de vida eligió Francisco?","opcoes":["Una vida pobre, como Jesús","Una vida de rey","Una vida de soldado"],"correta":0,"explicacao":"Francisco quiso vivir sencillo y pobre, como vivió Jesús."},
    {"tipo":"vf","enunciado":"Cuando era joven, Francisco estuvo preso después de una guerra.","correta":true,"explicacao":"En la prisión, Francisco empezó a pensar más en Dios."},
    {"tipo":"multipla","enunciado":"Después de conocer de verdad a Jesús, Francisco se volvió:","opcoes":["Muy alegre","Muy enojado","Muy triste"],"correta":0,"explicacao":"Francisco era tan alegre que cantaba alabanzas a Dios por los caminos."},
    {"tipo":"vf","enunciado":"Cuando nació, a Francisco le pusieron el nombre de Juan.","correta":true,"explicacao":"Su mamá lo bautizó como Juan, pero todos pasaron a llamarlo Francisco."},
  ],
  'francisco-2': [
    {"tipo":"multipla","enunciado":"¿Qué le pidió Jesús a Francisco en la iglesita de San Damián?","opcoes":["Que cuidara de su Iglesia","Que viviera en un castillo","Que se hiciera soldado"],"correta":0,"explicacao":"Jesús le pidió: ve y repara mi casa, y Francisco obedeció con alegría."},
    {"tipo":"ordenar","enunciado":"Arma el pedido que Francisco escuchó de Jesús:","blocos":["Francisco,","ve y repara","mi casa"],"explicacao":"Jesús llamó a Francisco para cuidar de su Iglesia."},
    {"tipo":"multipla","enunciado":"¿Qué hizo Francisco primero después de escuchar a Jesús?","opcoes":["Arregló iglesitas con sus manos","Se fue a dormir","Compró un caballo"],"correta":0,"explicacao":"Cargó piedras y arregló la iglesita de San Damián."},
    {"tipo":"vf","enunciado":"Francisco arregló la iglesita de San Damián con sus propias manos.","correta":true,"explicacao":"Cargaba piedras y pedía ayuda a quien pasaba."},
    {"tipo":"multipla","enunciado":"¿Cómo se llaman los amigos que siguieron a Francisco?","opcoes":["Franciscanos","Marineros","Caballeros"],"correta":0,"explicacao":"Los franciscanos son los frailes que viven como enseñó Francisco."},
    {"tipo":"vf","enunciado":"Francisco vivía con sus amigos como hermanos.","correta":true,"explicacao":"Llamaba hermanos a sus compañeros y lo compartía todo con ellos."},
    {"tipo":"multipla","enunciado":"¿Quién aprobó la forma de vida de Francisco y sus hermanos?","opcoes":["El Papa","Un rey","Un general"],"correta":0,"explicacao":"Francisco fue a Roma, y el Papa aprobó la vida de los frailes."},
    {"tipo":"vf","enunciado":"Francisco fue sacerdote.","correta":false,"explicacao":"Francisco nunca fue sacerdote, pero amaba mucho la misa."},
    {"tipo":"multipla","enunciado":"¿Cómo trataba Francisco a los pobres?","opcoes":["Con cariño, como hermanos","Con rabia","Con desprecio"],"correta":0,"explicacao":"Francisco compartía lo que tenía y trataba a cada pobre como a un hermano."},
    {"tipo":"vf","enunciado":"Frailes Menores quiere decir hermanos pequeños y humildes.","correta":true,"explicacao":"Querían ser los más pequeños de todos, para servir a todos."},
  ],
  'francisco-3': [
    {"tipo":"multipla","enunciado":"En su cántico, ¿por qué le da gracias Francisco a Dios?","opcoes":["Por el sol, la luna y la naturaleza","Por el dinero","Por los castillos"],"correta":0,"explicacao":"Es el Cántico de las Criaturas: alaba a Dios por el hermano sol y la hermana luna."},
    {"tipo":"vf","enunciado":"Francisco llamaba al sol hermano sol.","correta":true,"explicacao":"Para Francisco, todo lo que Dios creó era hermano."},
    {"tipo":"multipla","enunciado":"En una historia antigua, ¿con qué animal feroz hizo las paces Francisco?","opcoes":["Un lobo","Un gato","Un conejo"],"correta":0,"explicacao":"La historia cuenta que el lobo de Gubbio se volvió manso y amigo del pueblo."},
    {"tipo":"vf","enunciado":"Francisco armó un belén viviente en una noche de Navidad.","correta":true,"explicacao":"Quería que todos vieran cómo nació Jesús, pobrecito, en Belén."},
    {"tipo":"multipla","enunciado":"¿Cómo era el belén que armó Francisco?","opcoes":["Con personas y animales de verdad","Hecho de chocolate","Hecho de hielo"],"correta":0,"explicacao":"Con un buey y un burrito de verdad, recordó el nacimiento de Jesús."},
    {"tipo":"vf","enunciado":"La tradición cuenta que Francisco les predicó hasta a los pajaritos.","correta":true,"explicacao":"Les pedía a los pajaritos que alabaran a Dios, y ellos se quedaban quietitos escuchando."},
    {"tipo":"multipla","enunciado":"¿De quién es patrono San Francisco?","opcoes":["De los animales y la naturaleza","De los bancos","De los coches"],"correta":0,"explicacao":"Por eso mucha gente lleva a sus mascotas a recibir una bendición en su día."},
    {"tipo":"vf","enunciado":"Francisco decía que la luna es nuestra hermana.","correta":true,"explicacao":"En su cántico, alaba a Dios por la hermana luna y las estrellas."},
    {"tipo":"multipla","enunciado":"¿Cómo llamaba Francisco al agua?","opcoes":["Hermana agua","Cosa fea","Enemiga"],"correta":0,"explicacao":"Decía que la hermana agua es útil, humilde y preciosa."},
    {"tipo":"vf","enunciado":"Francisco pensaba que solo las personas eran criaturas de Dios.","correta":false,"explicacao":"Francisco amaba a todas las criaturas: personas, animales, plantas y estrellas."},
  ],
  'jose-1': [
    {"tipo":"multipla","enunciado":"¿Cuál era el trabajo de San José?","opcoes":["Carpintero","Pescador","Pastor"],"correta":0,"explicacao":"José era carpintero y hacía cosas de madera con sus manos."},
    {"tipo":"vf","enunciado":"La Biblia no cuenta ninguna palabra dicha por José.","correta":true,"explicacao":"José hablaba poco y hacía mucho: obedecía a Dios en silencio."},
    {"tipo":"multipla","enunciado":"¿Cómo llama la Biblia a José?","opcoes":["Hombre justo","Hombre enojón","Hombre rico"],"correta":0,"explicacao":"Justo quiere decir bueno y fiel a Dios."},
    {"tipo":"vf","enunciado":"José era de la familia del rey David.","correta":true,"explicacao":"Por eso a Jesús también se le llama hijo de David."},
    {"tipo":"multipla","enunciado":"¿Quién le avisó a José, en sueños, que el bebé de María venía de Dios?","opcoes":["Un ángel","Un soldado","Un vecino"],"correta":0,"explicacao":"Dios mandó un ángel para calmar el corazón de José."},
    {"tipo":"vf","enunciado":"José recibió a María en su casa y la cuidó con amor.","correta":true,"explicacao":"Obedeció al ángel y se quedó al lado de María."},
    {"tipo":"multipla","enunciado":"¿Qué nombre mandó el ángel ponerle al bebé?","opcoes":["Jesús","Pedro","David"],"correta":0,"explicacao":"Jesús quiere decir Dios salva."},
    {"tipo":"vf","enunciado":"José tuvo miedo y abandonó a María.","correta":false,"explicacao":"José fue fiel: confió en Dios y cuidó de María y de Jesús."},
    {"tipo":"multipla","enunciado":"¿En qué ciudad nació Jesús?","opcoes":["Belén","Roma","Lisboa"],"correta":0,"explicacao":"Jesús nació en Belén, y José estaba allí cuidándolo todo."},
    {"tipo":"vf","enunciado":"José cuidó de Jesús desde que era bebé.","correta":true,"explicacao":"José fue el papá que Dios eligió para cuidar de Jesús aquí en la tierra."},
  ],
  'jose-2': [
    {"tipo":"multipla","enunciado":"¿Cómo supo José que tenía que huir con su familia?","opcoes":["Un ángel le avisó en sueños","Recibió una carta","Lo oyó en el mercado"],"correta":0,"explicacao":"José siempre escuchaba la voz de Dios y obedecía enseguida."},
    {"tipo":"vf","enunciado":"La Sagrada Familia huyó para proteger al niño Jesús.","correta":true,"explicacao":"El rey Herodes quería hacerle daño al niño, y José protegió a su familia."},
    {"tipo":"multipla","enunciado":"¿A qué país huyó la Sagrada Familia?","opcoes":["Egipto","Japón","Brasil"],"correta":0,"explicacao":"Hicieron un viaje larguísimo hasta Egipto."},
    {"tipo":"vf","enunciado":"José partió con María y Jesús durante la noche.","correta":true,"explicacao":"Se levantó de noche y partió enseguida, para proteger a su familia."},
    {"tipo":"multipla","enunciado":"¿Dónde fue a vivir después la Sagrada Familia?","opcoes":["Nazaret","París","Roma"],"correta":0,"explicacao":"En Nazaret, Jesús creció junto a María y José."},
    {"tipo":"ordenar","enunciado":"Arma el camino de la Sagrada Familia:","blocos":["Jesús nace en Belén","Huyen a Egipto","Vuelven a Nazaret"],"explicacao":"José guió a su familia en cada paso, con valentía."},
    {"tipo":"vf","enunciado":"Una vez, José y María buscaron a Jesús durante tres días.","correta":true,"explicacao":"Lo encontraron en el Templo, conversando con los maestros."},
    {"tipo":"multipla","enunciado":"¿Dónde encontraron a Jesús después de tres días?","opcoes":["En el Templo","En la playa","En el mercado"],"correta":0,"explicacao":"Jesús estaba en la casa de Dios, escuchando y haciendo preguntas."},
    {"tipo":"vf","enunciado":"José era un papá perezoso.","correta":false,"explicacao":"José era trabajador y cuidadoso: protegía a su familia con amor."},
    {"tipo":"multipla","enunciado":"¿Quién llevó al bebé Jesús al Templo junto con María?","opcoes":["José","Pedro","Juan"],"correta":0,"explicacao":"José y María presentaron a Jesús a Dios en el Templo."},
  ],
  'jose-3': [
    {"tipo":"multipla","enunciado":"¿A quién protege San José?","opcoes":["A toda la Iglesia","Solo a los reyes","Solo a los soldados"],"correta":0,"explicacao":"Así como cuidó de Jesús, José cuida de toda la Iglesia."},
    {"tipo":"vf","enunciado":"A San José se le llama protector de la Sagrada Familia.","correta":true,"explicacao":"Protegió a Jesús y a María con todo su cariño."},
    {"tipo":"multipla","enunciado":"¿Qué oficio aprendió Jesús con José?","opcoes":["Carpintero","Pintor","Cocinero"],"correta":0,"explicacao":"Jesús aprendió con José a trabajar la madera."},
    {"tipo":"vf","enunciado":"Hay una fiesta de San José Obrero, que recuerda el valor del trabajo.","correta":true,"explicacao":"Trabajar con amor también es una forma de rezar."},
    {"tipo":"multipla","enunciado":"Según la tradición, ¿quién estaba junto a José cuando se fue al Cielo?","opcoes":["Jesús y María","Los soldados","Nadie"],"correta":0,"explicacao":"La tradición cuenta que José partió en los brazos de Jesús y María."},
    {"tipo":"vf","enunciado":"El papa Francisco escribió una carta sobre San José.","correta":true,"explicacao":"La carta se llama Con corazón de padre."},
    {"tipo":"multipla","enunciado":"¿Cómo es el corazón de José, según la carta del Papa?","opcoes":["Corazón de padre","Corazón de piedra","Corazón de hielo"],"correta":0,"explicacao":"José amó a Jesús con un corazón de padre, lleno de ternura."},
    {"tipo":"vf","enunciado":"Podemos pedirle a San José que rece por nosotros.","correta":true,"explicacao":"Los santos son amigos de Dios y rezan por nosotros."},
    {"tipo":"multipla","enunciado":"Completa: Jesús, María y...","opcoes":["José","Pedro","Pablo"],"correta":0,"explicacao":"Jesús, María y José forman la Sagrada Familia."},
    {"tipo":"vf","enunciado":"José trabajaba para mantener a su familia.","correta":true,"explicacao":"Con su trabajo, José aseguraba el pan de cada día en casa."},
  ],
  'teresinha-1': [
    {"tipo":"multipla","enunciado":"¿En qué país nació Teresita?","opcoes":["Francia","Brasil","Japón"],"correta":0,"explicacao":"Teresita nació en Francia y vivió en una ciudad llamada Lisieux."},
    {"tipo":"vf","enunciado":"Teresita decía que era una florecilla de Jesús.","correta":true,"explicacao":"Se veía como una florecilla sencilla en el jardín de Dios."},
    {"tipo":"multipla","enunciado":"¿Cómo se llamaban los papás de Teresita?","opcoes":["Luis y Celia","Pedro y Ana","Jorge y Rosa"],"correta":0,"explicacao":"¡Luis y Celia también fueron declarados santos!"},
    {"tipo":"vf","enunciado":"Los papás de Teresita también son santos.","correta":true,"explicacao":"Era una familia entera que amaba a Dios."},
    {"tipo":"multipla","enunciado":"¿Cuántas hermanas de Teresita también se hicieron monjas?","opcoes":["Cuatro","Ninguna","Veinte"],"correta":0,"explicacao":"María, Paulina, Leonia y Celina también entregaron su vida a Dios."},
    {"tipo":"vf","enunciado":"Teresita le pidió al Papa entrar pronto en el convento.","correta":true,"explicacao":"Siendo todavía una jovencita, habló con el Papa en persona, llena de valentía."},
    {"tipo":"multipla","enunciado":"¿Para qué se fue Teresita a vivir a un convento?","opcoes":["Para rezar y amar a Jesús","Para hacerse famosa","Para ganar dinero"],"correta":0,"explicacao":"En el convento, rezaba por todas las personas del mundo."},
    {"tipo":"vf","enunciado":"Teresita vivió hasta ser muy viejita.","correta":false,"explicacao":"Teresita se fue al Cielo siendo joven, pero vivió cada día con mucho amor."},
    {"tipo":"multipla","enunciado":"¿Qué nombre recibió Teresita en el convento?","opcoes":["Teresa del Niño Jesús","Teresa del Mar","Teresa de la Montaña"],"correta":0,"explicacao":"Quiso llevar en su nombre al Niño Jesús."},
    {"tipo":"vf","enunciado":"La familia de Teresita rezaba unida.","correta":true,"explicacao":"En casa rezaban, iban a misa y ayudaban a los pobres."},
  ],
  'teresinha-2': [
    {"tipo":"multipla","enunciado":"¿Qué es el caminito de Teresita?","opcoes":["Hacer cosas pequeñas con mucho amor","Hacer solo cosas enormes","Correr muy rápido"],"correta":0,"explicacao":"Hasta tender la cama puede ser un regalo para Jesús, si se hace con amor."},
    {"tipo":"vf","enunciado":"Para Teresita, una sonrisa puede ser un regalo para Jesús.","correta":true,"explicacao":"Sonreía incluso a quienes eran difíciles de tratar."},
    {"tipo":"multipla","enunciado":"¿Con qué cosa comparó Teresita su camino?","opcoes":["Un ascensor","Un barco","Una bicicleta"],"correta":0,"explicacao":"Los brazos de Jesús eran el ascensor que la subía al Cielo."},
    {"tipo":"vf","enunciado":"Teresita se veía como una niña en brazos de Dios.","correta":true,"explicacao":"Confiaba en Dios como una niña confía en su papá."},
    {"tipo":"multipla","enunciado":"Teresita prometió enviar desde el Cielo una lluvia de...","opcoes":["Rosas","Piedras","Hojas"],"correta":0,"explicacao":"Las rosas son las bendiciones que ella le pide a Dios para nosotros."},
    {"tipo":"ordenar","enunciado":"Arma la promesa de Teresita:","blocos":["Quiero pasar","mi cielo","haciendo el bien en la tierra"],"explicacao":"Prometió seguir ayudando a la gente desde el Cielo."},
    {"tipo":"vf","enunciado":"Teresita decía que solo las cosas enormes agradan a Dios.","correta":false,"explicacao":"Para ella, lo que vale es el amor, incluso en las cosas pequeñitas."},
    {"tipo":"multipla","enunciado":"¿Qué hacía Teresita cuando alguien era difícil con ella?","opcoes":["Sonreía y era amable","Peleaba","Dejaba de hablarle"],"correta":0,"explicacao":"Respondía con amabilidad y rezaba por esa persona."},
    {"tipo":"vf","enunciado":"Teresita confiaba mucho en el amor de Dios.","correta":true,"explicacao":"Confiar es como lanzarse a los brazos de quien nos ama."},
    {"tipo":"multipla","enunciado":"¿Qué está en el centro del caminito?","opcoes":["El amor y la confianza","La prisa","El miedo"],"correta":0,"explicacao":"Con amor y confianza, cualquier niño puede ser santo."},
  ],
  'teresinha-3': [
    {"tipo":"vf","enunciado":"Teresita es patrona de las misiones, aunque nunca salió del convento.","correta":true,"explicacao":"Ayudaba a los misioneros rezando por ellos todos los días."},
    {"tipo":"multipla","enunciado":"¿Qué libro cuenta la historia de Teresita, escrita por ella misma?","opcoes":["Historia de un alma","El Principito","Don Quijote"],"correta":0,"explicacao":"Escribió sus recuerdos, y el libro se leyó en el mundo entero."},
    {"tipo":"multipla","enunciado":"¿Cómo ayudaba Teresita a los misioneros?","opcoes":["Rezando y escribiendo cartas","Viajando en barco","Construyendo iglesias"],"correta":0,"explicacao":"Llamaba hermanos a dos sacerdotes misioneros y les escribía."},
    {"tipo":"vf","enunciado":"Teresita es Doctora de la Iglesia, que quiere decir una gran maestra de la fe.","correta":true,"explicacao":"Con su caminito, nos enseña a amar a Dios."},
    {"tipo":"multipla","enunciado":"¿Junto con qué santo es patrona de las misiones Teresita?","opcoes":["San Francisco Javier","San Jorge","San Pedro"],"correta":0,"explicacao":"Francisco Javier recorrió el mundo; Teresita rezó sin salir del convento."},
    {"tipo":"vf","enunciado":"Teresita se enfermó mucho, pero siguió confiando en Jesús.","correta":true,"explicacao":"Aun sufriendo, sonreía y rezaba."},
    {"tipo":"multipla","enunciado":"¿Cuáles fueron las últimas palabras de Teresita?","opcoes":["Dios mío, os amo","Tengo hambre","Hasta mañana"],"correta":0,"explicacao":"Se fue al Cielo diciendo que amaba a Dios."},
    {"tipo":"vf","enunciado":"Teresita quería ayudar a la gente incluso después de irse al Cielo.","correta":true,"explicacao":"Por eso tanta gente le pide que rece por nosotros."},
    {"tipo":"multipla","enunciado":"¿Dónde vivió Teresita rezando por el mundo entero?","opcoes":["En el convento","En un barco","En un castillo"],"correta":0,"explicacao":"En el convento de Lisieux rezaba por todos."},
    {"tipo":"vf","enunciado":"Teresita nunca rezaba por los demás.","correta":false,"explicacao":"Teresita rezaba por todos, sobre todo por los que estaban lejos de Dios."},
  ],
  'antonio-1': [
    {"tipo":"multipla","enunciado":"¿En qué ciudad nació San Antonio?","opcoes":["Lisboa","Madrid","Londres"],"correta":0,"explicacao":"Nació en Lisboa, en Portugal, y se hizo famoso en Padua, en Italia."},
    {"tipo":"vf","enunciado":"San Antonio se hizo fraile franciscano, como los amigos de San Francisco.","correta":true,"explicacao":"Quiso vivir pobre y alegre, como San Francisco."},
    {"tipo":"multipla","enunciado":"¿Cuál era el primer nombre de San Antonio?","opcoes":["Fernando","Carlos","Mateo"],"correta":0,"explicacao":"Se llamaba Fernando y recibió el nombre de Antonio cuando se hizo fraile."},
    {"tipo":"vf","enunciado":"Antonio quería ser misionero en África.","correta":true,"explicacao":"Soñaba con llevar a Jesús muy lejos, hasta Marruecos."},
    {"tipo":"multipla","enunciado":"¿Qué llevó el barco de Antonio hasta Italia?","opcoes":["Una tormenta","Una ballena","Un pirata"],"correta":0,"explicacao":"El barco se desvió, y Dios lo usó para llevarlo a Italia."},
    {"tipo":"vf","enunciado":"Antonio se enfermó en el viaje a África.","correta":true,"explicacao":"Enfermo, tuvo que volver, pero el barco acabó en Italia."},
    {"tipo":"multipla","enunciado":"¿En qué país vivió Antonio sus últimos años?","opcoes":["Italia","Brasil","China"],"correta":0,"explicacao":"En Italia predicó en muchas ciudades, hasta llegar a Padua."},
    {"tipo":"vf","enunciado":"Antonio murió muy viejito.","correta":false,"explicacao":"Antonio se fue al Cielo siendo joven, pero hizo mucho bien en poco tiempo."},
    {"tipo":"multipla","enunciado":"Hablar de Jesús a mucha gente es:","opcoes":["Predicar","Cocinar","Nadar"],"correta":0,"explicacao":"Predicar es anunciar la Palabra de Dios, y Antonio lo hacía muy bien."},
    {"tipo":"vf","enunciado":"Antonio fue declarado santo muy poco tiempo después de morir.","correta":true,"explicacao":"Todo el mundo ya sabía que era un hombre de Dios."},
  ],
  'antonio-2': [
    {"tipo":"multipla","enunciado":"¿Por qué se hizo famoso San Antonio?","opcoes":["Predicaba muy bien","Cantaba ópera","Era un rey"],"correta":0,"explicacao":"Cuando hablaba de Jesús, la gente se emocionaba."},
    {"tipo":"vf","enunciado":"Mucha gente le pide ayuda a San Antonio para encontrar cosas perdidas.","correta":true,"explicacao":"Se le recuerda como el santo de las cosas perdidas."},
    {"tipo":"multipla","enunciado":"En una historia antigua, ¿a quién le predicó Antonio?","opcoes":["A los peces","A las nubes","A las piedras"],"correta":0,"explicacao":"La historia cuenta que, cuando la gente no quiso escuchar, los peces sacaron la cabeza del agua para oírlo."},
    {"tipo":"vf","enunciado":"San Antonio conocía muy bien la Biblia.","correta":true,"explicacao":"Sabía de memoria muchos pasajes de la Palabra de Dios."},
    {"tipo":"multipla","enunciado":"¿Qué título especial le dio la Iglesia a Antonio?","opcoes":["Doctor de la Iglesia","Capitán del mar","Rey de Portugal"],"correta":0,"explicacao":"Doctor de la Iglesia quiere decir un gran maestro que enseña la fe."},
    {"tipo":"vf","enunciado":"San Francisco le escribió una carta a Antonio.","correta":true,"explicacao":"Francisco le pidió que enseñara a los frailes, sin olvidarse de rezar."},
    {"tipo":"ordenar","enunciado":"Arma el pedido a San Antonio:","blocos":["San Antonio,","ayúdame a encontrar","lo que perdí"],"explicacao":"Es un pedido sencillo que mucha gente hace con fe."},
    {"tipo":"multipla","enunciado":"¿Cuál era el libro que Antonio más amaba?","opcoes":["La Biblia","Un libro de recetas","Un mapa"],"correta":0,"explicacao":"La Biblia es la Palabra de Dios, y Antonio la estudiaba con amor."},
    {"tipo":"vf","enunciado":"Antonio dejó de hablar de Dios cuando la gente no quiso escuchar.","correta":false,"explicacao":"No se rindió: fue al mar y siguió hablando de Dios."},
    {"tipo":"multipla","enunciado":"¿Por qué el Papa llamó a Antonio Arca del Testamento?","opcoes":["Guardaba la Biblia en el corazón","Tenía un barco","Era carpintero"],"correta":0,"explicacao":"Antonio guardaba la Palabra de Dios en la memoria y en el corazón."},
  ],
  'antonio-3': [
    {"tipo":"vf","enunciado":"El Pan de los Pobres es una ayuda para quien tiene hambre, ligada a San Antonio.","correta":true,"explicacao":"Aún hoy, en su nombre, mucha gente comparte el pan con quien lo necesita."},
    {"tipo":"multipla","enunciado":"¿Qué sostiene San Antonio en brazos en las imágenes?","opcoes":["Al Niño Jesús","Un perrito","Una corona"],"correta":0,"explicacao":"La tradición cuenta que el Niño Jesús se le apareció mientras rezaba."},
    {"tipo":"multipla","enunciado":"¿Qué flor aparece en las imágenes de San Antonio?","opcoes":["Un lirio","Un girasol","Una margarita"],"correta":0,"explicacao":"El lirio blanco recuerda un corazón limpio."},
    {"tipo":"vf","enunciado":"En Brasil, mucha gente le pide a San Antonio un buen matrimonio.","correta":true,"explicacao":"Es una devoción alegre del pueblo, muy recordada en las fiestas de junio."},
    {"tipo":"multipla","enunciado":"¿En qué fiestas de Brasil se recuerda mucho a San Antonio?","opcoes":["Las fiestas de junio","El carnaval","El Año Nuevo"],"correta":0,"explicacao":"En las fiestas de junio recordamos a San Antonio, San Juan y San Pedro."},
    {"tipo":"vf","enunciado":"San Antonio ayudaba a los pobres.","correta":true,"explicacao":"Tenía un cariño especial por los que sufrían."},
    {"tipo":"multipla","enunciado":"¿Cuáles son los tres santos de las fiestas de junio?","opcoes":["Antonio, Juan y Pedro","Jorge, Cosme y Damián","Francisco, Clara y Benito"],"correta":0,"explicacao":"Antonio, Juan y Pedro se recuerdan con mucha alegría en junio."},
    {"tipo":"vf","enunciado":"San Antonio era un fraile vanidoso al que le gustaban las riquezas.","correta":false,"explicacao":"Vivía con sencillez y lo compartía todo con los pobres."},
    {"tipo":"multipla","enunciado":"¿Por qué tanta gente quiere a San Antonio?","opcoes":["Porque ayuda a quien lo necesita","Porque era muy rico","Porque era un rey"],"correta":0,"explicacao":"Es un amigo que reza por nosotros, sobre todo por los pobres."},
    {"tipo":"vf","enunciado":"Muchas iglesias de Brasil llevan el nombre de San Antonio.","correta":true,"explicacao":"Es uno de los santos más queridos del pueblo brasileño."},
  ],
  'pio-1': [
    {"tipo":"multipla","enunciado":"¿Qué ropa usaba el Padre Pío?","opcoes":["Un hábito marrón de fraile","Una armadura","Una corona"],"correta":0,"explicacao":"Era fraile capuchino y usaba el hábito marrón con capucha."},
    {"tipo":"vf","enunciado":"El Padre Pío tenía en las manos heridas parecidas a las de Jesús.","correta":true,"explicacao":"Sufrió con esas heridas durante muchos años, con paciencia y amor."},
    {"tipo":"multipla","enunciado":"¿Cómo se llamaba el Padre Pío de niño?","opcoes":["Francisco","Pablo","Santiago"],"correta":0,"explicacao":"Se llamaba Francesco, que es Francisco en italiano."},
    {"tipo":"vf","enunciado":"El Padre Pío nació en un pueblito de Italia.","correta":true,"explicacao":"Nació en Pietrelcina, en una familia sencilla del campo."},
    {"tipo":"multipla","enunciado":"¿En qué país vivió el Padre Pío?","opcoes":["Italia","Brasil","Estados Unidos"],"correta":0,"explicacao":"Pasó toda su vida en Italia."},
    {"tipo":"vf","enunciado":"El Padre Pío vivió muchos años en el mismo convento.","correta":true,"explicacao":"Estuvo muchísimos años en el convento de San Giovanni Rotondo."},
    {"tipo":"multipla","enunciado":"¿Qué era lo que más le gustaba hacer al Padre Pío?","opcoes":["Rezar","Viajar","Jugar"],"correta":0,"explicacao":"Rezaba el rosario muchas veces al día."},
    {"tipo":"vf","enunciado":"El Padre Pío nunca fue sacerdote.","correta":false,"explicacao":"Sí fue sacerdote, y celebraba la misa con mucho amor."},
    {"tipo":"multipla","enunciado":"¿Cómo era el Padre Pío?","opcoes":["Humilde y sencillo","Rico y vanidoso","Enojón y egoísta"],"correta":0,"explicacao":"Aunque era famoso, vivía como un fraile sencillo."},
    {"tipo":"vf","enunciado":"Hoy el Padre Pío es santo.","correta":true,"explicacao":"La Iglesia declaró que está en el Cielo con Dios."},
  ],
  'pio-2': [
    {"tipo":"multipla","enunciado":"¿Dónde le pedimos perdón a Dios con la ayuda del sacerdote?","opcoes":["En la Confesión","En el almuerzo","En un viaje"],"correta":0,"explicacao":"El Padre Pío pasaba horas en la Confesión, donde Jesús perdona nuestros pecados."},
    {"tipo":"ordenar","enunciado":"Arma el consejo del Padre Pío:","blocos":["Reza,","espera","y no te preocupes"],"explicacao":"Enseñaba a confiar en Dios en todo."},
    {"tipo":"multipla","enunciado":"¿Cómo llamaba el Padre Pío al rosario?","opcoes":["El arma","El juguete","El collar"],"correta":0,"explicacao":"Para él, el rosario era un arma de oración que vence el mal."},
    {"tipo":"vf","enunciado":"Mucha gente hacía fila para confesarse con el Padre Pío.","correta":true,"explicacao":"Venían personas de varios países para encontrar el perdón de Dios."},
    {"tipo":"multipla","enunciado":"¿Para qué pidió el Padre Pío que la gente se reuniera?","opcoes":["Para rezar juntos","Para pelear","Para ir de compras"],"correta":0,"explicacao":"Los Grupos de Oración del Padre Pío existen hasta hoy."},
    {"tipo":"vf","enunciado":"El Padre Pío decía que la oración es muy importante.","correta":true,"explicacao":"Para él, rezar es hablar con Dios y abrirle el corazón."},
    {"tipo":"multipla","enunciado":"¿Qué hace Dios cuando le pedimos perdón de corazón?","opcoes":["Perdona","Se queda enojado para siempre","No escucha"],"correta":0,"explicacao":"Dios es Padre y perdona a quien se arrepiente."},
    {"tipo":"vf","enunciado":"El Padre Pío celebraba la misa con mucho cariño.","correta":true,"explicacao":"Mucha gente se emocionaba solo de ver su amor en la misa."},
    {"tipo":"vf","enunciado":"El Padre Pío pensaba que rezar era una pérdida de tiempo.","correta":false,"explicacao":"Decía que la oración es la mejor arma que tenemos."},
    {"tipo":"multipla","enunciado":"¿A quién atendía el Padre Pío en el confesionario?","opcoes":["A ricos y pobres, a todos igual","Solo a los reyes","Solo a los artistas"],"correta":0,"explicacao":"Recibía a todos con el mismo cariño."},
  ],
  'pio-3': [
    {"tipo":"vf","enunciado":"El Padre Pío construyó un hospital para cuidar a los enfermos.","correta":true,"explicacao":"El nombre del hospital quiere decir Casa Alivio del Sufrimiento."},
    {"tipo":"multipla","enunciado":"¿Qué obra hizo el Padre Pío para los enfermos?","opcoes":["Un hospital","Un parque","Un estadio"],"correta":0,"explicacao":"Quería que los enfermos fueran tratados con amor y buenas medicinas."},
    {"tipo":"multipla","enunciado":"¿Qué papa declaró santo al Padre Pío?","opcoes":["Juan Pablo II","Benedicto XVI","Francisco"],"correta":0,"explicacao":"El papa Juan Pablo II declaró santo al Padre Pío ante una gran multitud."},
    {"tipo":"vf","enunciado":"Juan Pablo II conoció al Padre Pío cuando todavía era un sacerdote joven.","correta":true,"explicacao":"Años después, él mismo declaró santo al Padre Pío."},
    {"tipo":"multipla","enunciado":"¿Dónde está el hospital del Padre Pío?","opcoes":["Cerca de su convento","En una isla","En otro país"],"correta":0,"explicacao":"El hospital está junto al convento donde vivió, en Italia."},
    {"tipo":"vf","enunciado":"Hasta hoy el hospital del Padre Pío cuida a muchos enfermos.","correta":true,"explicacao":"Es un regalo de amor que sigue ayudando a la gente."},
    {"tipo":"multipla","enunciado":"¿Cómo quería el Padre Pío que trataran a los enfermos?","opcoes":["Con amor y cariño","Con prisa","Con desprecio"],"correta":0,"explicacao":"Para él, cuidar a un enfermo es cuidar al mismo Jesús."},
    {"tipo":"vf","enunciado":"Muchos peregrinos visitan el lugar donde vivió el Padre Pío.","correta":true,"explicacao":"Gente de todo el mundo va allí a rezar."},
    {"tipo":"multipla","enunciado":"Un peregrino es alguien que:","opcoes":["Viaja para rezar en un lugar santo","Vende pescado","Pinta cuadros"],"correta":0,"explicacao":"Los peregrinos caminan para encontrarse con Dios."},
    {"tipo":"vf","enunciado":"Al Padre Pío solo le importaban las personas sanas.","correta":false,"explicacao":"Tenía un cariño enorme por los enfermos y por los que sufrían."},
  ],
  'maria-1': [
    {"tipo":"multipla","enunciado":"¿Qué ángel le llevó el mensaje de Dios a María?","opcoes":["Gabriel","Miguel","Rafael"],"correta":0,"explicacao":"El ángel Gabriel le contó a María que sería la mamá de Jesús."},
    {"tipo":"vf","enunciado":"María le dijo que sí a Dios.","correta":true,"explicacao":"Respondió: he aquí la esclava del Señor, hágase en mí según tu palabra."},
    {"tipo":"multipla","enunciado":"¿En qué ciudad vivía María cuando llegó el ángel?","opcoes":["Nazaret","Belén","Roma"],"correta":0,"explicacao":"Nazaret era una ciudad pequeña y sencilla."},
    {"tipo":"vf","enunciado":"El ángel le dijo a María: Dios te salve, llena de gracia.","correta":true,"explicacao":"Con estas palabras empieza la oración del Avemaría."},
    {"tipo":"multipla","enunciado":"¿Qué nombre dijo el ángel que tendría el bebé?","opcoes":["Jesús","Moisés","David"],"correta":0,"explicacao":"Jesús es el Hijo de Dios que vino a vivir entre nosotros."},
    {"tipo":"vf","enunciado":"María tuvo miedo y le dijo que no a Dios.","correta":false,"explicacao":"María confió en Dios y dijo que sí con todo el corazón."},
    {"tipo":"multipla","enunciado":"¿Qué pariente de María también esperaba un bebé?","opcoes":["Isabel","Marta","Magdalena"],"correta":0,"explicacao":"Isabel era prima de María y esperaba a Juan Bautista."},
    {"tipo":"vf","enunciado":"El ángel dijo que para Dios nada es imposible.","correta":true,"explicacao":"Dios hace maravillas en la vida de quien confía en él."},
    {"tipo":"multipla","enunciado":"¿Qué oración empieza con las palabras del ángel?","opcoes":["El Avemaría","El Padrenuestro","El Gloria"],"correta":0,"explicacao":"Cuando rezamos el Avemaría, repetimos el saludo del ángel."},
    {"tipo":"vf","enunciado":"María es la mamá de Jesús.","correta":true,"explicacao":"Y Jesús nos dio a María para que fuera también nuestra mamá."},
  ],
  'maria-2': [
    {"tipo":"multipla","enunciado":"¿A quién fue a visitar María justo después de la visita del ángel?","opcoes":["A su prima Isabel","Al rey Herodes","A un pastor"],"correta":0,"explicacao":"María fue deprisa a ayudar a Isabel, que esperaba un bebé."},
    {"tipo":"vf","enunciado":"Cuando llegó María, el bebé de Isabel saltó de alegría en la pancita de su mamá.","correta":true,"explicacao":"Juan Bautista ya se alegraba con la llegada de Jesús."},
    {"tipo":"multipla","enunciado":"¿Qué bebé esperaba Isabel?","opcoes":["Juan Bautista","Pedro","Pablo"],"correta":0,"explicacao":"Juan Bautista iba a preparar el camino de Jesús."},
    {"tipo":"vf","enunciado":"Isabel dijo que María es bendita entre las mujeres.","correta":true,"explicacao":"Repetimos estas palabras en el Avemaría."},
    {"tipo":"multipla","enunciado":"María cantó una oración de alegría. ¿Cómo empieza?","opcoes":["Proclama mi alma la grandeza del Señor","Padre nuestro que estás en el cielo","Gloria a Dios en el cielo"],"correta":0,"explicacao":"Ese canto de María se llama Magníficat."},
    {"tipo":"ordenar","enunciado":"Arma el comienzo del canto de María:","blocos":["Proclama","mi alma","la grandeza del Señor"],"explicacao":"María le da gracias a Dios por las cosas lindas que hizo."},
    {"tipo":"multipla","enunciado":"¿Qué hizo María en casa de Isabel?","opcoes":["Ayudó a su prima","Se fue de paseo","Se fue a dormir"],"correta":0,"explicacao":"María se quedó unos tres meses ayudando a Isabel con mucho cariño."},
    {"tipo":"vf","enunciado":"En su canto, María dice que Dios mira con cariño a los humildes.","correta":true,"explicacao":"Dios ama a los pequeños y a los sencillos de corazón."},
    {"tipo":"vf","enunciado":"María se volvió orgullosa y se creyó mejor que todos.","correta":false,"explicacao":"María era humilde y le daba toda la gloria a Dios."},
    {"tipo":"multipla","enunciado":"¿Cómo nos enseña María a ser?","opcoes":["Humildes","Orgullosos","Egoístas"],"correta":0,"explicacao":"Quien es humilde deja que Dios haga maravillas en su vida."},
  ],
  'maria-3': [
    {"tipo":"multipla","enunciado":"En la cruz, ¿de quién le pidió Jesús a María que fuera mamá?","opcoes":["Del discípulo Juan","De un soldado","De nadie"],"correta":0,"explicacao":"Jesús le dijo a Juan: ahí tienes a tu madre, y así María es la mamá de todos nosotros."},
    {"tipo":"vf","enunciado":"Cuando rezamos el rosario, recordamos la vida de Jesús y de María.","correta":true,"explicacao":"Cada misterio del rosario cuenta un pedacito de esa historia."},
    {"tipo":"multipla","enunciado":"¿Quién es la patrona de Brasil?","opcoes":["Nuestra Señora Aparecida","Nuestra Señora de Lourdes","Nuestra Señora de Guadalupe"],"correta":0,"explicacao":"La imagen de Aparecida la encontraron unos pescadores en un río."},
    {"tipo":"vf","enunciado":"La imagen de Nuestra Señora Aparecida la encontraron unos pescadores.","correta":true,"explicacao":"Echaron la red en el río y encontraron la imagen."},
    {"tipo":"multipla","enunciado":"En Fátima, ¿a cuántos niños se apareció la Virgen?","opcoes":["Tres","Uno","Diez"],"correta":0,"explicacao":"Lucía, Francisco y Jacinta eran pastorcitos."},
    {"tipo":"vf","enunciado":"Los pastorcitos de Fátima eran adultos muy ricos.","correta":false,"explicacao":"Eran niños sencillos que cuidaban ovejas."},
    {"tipo":"multipla","enunciado":"En Lourdes, ¿a qué niña se apareció la Virgen?","opcoes":["Bernardita","Teresita","Clara"],"correta":0,"explicacao":"Bernardita era una niña pobre y muy sincera."},
    {"tipo":"vf","enunciado":"María fue llevada al Cielo en cuerpo y alma.","correta":true,"explicacao":"Esta fiesta se llama Asunción de la Virgen."},
    {"tipo":"multipla","enunciado":"¿Qué les dijo María a los sirvientes en la boda de Caná?","opcoes":["Haced lo que él os diga","Váyanse","Traigan más pan"],"correta":0,"explicacao":"Es el mejor consejo de María: hacer lo que Jesús pide."},
    {"tipo":"vf","enunciado":"A María se la llama Madre de la Iglesia.","correta":true,"explicacao":"Cuida de todos los hijos de Dios como una mamá cuida de su familia."},
  ],
  'bento-1': [
    {"tipo":"multipla","enunciado":"¿Cuál era el lema de San Benito?","opcoes":["Reza y trabaja","Descansa y juega","Estudia y viaja"],"correta":0,"explicacao":"En latín se dice Ora et labora: rezar y trabajar."},
    {"tipo":"vf","enunciado":"San Benito es el patrono de Europa.","correta":true,"explicacao":"Sus monjes ayudaron a llevar la fe por toda Europa."},
    {"tipo":"multipla","enunciado":"¿En qué país nació San Benito?","opcoes":["Italia","Brasil","Japón"],"correta":0,"explicacao":"Benito nació en una ciudad de Italia llamada Nursia."},
    {"tipo":"vf","enunciado":"La tradición cuenta que San Benito tenía una hermana gemela, Santa Escolástica.","correta":true,"explicacao":"Los dos hermanos amaban mucho a Dios."},
    {"tipo":"multipla","enunciado":"¿Adónde fue Benito a rezar solo cuando era joven?","opcoes":["A una cueva","A un barco","A un castillo"],"correta":0,"explicacao":"Vivió en una cueva, rezando en silencio, cerca de Subiaco."},
    {"tipo":"vf","enunciado":"Benito dejó la gran ciudad para estar más cerca de Dios.","correta":true,"explicacao":"Salió de Roma para rezar en paz."},
    {"tipo":"multipla","enunciado":"¿Cómo se llama quien vive en un monasterio, rezando y trabajando?","opcoes":["Monje","Marinero","Bombero"],"correta":0,"explicacao":"Los monjes rezan juntos varias veces al día."},
    {"tipo":"vf","enunciado":"San Benito vivió hace poco, en la época de los celulares.","correta":false,"explicacao":"San Benito vivió hace muchísimo tiempo, mucho antes que nuestros abuelos."},
    {"tipo":"multipla","enunciado":"¿Qué casa grande construyó Benito para los monjes?","opcoes":["Un monasterio","Un palacio","Un castillo"],"correta":0,"explicacao":"Su monasterio más famoso está en Montecasino."},
    {"tipo":"vf","enunciado":"Benito enseñó que trabajar también es una forma de alabar a Dios.","correta":true,"explicacao":"Quien trabaja con amor está sirviendo a Dios."},
  ],
  'bento-2': [
    {"tipo":"multipla","enunciado":"San Benito escribió un libro para los monjes. ¿Cómo se llama?","opcoes":["La Regla","El Mapa","La Receta"],"correta":0,"explicacao":"La Regla enseña a vivir juntos, rezando y trabajando."},
    {"tipo":"vf","enunciado":"Muchos monasterios siguen hoy la Regla de San Benito.","correta":true,"explicacao":"Desde hace muchísimos años guía a monjes y monjas."},
    {"tipo":"multipla","enunciado":"¿Cuál es la primera palabra de la Regla?","opcoes":["Escucha","Corre","Duerme"],"correta":0,"explicacao":"Benito empieza pidiendo: escucha, hijo, con el oído del corazón."},
    {"tipo":"vf","enunciado":"Según la Regla, cada visitante debe ser recibido como si fuera Jesús.","correta":true,"explicacao":"Recibir bien a las personas es una forma de amar a Jesús."},
    {"tipo":"multipla","enunciado":"¿Cómo se llama el monje que cuida de todo el monasterio?","opcoes":["Abad","Capitán","Alcalde"],"correta":0,"explicacao":"Abad quiere decir padre: cuida de los monjes como un padre."},
    {"tipo":"ordenar","enunciado":"Arma la frase de San Benito:","blocos":["Que en todo","sea Dios","glorificado"],"explicacao":"Todo lo que hacemos puede ser para la gloria de Dios."},
    {"tipo":"vf","enunciado":"Para San Benito, la oración va antes que todo.","correta":true,"explicacao":"Enseñaba: que nada se anteponga a la oración."},
    {"tipo":"multipla","enunciado":"¿Qué hacen juntos los monjes varias veces al día?","opcoes":["Rezan","Bailan","Viajan"],"correta":0,"explicacao":"Cantan salmos y alaban a Dios en distintos momentos del día."},
    {"tipo":"vf","enunciado":"La Regla enseña a los monjes a pelear entre ellos.","correta":false,"explicacao":"La Regla enseña la paz, la obediencia y el amor entre hermanos."},
    {"tipo":"multipla","enunciado":"¿Dónde viven los monjes?","opcoes":["En un monasterio","En un circo","En un barco"],"correta":0,"explicacao":"El monasterio es la casa de los monjes, donde rezan y trabajan."},
  ],
  'bento-3': [
    {"tipo":"vf","enunciado":"La medalla de San Benito tiene una oración para alejar el mal.","correta":true,"explicacao":"Sus letritas son pedidos de protección a Dios."},
    {"tipo":"multipla","enunciado":"¿Dónde estaba el monasterio más famoso de San Benito?","opcoes":["Montecasino","Río de Janeiro","París"],"correta":0,"explicacao":"El monasterio de Montecasino está en lo alto de una montaña, en Italia."},
    {"tipo":"multipla","enunciado":"¿Qué aparece en la medalla de San Benito?","opcoes":["Una cruz","Un ancla","Un pez"],"correta":0,"explicacao":"La cruz nos recuerda que Jesús venció el mal por amor."},
    {"tipo":"vf","enunciado":"En una historia antigua, un cuervo le quitó a Benito un pan que tenía veneno.","correta":true,"explicacao":"Por eso el cuervo aparece en las imágenes de San Benito."},
    {"tipo":"multipla","enunciado":"¿Qué pájaro aparece en las imágenes de San Benito?","opcoes":["Un cuervo","Un loro","Una gallina"],"correta":0,"explicacao":"El cuervo recuerda cómo Dios protegió a Benito."},
    {"tipo":"vf","enunciado":"En la medalla está escrito: la santa cruz sea mi luz.","correta":true,"explicacao":"En latín: Crux sacra sit mihi lux."},
    {"tipo":"multipla","enunciado":"¿Quién escribió la historia de San Benito?","opcoes":["El papa San Gregorio","Un rey","Un soldado"],"correta":0,"explicacao":"El papa Gregorio contó la vida de Benito en un libro."},
    {"tipo":"vf","enunciado":"La medalla de San Benito es un amuleto de la suerte.","correta":false,"explicacao":"La medalla no es un amuleto: nos recuerda rezar y confiar en Dios."},
    {"tipo":"multipla","enunciado":"¿Para qué sirve la medalla de San Benito?","opcoes":["Para recordar a Dios y pedir protección","Para ganar juegos","Para hacerse rico"],"correta":0,"explicacao":"Nos ayuda a recordar que Dios nos protege."},
    {"tipo":"vf","enunciado":"Cuando hacemos la señal de la cruz, recordamos que Jesús nos protege.","correta":true,"explicacao":"Benito hacía la señal de la cruz con mucha fe."},
  ],
  'clara-1': [
    {"tipo":"multipla","enunciado":"¿Quién ayudó a Clara a seguir a Jesús?","opcoes":["San Francisco","San Benito","San Antonio"],"correta":0,"explicacao":"Francisco era de la misma ciudad y le enseñó a Clara a vivir pobre, como Jesús."},
    {"tipo":"vf","enunciado":"Clara empezó una familia de hermanas que rezan, las Clarisas.","correta":true,"explicacao":"Las hermanas Clarisas existen hasta hoy en el mundo entero."},
    {"tipo":"multipla","enunciado":"¿De qué tipo de familia venía Clara?","opcoes":["Rica","Pobre","De pescadores"],"correta":0,"explicacao":"Clara dejó una casa llena de comodidades para seguir a Jesús."},
    {"tipo":"vf","enunciado":"Clara salió de casa de noche para seguir a Jesús.","correta":true,"explicacao":"Fue una decisión valiente, llena de amor a Dios."},
    {"tipo":"multipla","enunciado":"¿En qué ciudad nació Clara?","opcoes":["Asís","Lisboa","París"],"correta":0,"explicacao":"Clara nació en Asís, la misma ciudad de San Francisco."},
    {"tipo":"vf","enunciado":"Francisco le cortó el cabello a Clara para mostrar que era toda de Dios.","correta":true,"explicacao":"Fue la manera de mostrar que Clara había elegido a Jesús."},
    {"tipo":"multipla","enunciado":"¿Qué hermana de Clara también se fue a seguir a Jesús con ella?","opcoes":["Inés","Rita","Mónica"],"correta":0,"explicacao":"Inés siguió a Clara pocos días después."},
    {"tipo":"vf","enunciado":"Clara quería ser rica y famosa.","correta":false,"explicacao":"Clara eligió ser pobre para tener a Jesús como su tesoro."},
    {"tipo":"multipla","enunciado":"¿Dónde vivió Clara toda la vida con sus hermanas?","opcoes":["En San Damián","En un castillo","En un barco"],"correta":0,"explicacao":"San Damián era la iglesita que Francisco había arreglado."},
    {"tipo":"vf","enunciado":"Clara y Francisco eran amigos en la fe.","correta":true,"explicacao":"Se ayudaban a amar más a Jesús."},
  ],
  'clara-2': [
    {"tipo":"multipla","enunciado":"¿Qué llevaba Clara en las manos cuando unos soldados llegaron al convento?","opcoes":["La hostia, que es Jesús","Una espada","Un escudo"],"correta":0,"explicacao":"Clara confió en Jesús presente en la hostia."},
    {"tipo":"vf","enunciado":"Aun enferma, Clara enfrentó a los soldados con fe.","correta":true,"explicacao":"No usó armas: usó la oración."},
    {"tipo":"multipla","enunciado":"¿Qué hicieron los soldados después de que Clara rezó?","opcoes":["Se fueron","Hicieron una fiesta","Se quedaron a vivir allí"],"correta":0,"explicacao":"La historia cuenta que huyeron, y las hermanas quedaron protegidas."},
    {"tipo":"vf","enunciado":"Clara escribía cartas con consejos a una princesa llamada Inés.","correta":true,"explicacao":"Inés de Praga también lo dejó todo para seguir a Jesús pobre."},
    {"tipo":"multipla","enunciado":"¿Cuál era el consejo de Clara en sus cartas?","opcoes":["Mirar a Jesús con amor","Comprar muchas cosas","Estar siempre enojado"],"correta":0,"explicacao":"Clara enseñaba a mirar a Jesús con el corazón."},
    {"tipo":"ordenar","enunciado":"Arma la historia de Clara:","blocos":["Llegan los soldados","Clara reza con Jesús","Los soldados huyen"],"explicacao":"La oración de Clara protegió a las hermanas."},
    {"tipo":"vf","enunciado":"Clara escribió una regla para que las hermanas vivieran pobres y rezando.","correta":true,"explicacao":"El Papa aprobó la regla poco antes de que Clara se fuera al Cielo."},
    {"tipo":"multipla","enunciado":"¿Qué le pidió Clara al Papa toda la vida?","opcoes":["Poder vivir pobre","Mucho dinero","Un palacio"],"correta":0,"explicacao":"Clara quería vivir solo con Dios, sin guardar riquezas."},
    {"tipo":"vf","enunciado":"A Clara le gustaba guardar joyas y dinero.","correta":false,"explicacao":"El tesoro de Clara era Jesús, no las riquezas."},
    {"tipo":"multipla","enunciado":"Clara amaba a Jesús en la Eucaristía. ¿Dónde recibimos la Eucaristía?","opcoes":["En la misa","En el mercado","En la escuela"],"correta":0,"explicacao":"En la misa, Jesús se nos da en la Comunión."},
  ],
  'clara-3': [
    {"tipo":"vf","enunciado":"Santa Clara es la patrona de la televisión.","correta":true,"explicacao":"Enferma, vio la misa desde lejos, como si fuera en una pantalla."},
    {"tipo":"multipla","enunciado":"¿Cuál era el mayor tesoro de Clara?","opcoes":["Jesús","El oro","Las tierras"],"correta":0,"explicacao":"Para Clara, quien tiene a Jesús lo tiene todo."},
    {"tipo":"multipla","enunciado":"¿Por qué Clara es patrona de la televisión?","opcoes":["Vio la misa desde lejos, enferma en la cama","Le gustaban las películas","Inventó la televisión"],"correta":0,"explicacao":"Dios le permitió seguir la misa sin levantarse de la cama."},
    {"tipo":"vf","enunciado":"El nombre Clara recuerda la luz y la claridad.","correta":true,"explicacao":"La vida de Clara iluminó a muchas personas."},
    {"tipo":"multipla","enunciado":"¿Cómo se llaman las hermanas que siguen a Santa Clara?","opcoes":["Clarisas","Carmelitas","Benedictinas"],"correta":0,"explicacao":"Clarisas viene del nombre de Clara."},
    {"tipo":"vf","enunciado":"Clara fue declarada santa muy poco tiempo después de morir.","correta":true,"explicacao":"La gente ya sabía que era santa."},
    {"tipo":"multipla","enunciado":"¿Cómo vivía Clara?","opcoes":["Con sencillez y alegría","Con lujo y vanidad","Con rabia"],"correta":0,"explicacao":"Era pobre, pero muy alegre."},
    {"tipo":"vf","enunciado":"Clara estaba triste por haber dejado la riqueza.","correta":false,"explicacao":"Clara era feliz porque tenía a Jesús en el corazón."},
    {"tipo":"multipla","enunciado":"¿Qué hacía Clara muchas horas al día?","opcoes":["Rezaba","Dormía","Paseaba"],"correta":0,"explicacao":"Clara rezaba mucho y cuidaba de sus hermanas con cariño."},
    {"tipo":"vf","enunciado":"Clara servía a sus hermanas y cuidaba a las que estaban enfermas.","correta":true,"explicacao":"Aunque era la madre abadesa, les lavaba los pies y las servía a todas."},
  ],
  'jpii-1': [
    {"tipo":"multipla","enunciado":"¿De qué país venía el papa Juan Pablo II?","opcoes":["Polonia","Italia","Brasil"],"correta":0,"explicacao":"Nació en Polonia, un país de Europa."},
    {"tipo":"vf","enunciado":"Juan Pablo II se llamaba Karol.","correta":true,"explicacao":"Karol es la forma polaca de decir Carlos."},
    {"tipo":"multipla","enunciado":"¿Qué consejo famoso dio Juan Pablo II a todos?","opcoes":["¡No tengáis miedo!","¡Quédense callados!","¡Váyanse a dormir!"],"correta":0,"explicacao":"Quería que nadie tuviera miedo de abrirle el corazón a Jesús."},
    {"tipo":"vf","enunciado":"De joven, Karol trabajó rompiendo piedras en una cantera.","correta":true,"explicacao":"Sabía lo duro que es el trabajo de cada día."},
    {"tipo":"multipla","enunciado":"¿Qué le gustaba hacer a Karol cuando era joven?","opcoes":["Teatro y deportes","Pelear","Quedarse quieto"],"correta":0,"explicacao":"Hacía teatro y le encantaba esquiar en las montañas."},
    {"tipo":"vf","enunciado":"Juan Pablo II fue papa durante muchos años.","correta":true,"explicacao":"Guió a la Iglesia durante mucho tiempo, visitando el mundo entero."},
    {"tipo":"multipla","enunciado":"¿De quién es pastor el Papa?","opcoes":["De toda la Iglesia","De un solo país","Solo de los sacerdotes"],"correta":0,"explicacao":"El Papa cuida de todos los católicos del mundo."},
    {"tipo":"vf","enunciado":"Juan Pablo II nunca salió de Roma.","correta":false,"explicacao":"Viajó por el mundo entero llevando a Jesús a muchos pueblos."},
    {"tipo":"multipla","enunciado":"¿Cómo le gustaba a Juan Pablo II estar cerca de la gente?","opcoes":["Viajando y visitando","Encerrado en casa","Escondido"],"correta":0,"explicacao":"Visitó muchísimos países."},
    {"tipo":"vf","enunciado":"Hoy Juan Pablo II es santo.","correta":true,"explicacao":"La Iglesia declaró que está en el Cielo, junto a Dios."},
  ],
  'jpii-2': [
    {"tipo":"vf","enunciado":"Juan Pablo II creó la Jornada Mundial de la Juventud.","correta":true,"explicacao":"Es un gran encuentro de jóvenes de todo el mundo con el Papa."},
    {"tipo":"multipla","enunciado":"¿Qué oración cortita aparece en la imagen de Jesús Misericordioso?","opcoes":["Jesús, en ti confío","Buenos días, Jesús","Hasta luego, Jesús"],"correta":0,"explicacao":"Es una forma sencilla de decir que confiamos en el amor de Jesús."},
    {"tipo":"multipla","enunciado":"¿Qué santa amiga de Jesús Misericordioso declaró santa Juan Pablo II?","opcoes":["Santa Faustina","Santa Rita","Santa Clara"],"correta":0,"explicacao":"Faustina era una religiosa de Polonia, como él."},
    {"tipo":"vf","enunciado":"Juan Pablo II visitó Brasil.","correta":true,"explicacao":"Vino a Brasil tres veces y lo recibieron con mucha alegría."},
    {"tipo":"multipla","enunciado":"¿Cómo llamaba Juan Pablo II a los jóvenes?","opcoes":["Centinelas de la mañana","Perezosos","Niños perdidos"],"correta":0,"explicacao":"Un centinela espera que salga el sol, y el sol es Jesús."},
    {"tipo":"vf","enunciado":"Juan Pablo II quería mucho a los jóvenes.","correta":true,"explicacao":"Decía que los jóvenes son la esperanza de la Iglesia."},
    {"tipo":"ordenar","enunciado":"Arma la frase del Papa a los jóvenes:","blocos":["Vosotros sois","la esperanza","de la Iglesia"],"explicacao":"Creía que los jóvenes pueden cambiar el mundo con Jesús."},
    {"tipo":"multipla","enunciado":"¿De quién quería el Papa que los jóvenes fueran amigos?","opcoes":["De Jesús","Solo de los famosos","De nadie"],"correta":0,"explicacao":"Para él, Jesús es el mejor amigo que alguien puede tener."},
    {"tipo":"vf","enunciado":"Juan Pablo II pensaba que los santos solo existían antes.","correta":false,"explicacao":"Mostró que hoy también hay santos, y que tú también puedes serlo."},
    {"tipo":"multipla","enunciado":"¿Cómo se llama el encuentro de los jóvenes con el Papa?","opcoes":["Jornada Mundial de la Juventud","Copa del Mundo","Fiesta de junio"],"correta":0,"explicacao":"En la Jornada, jóvenes de muchos países rezan y cantan juntos."},
  ],
  'jpii-3': [
    {"tipo":"vf","enunciado":"Juan Pablo II perdonó al hombre que le disparó.","correta":true,"explicacao":"Fue a visitarlo a la cárcel y habló con él como con un hermano."},
    {"tipo":"multipla","enunciado":"¿Qué nuevos misterios del rosario creó Juan Pablo II?","opcoes":["Los misterios luminosos","Los misterios del mar","Los misterios de las estrellas"],"correta":0,"explicacao":"Recuerdan momentos de la vida de Jesús, como su bautismo y la boda de Caná."},
    {"tipo":"multipla","enunciado":"¿Qué hizo el Papa después de ser atacado?","opcoes":["Perdonó","Se llenó de odio","Quiso venganza"],"correta":0,"explicacao":"Perdonar es la manera de Jesús de vencer el mal."},
    {"tipo":"vf","enunciado":"Juan Pablo II le dio gracias a la Virgen por haberlo salvado.","correta":true,"explicacao":"Dijo que la Virgen lo protegió ese día."},
    {"tipo":"multipla","enunciado":"¿A qué advocación de la Virgen le agradeció el Papa por haberlo salvado?","opcoes":["Nuestra Señora de Fátima","Nuestra Señora del Carmen","Nuestra Señora de la Luz"],"correta":0,"explicacao":"El ataque ocurrió el día de Nuestra Señora de Fátima."},
    {"tipo":"vf","enunciado":"Ya anciano y enfermo, Juan Pablo II siguió trabajando.","correta":true,"explicacao":"Mostró que hasta la enfermedad se puede ofrecer a Dios con amor."},
    {"tipo":"multipla","enunciado":"¿Qué gritaba la gente en la despedida de Juan Pablo II?","opcoes":["¡Santo ya!","¡Vete!","¡Silencio!"],"correta":0,"explicacao":"La gente estaba segura de que era un santo."},
    {"tipo":"vf","enunciado":"Juan Pablo II fue declarado santo el mismo día que el papa Juan XXIII.","correta":true,"explicacao":"Fue una fiesta con dos papas santos."},
    {"tipo":"multipla","enunciado":"¿Cuál era la oración preferida de Juan Pablo II?","opcoes":["El rosario","La novena de Navidad","El Vía Crucis"],"correta":0,"explicacao":"Él mismo dijo que el rosario era su oración preferida."},
    {"tipo":"vf","enunciado":"Perdonar es guardar rabia en el corazón.","correta":false,"explicacao":"Perdonar es soltar la rabia y dejar que Dios sane el corazón."},
  ],
  'rita-1': [
    {"tipo":"multipla","enunciado":"Santa Rita es la santa de...","opcoes":["Las causas imposibles","Los viajes","Los deportes"],"correta":0,"explicacao":"Cuando algo parece imposible, le pedimos a Rita que rece por nosotros."},
    {"tipo":"vf","enunciado":"Rita estuvo casada y tuvo hijos antes de ser monja.","correta":true,"explicacao":"Fue santa como esposa, como mamá y como monja."},
    {"tipo":"multipla","enunciado":"¿En qué país nació Rita?","opcoes":["Italia","España","Japón"],"correta":0,"explicacao":"Rita nació en una aldea de Italia llamada Roccaporena."},
    {"tipo":"vf","enunciado":"Desde niña, Rita quería entregar su vida a Dios.","correta":true,"explicacao":"Pero obedeció a sus papás, se casó y vivió con mucha fe."},
    {"tipo":"multipla","enunciado":"¿Cómo era el marido de Rita al principio?","opcoes":["Enojón y difícil","Muy tranquilo","Muy tímido"],"correta":0,"explicacao":"Rita tuvo paciencia y rezó mucho por él."},
    {"tipo":"vf","enunciado":"Con paciencia y oración, Rita ayudó a su marido a volverse más bondadoso.","correta":true,"explicacao":"El amor de Rita tocó el corazón de él."},
    {"tipo":"multipla","enunciado":"¿Cuántos hijos tuvo Rita?","opcoes":["Dos","Diez","Ninguno"],"correta":0,"explicacao":"Tuvo dos niños y les enseñó a amar a Dios."},
    {"tipo":"vf","enunciado":"Rita gritaba y peleaba con todo el mundo.","correta":false,"explicacao":"Rita era mansa y respondía con paciencia y cariño."},
    {"tipo":"multipla","enunciado":"¿Qué flor nos recuerda a Santa Rita?","opcoes":["La rosa","El girasol","La margarita"],"correta":0,"explicacao":"Por una rosa que floreció en invierno."},
    {"tipo":"vf","enunciado":"Rita rezaba por su familia.","correta":true,"explicacao":"La oración era la fuerza de Rita en casa."},
  ],
  'rita-2': [
    {"tipo":"multipla","enunciado":"Cuando el marido de Rita murió en una pelea, ¿qué eligió ella?","opcoes":["Perdonar","Vengarse","Huir"],"correta":0,"explicacao":"Rita eligió el perdón, aunque le dolía el corazón."},
    {"tipo":"vf","enunciado":"Rita perdonó a quienes le hicieron daño a su marido.","correta":true,"explicacao":"El perdón de Rita trajo paz a las familias."},
    {"tipo":"multipla","enunciado":"¿Qué quería Rita que hicieran las familias?","opcoes":["Que hicieran las paces","Que siguieran peleando","Que se mudaran de ciudad"],"correta":0,"explicacao":"Rezó y trabajó para que todos vivieran en paz."},
    {"tipo":"vf","enunciado":"Rita logró que las familias enemigas hicieran las paces.","correta":true,"explicacao":"La tradición cuenta que, después de eso, pudo entrar en el convento."},
    {"tipo":"multipla","enunciado":"¿Qué virtud de Rita se recuerda más?","opcoes":["El perdón","La prisa","La vanidad"],"correta":0,"explicacao":"Perdonar es un regalo que sana el corazón."},
    {"tipo":"ordenar","enunciado":"Arma la oración a Santa Rita:","blocos":["Santa Rita,","abogada","de las causas imposibles"],"explicacao":"Abogada es quien nos defiende: Rita reza por nosotros ante Dios."},
    {"tipo":"vf","enunciado":"Perdonar quiere decir que el mal no tiene importancia.","correta":false,"explicacao":"Perdonar no es decir que el mal está bien: es no guardar odio en el corazón."},
    {"tipo":"multipla","enunciado":"¿Qué ayudaba a Rita a perdonar?","opcoes":["La oración","La rabia","El miedo"],"correta":0,"explicacao":"Rezando, Rita encontraba fuerzas para perdonar."},
    {"tipo":"vf","enunciado":"Quien perdona se queda con el corazón más ligero.","correta":true,"explicacao":"El perdón le quita al corazón un peso muy grande."},
    {"tipo":"multipla","enunciado":"Después de que las familias hicieron las paces, ¿adónde fue a vivir Rita?","opcoes":["A un convento","A un castillo","A un barco"],"correta":0,"explicacao":"Rita se hizo monja en el convento de Casia."},
  ],
  'rita-3': [
    {"tipo":"vf","enunciado":"Rita recibió en la frente una herida, como la de una espina de la corona de Jesús.","correta":true,"explicacao":"Quiso sentir un poquito del dolor de Jesús, por amor."},
    {"tipo":"multipla","enunciado":"¿En qué ciudad está el convento de Santa Rita?","opcoes":["Casia","Lisboa","París"],"correta":0,"explicacao":"Por eso se llama Rita de Casia."},
    {"tipo":"multipla","enunciado":"¿Qué floreció en invierno cuando Rita lo pidió?","opcoes":["Una rosa","Un girasol","Una margarita"],"correta":0,"explicacao":"La tradición cuenta que encontraron una rosa en el jardín, en pleno invierno."},
    {"tipo":"vf","enunciado":"La tradición cuenta que Rita pidió higos en invierno y aparecieron.","correta":true,"explicacao":"Dios tuvo ese cariño con su amiga enferma."},
    {"tipo":"multipla","enunciado":"¿Delante de quién rezaba Rita cuando recibió la espina?","opcoes":["De Jesús en la cruz","De un rey","De un espejo"],"correta":0,"explicacao":"Rezaba mirando a Jesús crucificado."},
    {"tipo":"vf","enunciado":"Muchos peregrinos visitan a Santa Rita en Casia.","correta":true,"explicacao":"Mucha gente va allí a pedirle que rece por nosotros."},
    {"tipo":"multipla","enunciado":"¿Por qué la rosa es el símbolo de Santa Rita?","opcoes":["Floreció en invierno cuando ella lo pidió","Ella vendía flores","Ella solo plantaba rosas"],"correta":0,"explicacao":"La rosa nos recuerda que para Dios nada es imposible."},
    {"tipo":"vf","enunciado":"Rita se quejaba de su herida todo el tiempo.","correta":false,"explicacao":"Rita le ofrecía su dolor a Jesús, con paciencia."},
    {"tipo":"multipla","enunciado":"Cuando le pedimos a Dios algo difícil, ¿a quién podemos pedir que rece con nosotros?","opcoes":["A Santa Rita","A un mago","A la suerte"],"correta":0,"explicacao":"Rita reza por nosotros ante Dios."},
    {"tipo":"vf","enunciado":"Santa Rita vivió hace mucho tiempo, pero todavía hoy la quieren mucho.","correta":true,"explicacao":"En muchas iglesias hay una imagen de Santa Rita con rosas."},
  ],
  'judas-1': [
    {"tipo":"multipla","enunciado":"¿Cuántos apóstoles eligió Jesús?","opcoes":["Doce","Tres","Cien"],"correta":0,"explicacao":"Judas Tadeo era uno de los doce amigos más cercanos de Jesús."},
    {"tipo":"vf","enunciado":"San Judas Tadeo es el mismo Judas que traicionó a Jesús.","correta":false,"explicacao":"Son dos personas distintas: Judas Tadeo fue fiel a Jesús hasta el final."},
    {"tipo":"multipla","enunciado":"¿Con qué apóstol se celebra a San Judas Tadeo el mismo día?","opcoes":["San Simón","San Jorge","San Juan"],"correta":0,"explicacao":"Los dos apóstoles se recuerdan juntos."},
    {"tipo":"vf","enunciado":"En la Última Cena, Judas Tadeo le hizo una pregunta a Jesús.","correta":true,"explicacao":"Quería entender cómo se mostraría Jesús a sus amigos."},
    {"tipo":"multipla","enunciado":"¿Qué le respondió Jesús a Judas Tadeo?","opcoes":["Que vendría a vivir en quien lo ama","Que se iba de viaje","Que estaba cansado"],"correta":0,"explicacao":"Jesús y el Padre hacen su casa en el corazón de quien ama a Jesús."},
    {"tipo":"vf","enunciado":"El nombre Tadeo ayuda a no confundir a los dos Judas.","correta":true,"explicacao":"Así sabemos que hablamos del apóstol fiel."},
    {"tipo":"multipla","enunciado":"¿Qué es un apóstol?","opcoes":["Un amigo enviado por Jesús","Un soldado romano","Un rey"],"correta":0,"explicacao":"Apóstol quiere decir enviado: lleva a Jesús a los demás."},
    {"tipo":"vf","enunciado":"Según la tradición, Judas Tadeo dio la vida por amor a Jesús.","correta":true,"explicacao":"Fue fiel hasta el final, anunciando a Jesús."},
    {"tipo":"multipla","enunciado":"Según la tradición, ¿qué era Judas Tadeo de Jesús?","opcoes":["Pariente","Vecino","Desconocido"],"correta":0,"explicacao":"Muchos creen que era primo de Jesús."},
    {"tipo":"vf","enunciado":"La tradición cuenta que Judas Tadeo anunció a Jesús en tierras lejanas.","correta":true,"explicacao":"Después de que Jesús subió al Cielo, salió por el mundo hablando de Dios."},
  ],
  'judas-2': [
    {"tipo":"multipla","enunciado":"¿Qué libro de la Biblia lleva el nombre de Judas?","opcoes":["La Carta de Judas","El Libro de los Salmos","El Evangelio de Marcos"],"correta":0,"explicacao":"Es una carta cortita del Nuevo Testamento."},
    {"tipo":"vf","enunciado":"La Carta de Judas es muy cortita.","correta":true,"explicacao":"Tiene un solo capítulo."},
    {"tipo":"multipla","enunciado":"¿En qué parte de la Biblia está la Carta de Judas?","opcoes":["En el Nuevo Testamento","En el Antiguo Testamento","En el Libro de los Salmos"],"correta":0,"explicacao":"El Nuevo Testamento cuenta la vida de Jesús y de los primeros cristianos."},
    {"tipo":"vf","enunciado":"La Carta de Judas pide a los cristianos que cuiden la fe.","correta":true,"explicacao":"Pide que cuidemos la fe como un tesoro."},
    {"tipo":"multipla","enunciado":"¿Qué pide la carta que hagamos con quien tiene dudas?","opcoes":["Tenerle compasión","Pelear","Burlarnos"],"correta":0,"explicacao":"Compasión es tratar al otro con cariño y paciencia."},
    {"tipo":"ordenar","enunciado":"Arma el consejo de la Carta de Judas:","blocos":["Manteneos","en el amor","de Dios"],"explicacao":"Quedarse en el amor de Dios es lo que más importa."},
    {"tipo":"vf","enunciado":"La Carta de Judas va justo antes del último libro de la Biblia.","correta":true,"explicacao":"El último libro de la Biblia es el Apocalipsis."},
    {"tipo":"multipla","enunciado":"¿Cómo termina la Carta de Judas?","opcoes":["Con una alabanza a Dios","Con una lista de nombres","Con una historia de guerra"],"correta":0,"explicacao":"Termina dando gloria a Dios, que nos cuida."},
    {"tipo":"vf","enunciado":"La Carta de Judas manda despreciar a quien tiene dudas.","correta":false,"explicacao":"La carta pide compasión: ayudar con cariño a quien está confundido."},
    {"tipo":"multipla","enunciado":"¿Por qué la Carta de Judas se llama carta católica?","opcoes":["Es para todos los cristianos","Es solo para sacerdotes","Es un secreto"],"correta":0,"explicacao":"Católico quiere decir para todos, en el mundo entero."},
  ],
  'judas-3': [
    {"tipo":"vf","enunciado":"A San Judas Tadeo lo llaman el santo de las causas difíciles.","correta":true,"explicacao":"Cuando todo parece difícil, le pedimos que rece por nosotros."},
    {"tipo":"multipla","enunciado":"¿Qué aparece sobre la cabeza de San Judas en las imágenes?","opcoes":["Una llama","Un sombrero","Una corona"],"correta":0,"explicacao":"La llama recuerda al Espíritu Santo, que vino sobre los apóstoles."},
    {"tipo":"multipla","enunciado":"¿Qué rostro lleva San Judas en el pecho, en las imágenes?","opcoes":["El rostro de Jesús","El rostro de un rey","El rostro de un ángel"],"correta":0,"explicacao":"Lleva a Jesús bien cerca del corazón."},
    {"tipo":"vf","enunciado":"En São Paulo hay un santuario de San Judas Tadeo muy visitado.","correta":true,"explicacao":"Todos los días mucha gente va allí a rezar."},
    {"tipo":"multipla","enunciado":"¿Qué fiesta recuerda la llama sobre San Judas?","opcoes":["Pentecostés","Navidad","Pascua"],"correta":0,"explicacao":"En Pentecostés, el Espíritu Santo vino como lenguas de fuego."},
    {"tipo":"vf","enunciado":"Pedirle a un santo que rece por nosotros es cambiar a Dios por el santo.","correta":false,"explicacao":"Solo Dios es adorado; los santos son amigos que rezan por nosotros."},
    {"tipo":"multipla","enunciado":"Cuando le pedimos ayuda a San Judas, ¿qué hace él?","opcoes":["Reza a Dios por nosotros","Hace magia","Nada"],"correta":0,"explicacao":"Los santos son amigos de Dios y rezan junto con nosotros."},
    {"tipo":"vf","enunciado":"Los santos son amigos de Dios.","correta":true,"explicacao":"Vivieron con mucho amor y hoy están con Dios en el Cielo."},
    {"tipo":"multipla","enunciado":"¿Cuál es una oración cortita a San Judas?","opcoes":["San Judas Tadeo, ruega por nosotros","San Judas Tadeo, vamos a jugar","San Judas Tadeo, hasta mañana"],"correta":0,"explicacao":"Ruega por nosotros quiere decir: reza por nosotros."},
    {"tipo":"vf","enunciado":"Tener esperanza es confiar en que Dios nos cuida.","correta":true,"explicacao":"San Judas es el apóstol de la esperanza."},
  ],
  'avila-1': [
    {"tipo":"multipla","enunciado":"¿En qué país nació Santa Teresa de Ávila?","opcoes":["España","Italia","Brasil"],"correta":0,"explicacao":"Nació en la ciudad de Ávila, en España."},
    {"tipo":"vf","enunciado":"De niña, Teresa huyó con su hermano soñando con dar la vida por Jesús.","correta":true,"explicacao":"Un tío los encontró en el camino y los llevó de vuelta a casa."},
    {"tipo":"multipla","enunciado":"Teresa era monja carmelita. ¿Qué hacen mucho las carmelitas?","opcoes":["Rezan","Corren","Viajan en avión"],"correta":0,"explicacao":"Las carmelitas pasan mucho tiempo rezando en silencio."},
    {"tipo":"vf","enunciado":"Teresa abrió muchas casas nuevas para que las hermanas rezaran.","correta":true,"explicacao":"Fundó muchos conventos por España."},
    {"tipo":"multipla","enunciado":"¿Cómo viajaba Teresa por España?","opcoes":["En carreta","En tren","En coche"],"correta":0,"explicacao":"Viajaba en carretas sencillas, por caminos difíciles."},
    {"tipo":"vf","enunciado":"Teresa tenía la salud débil, pero trabajó mucho por Dios.","correta":true,"explicacao":"Ni la enfermedad hizo que Teresa se rindiera."},
    {"tipo":"multipla","enunciado":"¿Cuál fue el primer convento que fundó Teresa?","opcoes":["San José","San Damián","Montecasino"],"correta":0,"explicacao":"El convento de San José está en Ávila."},
    {"tipo":"vf","enunciado":"Teresa era siempre seria y nunca bromeaba.","correta":false,"explicacao":"Teresa era alegre y hacía reír a las hermanas."},
    {"tipo":"multipla","enunciado":"¿Qué enseñaba Teresa a las hermanas?","opcoes":["A rezar con el corazón","A hacerse ricas","A pelear"],"correta":0,"explicacao":"Para Teresa, rezar es hablar con un amigo."},
    {"tipo":"vf","enunciado":"Santa Teresa es Doctora de la Iglesia, una gran maestra de la fe.","correta":true,"explicacao":"Fue la primera mujer en recibir ese título."},
  ],
  'avila-2': [
    {"tipo":"multipla","enunciado":"¿Con qué comparó Teresa nuestra alma?","opcoes":["Con un castillo","Con una caja","Con un coche"],"correta":0,"explicacao":"Un castillo precioso, con Dios viviendo en el centro."},
    {"tipo":"ordenar","enunciado":"Arma el poema de Teresa:","blocos":["Nada te turbe,","nada te espante,","solo Dios basta"],"explicacao":"Cuando tenemos a Dios, no necesitamos tener miedo."},
    {"tipo":"multipla","enunciado":"¿Cuántas moradas tiene el castillo de Teresa?","opcoes":["Siete","Dos","Cien"],"correta":0,"explicacao":"Cada morada es un paso para estar más cerca de Dios."},
    {"tipo":"vf","enunciado":"Para Teresa, Dios vive en el centro del castillo del alma.","correta":true,"explicacao":"Dios está dentro de nosotros, bien cerquita."},
    {"tipo":"multipla","enunciado":"Según Teresa, ¿cuál es la puerta para entrar en el castillo?","opcoes":["La oración","El dinero","La fama"],"correta":0,"explicacao":"Rezando, entramos en el castillo y encontramos a Dios."},
    {"tipo":"vf","enunciado":"Teresa escribió libros para enseñar a rezar a las hermanas.","correta":true,"explicacao":"Uno de ellos se llama Camino de perfección."},
    {"tipo":"vf","enunciado":"Teresa decía que el alma es fea y oscura.","correta":false,"explicacao":"Teresa decía que el alma es hermosa como un castillo de cristal."},
    {"tipo":"multipla","enunciado":"¿De qué era el castillo que imaginó Teresa?","opcoes":["De cristal o diamante","De arena","De cartón"],"correta":0,"explicacao":"Es una forma de decir que Dios nos hizo muy bonitos por dentro."},
    {"tipo":"vf","enunciado":"Quien tiene a Dios no necesita tener miedo de nada.","correta":true,"explicacao":"Teresa escribió: quien a Dios tiene nada le falta."},
    {"tipo":"multipla","enunciado":"Según Teresa, ¿dónde podemos encontrar a Dios?","opcoes":["Dentro de nuestro corazón","Solo en el cielo azul","En ningún lugar"],"correta":0,"explicacao":"Dios está más cerca de lo que imaginamos."},
  ],
  'avila-3': [
    {"tipo":"multipla","enunciado":"Para Teresa, rezar es:","opcoes":["Hablar con un amigo que nos ama","Repetir palabras sin pensar","Solo pedir regalos"],"correta":0,"explicacao":"Teresa decía que rezar es hablar con Dios como amigos."},
    {"tipo":"vf","enunciado":"San Juan de la Cruz fue amigo y ayudante de Teresa.","correta":true,"explicacao":"Los dos trabajaron juntos para renovar la vida de las hermanas y los frailes carmelitas."},
    {"tipo":"multipla","enunciado":"¿Dónde decía Teresa que también está Dios?","opcoes":["Entre los pucheros de la cocina","Solo en los palacios","Lejos de nosotros"],"correta":0,"explicacao":"Hasta lavando los platos podemos estar con Dios."},
    {"tipo":"vf","enunciado":"Teresa contó que un ángel le tocó el corazón con una flecha de fuego.","correta":true,"explicacao":"Era una señal del amor enorme de Dios por ella."},
    {"tipo":"multipla","enunciado":"Un artista hizo una estatua famosa de Teresa. ¿Con quién aparece?","opcoes":["Con un ángel","Con un león","Con un rey"],"correta":0,"explicacao":"La estatua muestra al ángel que le tocó el corazón con el amor de Dios."},
    {"tipo":"vf","enunciado":"Teresa estaba de viaje cuando se fue al Cielo.","correta":true,"explicacao":"Hasta el final, trabajó por las hermanas con mucho amor."},
    {"tipo":"multipla","enunciado":"Según Teresa, ¿cuál es la mejor forma de ser amigo de Dios?","opcoes":["Hablar con él todos los días","Olvidarse de él","Solo pedirle cosas"],"correta":0,"explicacao":"Los amigos hablan siempre, y a Dios le encanta escucharnos."},
    {"tipo":"vf","enunciado":"Teresa pensaba que solo se puede rezar dentro de la iglesia.","correta":false,"explicacao":"Podemos rezar en todas partes: en casa, en la escuela y hasta en la cocina."},
    {"tipo":"multipla","enunciado":"¿Quién era el mejor amigo de Teresa?","opcoes":["Jesús","Un rey","Una reina"],"correta":0,"explicacao":"Teresa hablaba con Jesús todos los días."},
    {"tipo":"vf","enunciado":"Los libros de Teresa ayudan a gente del mundo entero a rezar.","correta":true,"explicacao":"Por eso la llaman maestra de oración."},
  ],
});
