// ============================================================
//  LUMINA SANCTI — Perguntas das crianças em inglês
// ============================================================
// Tradução do trilhas-kids.js, com as mesmas chaves (um capítulo por
// chave), a mesma ordem e a mesma quantidade de atividades.

window.ATIVIDADES_KIDS_TRADUZIDAS = window.ATIVIDADES_KIDS_TRADUZIDAS || {};
window.ATIVIDADES_KIDS_TRADUZIDAS.en = Object.assign(window.ATIVIDADES_KIDS_TRADUZIDAS.en || {}, {
  'francisco-1': [
    {"tipo":"multipla","enunciado":"In which city was Saint Francis born?","opcoes":["Assisi","Rome","Lisbon"],"correta":0,"explicacao":"Francis was born in Assisi, a lovely little town in Italy."},
    {"tipo":"vf","enunciado":"When he was young, Francis dreamed of being a knight.","correta":true,"explicacao":"He wanted to be a famous knight, but God had an even bigger dream for him."},
    {"tipo":"multipla","enunciado":"What did Francis's father sell?","opcoes":["Cloth","Bread","Shoes"],"correta":0,"explicacao":"Francis's father sold beautiful cloth and was very rich."},
    {"tipo":"vf","enunciado":"Francis was born into a poor family.","correta":false,"explicacao":"His family was rich; Francis chose to be poor out of love for Jesus."},
    {"tipo":"multipla","enunciado":"What did Francis do when he met a very sick man on the road?","opcoes":["He gave him a hug","He ran away","He pretended not to see"],"correta":0,"explicacao":"Francis hugged the sick man, because he saw Jesus in those who suffer."},
    {"tipo":"vf","enunciado":"Francis gave back to his father even the clothes he was wearing.","correta":true,"explicacao":"He wanted to show that, from then on, his only treasure was the Father in Heaven."},
    {"tipo":"multipla","enunciado":"What kind of life did Francis choose?","opcoes":["A poor life, like Jesus","A king's life","A soldier's life"],"correta":0,"explicacao":"Francis wanted to live simply and poorly, as Jesus lived."},
    {"tipo":"vf","enunciado":"When he was young, Francis was held prisoner after a war.","correta":true,"explicacao":"In prison, Francis began to think more about God."},
    {"tipo":"multipla","enunciado":"After truly getting to know Jesus, Francis became:","opcoes":["Very joyful","Very angry","Very sad"],"correta":0,"explicacao":"Francis was so joyful that he sang praises to God along the roads."},
    {"tipo":"vf","enunciado":"When he was born, Francis was given the name John.","correta":true,"explicacao":"His mother had him baptized John, but everyone came to call him Francis."},
  ],
  'francisco-2': [
    {"tipo":"multipla","enunciado":"What did Jesus ask of Francis in the little church of San Damiano?","opcoes":["To take care of his Church","To live in a castle","To become a soldier"],"correta":0,"explicacao":"Jesus asked: go and repair my house, and Francis obeyed with joy."},
    {"tipo":"ordenar","enunciado":"Put together what Francis heard from Jesus:","blocos":["Francis,","go and repair","my house"],"explicacao":"Jesus called Francis to take care of his Church."},
    {"tipo":"multipla","enunciado":"What did Francis do first after hearing Jesus?","opcoes":["He fixed little churches with his hands","He went to sleep","He bought a horse"],"correta":0,"explicacao":"He carried stones and fixed the little church of San Damiano."},
    {"tipo":"vf","enunciado":"Francis fixed the little church of San Damiano with his own hands.","correta":true,"explicacao":"He carried stones and asked people passing by for help."},
    {"tipo":"multipla","enunciado":"What are the friends who followed Francis called?","opcoes":["Franciscans","Sailors","Knights"],"correta":0,"explicacao":"The Franciscans are the friars who live the way Francis taught."},
    {"tipo":"vf","enunciado":"Francis lived with his friends like brothers.","correta":true,"explicacao":"He called his companions brothers and shared everything with them."},
    {"tipo":"multipla","enunciado":"Who approved the way of life of Francis and his brothers?","opcoes":["The Pope","A king","A general"],"correta":0,"explicacao":"Francis went to Rome, and the Pope approved the life of the friars."},
    {"tipo":"vf","enunciado":"Francis was a priest.","correta":false,"explicacao":"Francis was never a priest, but he loved the Mass very much."},
    {"tipo":"multipla","enunciado":"How did Francis treat the poor?","opcoes":["With love, like brothers","With anger","With scorn"],"correta":0,"explicacao":"Francis shared what he had and treated every poor person as a brother."},
    {"tipo":"vf","enunciado":"Friars Minor means little and humble brothers.","correta":true,"explicacao":"They wanted to be the least of all, so they could serve everyone."},
  ],
  'francisco-3': [
    {"tipo":"multipla","enunciado":"In his canticle, what does Francis thank God for?","opcoes":["The sun, the moon and nature","Money","Castles"],"correta":0,"explicacao":"It is the Canticle of the Creatures: he praises God for Brother Sun and Sister Moon."},
    {"tipo":"vf","enunciado":"Francis called the sun Brother Sun.","correta":true,"explicacao":"For Francis, everything God created was a brother or a sister."},
    {"tipo":"multipla","enunciado":"In an old story, which fierce animal did Francis make peace with?","opcoes":["A wolf","A cat","A rabbit"],"correta":0,"explicacao":"The story tells that the wolf of Gubbio became gentle and a friend of the people."},
    {"tipo":"vf","enunciado":"Francis set up a living nativity scene on Christmas night.","correta":true,"explicacao":"He wanted everyone to see how Jesus was born, so poor, in Bethlehem."},
    {"tipo":"multipla","enunciado":"What was the nativity scene Francis set up like?","opcoes":["With real people and animals","Made of chocolate","Made of ice"],"correta":0,"explicacao":"With a real ox and a real donkey, he remembered the birth of Jesus."},
    {"tipo":"vf","enunciado":"Tradition says Francis even preached to the little birds.","correta":true,"explicacao":"He asked the birds to praise God, and they stayed very still, listening."},
    {"tipo":"multipla","enunciado":"Whom is Saint Francis the patron of?","opcoes":["Animals and nature","Banks","Cars"],"correta":0,"explicacao":"That is why many people bring their pets to be blessed on his feast day."},
    {"tipo":"vf","enunciado":"Francis said the moon is our sister.","correta":true,"explicacao":"In his canticle, he praises God for Sister Moon and the stars."},
    {"tipo":"multipla","enunciado":"What did Francis call water?","opcoes":["Sister Water","An ugly thing","An enemy"],"correta":0,"explicacao":"He said Sister Water is useful, humble and precious."},
    {"tipo":"vf","enunciado":"Francis thought only people were God's creatures.","correta":false,"explicacao":"Francis loved all creatures: people, animals, plants and stars."},
  ],
  'jose-1': [
    {"tipo":"multipla","enunciado":"What was Saint Joseph's job?","opcoes":["Carpenter","Fisherman","Shepherd"],"correta":0,"explicacao":"Joseph was a carpenter and made things out of wood with his hands."},
    {"tipo":"vf","enunciado":"The Bible does not tell us a single word Joseph said.","correta":true,"explicacao":"Joseph spoke little and did a lot: he obeyed God in silence."},
    {"tipo":"multipla","enunciado":"What does the Bible call Joseph?","opcoes":["A just man","An angry man","A rich man"],"correta":0,"explicacao":"Just means good and faithful to God."},
    {"tipo":"vf","enunciado":"Joseph was from King David's family.","correta":true,"explicacao":"That is why Jesus is also called the son of David."},
    {"tipo":"multipla","enunciado":"Who told Joseph, in a dream, that Mary's baby came from God?","opcoes":["An angel","A soldier","A neighbor"],"correta":0,"explicacao":"God sent an angel to calm Joseph's heart."},
    {"tipo":"vf","enunciado":"Joseph welcomed Mary into his home and cared for her with love.","correta":true,"explicacao":"He obeyed the angel and stayed by Mary's side."},
    {"tipo":"multipla","enunciado":"What name did the angel say to give the baby?","opcoes":["Jesus","Peter","David"],"correta":0,"explicacao":"Jesus means God saves."},
    {"tipo":"vf","enunciado":"Joseph got scared and left Mary.","correta":false,"explicacao":"Joseph was faithful: he trusted God and took care of Mary and Jesus."},
    {"tipo":"multipla","enunciado":"In which town was Jesus born?","opcoes":["Bethlehem","Rome","Lisbon"],"correta":0,"explicacao":"Jesus was born in Bethlehem, and Joseph was there taking care of everything."},
    {"tipo":"vf","enunciado":"Joseph cared for Jesus from the time he was a baby.","correta":true,"explicacao":"Joseph was the father God chose to care for Jesus here on earth."},
  ],
  'jose-2': [
    {"tipo":"multipla","enunciado":"How did Joseph know he had to flee with his family?","opcoes":["An angel told him in a dream","He got a letter","He heard it at the market"],"correta":0,"explicacao":"Joseph always listened to God's voice and obeyed right away."},
    {"tipo":"vf","enunciado":"The Holy Family fled to protect baby Jesus.","correta":true,"explicacao":"King Herod wanted to harm the child, and Joseph protected his family."},
    {"tipo":"multipla","enunciado":"To which country did the Holy Family flee?","opcoes":["Egypt","Japan","Brazil"],"correta":0,"explicacao":"They made a very long trip all the way to Egypt."},
    {"tipo":"vf","enunciado":"Joseph left with Mary and Jesus during the night.","correta":true,"explicacao":"He got up at night and left at once, to protect his family."},
    {"tipo":"multipla","enunciado":"Where did the Holy Family go to live afterwards?","opcoes":["Nazareth","Paris","Rome"],"correta":0,"explicacao":"In Nazareth, Jesus grew up with Mary and Joseph."},
    {"tipo":"ordenar","enunciado":"Put together the journey of the Holy Family:","blocos":["Jesus is born in Bethlehem","They flee to Egypt","They go back to Nazareth"],"explicacao":"Joseph guided his family at every step, with courage."},
    {"tipo":"vf","enunciado":"Once, Joseph and Mary looked for Jesus for three days.","correta":true,"explicacao":"They found him in the Temple, talking with the teachers."},
    {"tipo":"multipla","enunciado":"Where did they find Jesus after three days?","opcoes":["In the Temple","At the beach","At the market"],"correta":0,"explicacao":"Jesus was in God's house, listening and asking questions."},
    {"tipo":"vf","enunciado":"Joseph was a lazy father.","correta":false,"explicacao":"Joseph was hardworking and caring: he protected his family with love."},
    {"tipo":"multipla","enunciado":"Who took baby Jesus to the Temple together with Mary?","opcoes":["Joseph","Peter","John"],"correta":0,"explicacao":"Joseph and Mary presented Jesus to God in the Temple."},
  ],
  'jose-3': [
    {"tipo":"multipla","enunciado":"Whom does Saint Joseph protect?","opcoes":["The whole Church","Only kings","Only soldiers"],"correta":0,"explicacao":"Just as he cared for Jesus, Joseph cares for the whole Church."},
    {"tipo":"vf","enunciado":"Saint Joseph is called the protector of the Holy Family.","correta":true,"explicacao":"He protected Jesus and Mary with all his love."},
    {"tipo":"multipla","enunciado":"What trade did Jesus learn from Joseph?","opcoes":["Carpenter","Painter","Cook"],"correta":0,"explicacao":"Jesus learned from Joseph how to work with wood."},
    {"tipo":"vf","enunciado":"There is a feast of Saint Joseph the Worker, which reminds us of the value of work.","correta":true,"explicacao":"Working with love is also a way of praying."},
    {"tipo":"multipla","enunciado":"According to tradition, who was with Joseph when he went to Heaven?","opcoes":["Jesus and Mary","The soldiers","No one"],"correta":0,"explicacao":"Tradition says Joseph died in the arms of Jesus and Mary."},
    {"tipo":"vf","enunciado":"Pope Francis wrote a letter about Saint Joseph.","correta":true,"explicacao":"The letter is called With a Father's Heart."},
    {"tipo":"multipla","enunciado":"What is Joseph's heart like, according to the Pope's letter?","opcoes":["A father's heart","A heart of stone","A heart of ice"],"correta":0,"explicacao":"Joseph loved Jesus with a father's heart, full of tenderness."},
    {"tipo":"vf","enunciado":"We can ask Saint Joseph to pray for us.","correta":true,"explicacao":"The saints are God's friends, and they pray for us."},
    {"tipo":"multipla","enunciado":"Complete: Jesus, Mary and...","opcoes":["Joseph","Peter","Paul"],"correta":0,"explicacao":"Jesus, Mary and Joseph are the Holy Family."},
    {"tipo":"vf","enunciado":"Joseph worked to support his family.","correta":true,"explicacao":"With his work, Joseph made sure there was bread at home every day."},
  ],
  'teresinha-1': [
    {"tipo":"multipla","enunciado":"In which country was Thérèse born?","opcoes":["France","Brazil","Japan"],"correta":0,"explicacao":"Thérèse was born in France and lived in a town called Lisieux."},
    {"tipo":"vf","enunciado":"Thérèse said she was a little flower of Jesus.","correta":true,"explicacao":"She saw herself as a simple little flower in God's garden."},
    {"tipo":"multipla","enunciado":"What were Thérèse's parents called?","opcoes":["Louis and Zélie","Peter and Anne","George and Rose"],"correta":0,"explicacao":"Louis and Zélie were also declared saints!"},
    {"tipo":"vf","enunciado":"Thérèse's parents are saints too.","correta":true,"explicacao":"It was a whole family that loved God."},
    {"tipo":"multipla","enunciado":"How many of Thérèse's sisters also became nuns?","opcoes":["Four","None","Twenty"],"correta":0,"explicacao":"Marie, Pauline, Léonie and Céline also gave their lives to God."},
    {"tipo":"vf","enunciado":"Thérèse asked the Pope to let her enter the convent early.","correta":true,"explicacao":"While still a young girl, she spoke to the Pope in person, full of courage."},
    {"tipo":"multipla","enunciado":"Why did Thérèse go to live in a convent?","opcoes":["To pray and love Jesus","To become famous","To earn money"],"correta":0,"explicacao":"In the convent, she prayed for all the people in the world."},
    {"tipo":"vf","enunciado":"Thérèse lived until she was very old.","correta":false,"explicacao":"Thérèse went to Heaven while still young, but she lived each day with great love."},
    {"tipo":"multipla","enunciado":"What name did Thérèse receive in the convent?","opcoes":["Thérèse of the Child Jesus","Thérèse of the Sea","Thérèse of the Mountain"],"correta":0,"explicacao":"She wanted to carry the Child Jesus in her name."},
    {"tipo":"vf","enunciado":"Thérèse's family prayed together.","correta":true,"explicacao":"At home, they prayed, went to Mass and helped the poor."},
  ],
  'teresinha-2': [
    {"tipo":"multipla","enunciado":"What is Thérèse's little way?","opcoes":["Doing small things with lots of love","Doing only huge things","Running very fast"],"correta":0,"explicacao":"Even making your bed can be a gift for Jesus, if you do it with love."},
    {"tipo":"vf","enunciado":"For Thérèse, a smile can be a gift for Jesus.","correta":true,"explicacao":"She smiled even at people who were hard to get along with."},
    {"tipo":"multipla","enunciado":"What did Thérèse compare her way to?","opcoes":["An elevator","A boat","A bicycle"],"correta":0,"explicacao":"Jesus' arms were the elevator that carried her up to Heaven."},
    {"tipo":"vf","enunciado":"Thérèse saw herself as a child in God's arms.","correta":true,"explicacao":"She trusted God the way a child trusts her father."},
    {"tipo":"multipla","enunciado":"Thérèse promised to send a shower of what from Heaven?","opcoes":["Roses","Stones","Leaves"],"correta":0,"explicacao":"The roses are the blessings she asks God to give us."},
    {"tipo":"ordenar","enunciado":"Put Thérèse's promise together:","blocos":["I want to spend","my Heaven","doing good on earth"],"explicacao":"She promised to keep helping people from Heaven."},
    {"tipo":"vf","enunciado":"Thérèse said only huge things please God.","correta":false,"explicacao":"For her, what matters is love, even in the tiniest things."},
    {"tipo":"multipla","enunciado":"What did Thérèse do when someone was hard on her?","opcoes":["She smiled and was kind","She fought back","She stopped talking to them"],"correta":0,"explicacao":"She answered kindly and prayed for that person."},
    {"tipo":"vf","enunciado":"Thérèse trusted God's love very much.","correta":true,"explicacao":"Trusting is like jumping into the arms of someone who loves us."},
    {"tipo":"multipla","enunciado":"What is at the heart of the little way?","opcoes":["Love and trust","Hurry","Fear"],"correta":0,"explicacao":"With love and trust, any child can become a saint."},
  ],
  'teresinha-3': [
    {"tipo":"vf","enunciado":"Thérèse is patroness of the missions, even though she never left her convent.","correta":true,"explicacao":"She helped missionaries by praying for them every day."},
    {"tipo":"multipla","enunciado":"Which book tells Thérèse's story, written by Thérèse herself?","opcoes":["Story of a Soul","The Little Prince","Don Quixote"],"correta":0,"explicacao":"She wrote down her memories, and the book was read all over the world."},
    {"tipo":"multipla","enunciado":"How did Thérèse help missionaries?","opcoes":["By praying and writing letters","By traveling on ships","By building churches"],"correta":0,"explicacao":"She called two missionary priests her brothers and wrote to them."},
    {"tipo":"vf","enunciado":"Thérèse is a Doctor of the Church, which means a great teacher of the faith.","correta":true,"explicacao":"With her little way, she teaches us to love God."},
    {"tipo":"multipla","enunciado":"Thérèse is patroness of the missions together with which saint?","opcoes":["Saint Francis Xavier","Saint George","Saint Peter"],"correta":0,"explicacao":"Francis Xavier traveled the world; Thérèse prayed without leaving her convent."},
    {"tipo":"vf","enunciado":"Thérèse became very sick, but she kept trusting Jesus.","correta":true,"explicacao":"Even while suffering, she smiled and prayed."},
    {"tipo":"multipla","enunciado":"What were Thérèse's last words?","opcoes":["My God, I love you","I'm hungry","See you tomorrow"],"correta":0,"explicacao":"She went to Heaven saying that she loved God."},
    {"tipo":"vf","enunciado":"Thérèse wanted to help people even after going to Heaven.","correta":true,"explicacao":"That is why so many people ask her to pray for us."},
    {"tipo":"multipla","enunciado":"Where did Thérèse live, praying for the whole world?","opcoes":["In the convent","On a ship","In a castle"],"correta":0,"explicacao":"In the convent of Lisieux she prayed for everyone."},
    {"tipo":"vf","enunciado":"Thérèse never prayed for other people.","correta":false,"explicacao":"Thérèse prayed for everyone, especially for those who were far from God."},
  ],
  'antonio-1': [
    {"tipo":"multipla","enunciado":"In which city was Saint Anthony born?","opcoes":["Lisbon","Madrid","London"],"correta":0,"explicacao":"He was born in Lisbon, in Portugal, and became famous in Padua, in Italy."},
    {"tipo":"vf","enunciado":"Saint Anthony became a Franciscan friar, like the friends of Saint Francis.","correta":true,"explicacao":"He wanted to live poor and joyful, the way Saint Francis did."},
    {"tipo":"multipla","enunciado":"What was Saint Anthony's first name?","opcoes":["Fernando","Charles","Matthew"],"correta":0,"explicacao":"His name was Fernando, and he was given the name Anthony when he became a friar."},
    {"tipo":"vf","enunciado":"Anthony wanted to be a missionary in Africa.","correta":true,"explicacao":"He dreamed of taking Jesus far away, all the way to Morocco."},
    {"tipo":"multipla","enunciado":"What carried Anthony's ship to Italy?","opcoes":["A storm","A whale","A pirate"],"correta":0,"explicacao":"The ship went off course, and God used this to bring him to Italy."},
    {"tipo":"vf","enunciado":"Anthony got sick on the trip to Africa.","correta":true,"explicacao":"Because he was sick, he had to go back, but the ship ended up in Italy."},
    {"tipo":"multipla","enunciado":"In which country did Anthony spend his last years?","opcoes":["Italy","Brazil","China"],"correta":0,"explicacao":"In Italy, he preached in many towns, until he reached Padua."},
    {"tipo":"vf","enunciado":"Anthony died when he was very old.","correta":false,"explicacao":"Anthony went to Heaven while still young, but he did a lot of good in a short time."},
    {"tipo":"multipla","enunciado":"Talking about Jesus to lots of people is called:","opcoes":["Preaching","Cooking","Swimming"],"correta":0,"explicacao":"Preaching is announcing the Word of God, and Anthony did it very well."},
    {"tipo":"vf","enunciado":"Anthony was declared a saint very soon after he died.","correta":true,"explicacao":"Everyone already knew he was a man of God."},
  ],
  'antonio-2': [
    {"tipo":"multipla","enunciado":"Why did Saint Anthony become famous?","opcoes":["He preached very well","He sang opera","He was a king"],"correta":0,"explicacao":"When he talked about Jesus, people were deeply moved."},
    {"tipo":"vf","enunciado":"Many people ask Saint Anthony for help finding lost things.","correta":true,"explicacao":"He is remembered as the saint of lost things."},
    {"tipo":"multipla","enunciado":"In an old story, to whom did Anthony preach?","opcoes":["To the fish","To the clouds","To the stones"],"correta":0,"explicacao":"The story tells that, when people wouldn't listen, the fish lifted their heads out of the water to hear him."},
    {"tipo":"vf","enunciado":"Saint Anthony knew the Bible very well.","correta":true,"explicacao":"He knew many passages of God's Word by heart."},
    {"tipo":"multipla","enunciado":"What special title did the Church give Anthony?","opcoes":["Doctor of the Church","Sea captain","King of Portugal"],"correta":0,"explicacao":"Doctor of the Church means a great teacher of the faith."},
    {"tipo":"vf","enunciado":"Saint Francis wrote a letter to Anthony.","correta":true,"explicacao":"Francis asked him to teach the friars, without forgetting to pray."},
    {"tipo":"ordenar","enunciado":"Put together the prayer to Saint Anthony:","blocos":["Saint Anthony,","help me find","what I have lost"],"explicacao":"It is a simple prayer that many people say with faith."},
    {"tipo":"multipla","enunciado":"What book did Anthony love most?","opcoes":["The Bible","A cookbook","A map"],"correta":0,"explicacao":"The Bible is the Word of God, and Anthony studied it with love."},
    {"tipo":"vf","enunciado":"Anthony gave up talking about God when people wouldn't listen.","correta":false,"explicacao":"He did not give up: he went to the sea and kept on talking about God."},
    {"tipo":"multipla","enunciado":"Why did the Pope call Anthony the Ark of the Testament?","opcoes":["He kept the Bible in his heart","He had a boat","He was a carpenter"],"correta":0,"explicacao":"Anthony kept God's Word in his memory and in his heart."},
  ],
  'antonio-3': [
    {"tipo":"vf","enunciado":"Saint Anthony's Bread is help for the hungry, linked to Saint Anthony.","correta":true,"explicacao":"Even today, in his name, many people share bread with those in need."},
    {"tipo":"multipla","enunciado":"Whom does Saint Anthony hold in his arms in pictures?","opcoes":["The Child Jesus","A puppy","A crown"],"correta":0,"explicacao":"Tradition says the Child Jesus appeared to him while he was praying."},
    {"tipo":"multipla","enunciado":"Which flower appears in pictures of Saint Anthony?","opcoes":["A lily","A sunflower","A daisy"],"correta":0,"explicacao":"The white lily reminds us of a pure heart."},
    {"tipo":"vf","enunciado":"In Brazil, many people ask Saint Anthony for a good marriage.","correta":true,"explicacao":"It is a joyful devotion of the people, celebrated at the June festivals."},
    {"tipo":"multipla","enunciado":"At which Brazilian festivals is Saint Anthony especially remembered?","opcoes":["The June festivals","Carnival","New Year's"],"correta":0,"explicacao":"At the June festivals we remember Saint Anthony, Saint John and Saint Peter."},
    {"tipo":"vf","enunciado":"Saint Anthony helped the poor.","correta":true,"explicacao":"He had a special love for those who suffered."},
    {"tipo":"multipla","enunciado":"Who are the three saints of the June festivals?","opcoes":["Anthony, John and Peter","George, Cosmas and Damian","Francis, Clare and Benedict"],"correta":0,"explicacao":"Anthony, John and Peter are remembered with great joy in June."},
    {"tipo":"vf","enunciado":"Saint Anthony was a vain friar who liked riches.","correta":false,"explicacao":"He lived simply and shared everything with the poor."},
    {"tipo":"multipla","enunciado":"Why do so many people love Saint Anthony?","opcoes":["Because he helps those in need","Because he was very rich","Because he was a king"],"correta":0,"explicacao":"He is a friend who prays for us, especially for the poor."},
    {"tipo":"vf","enunciado":"Many churches in Brazil are named after Saint Anthony.","correta":true,"explicacao":"He is one of the most beloved saints of the Brazilian people."},
  ],
  'pio-1': [
    {"tipo":"multipla","enunciado":"What clothes did Padre Pio wear?","opcoes":["A brown friar's habit","Armor","A crown"],"correta":0,"explicacao":"He was a Capuchin friar and wore the brown habit with a hood."},
    {"tipo":"vf","enunciado":"Padre Pio had wounds on his hands like the wounds of Jesus.","correta":true,"explicacao":"He suffered with those wounds for many years, with patience and love."},
    {"tipo":"multipla","enunciado":"What was Padre Pio's name when he was a child?","opcoes":["Francis","Paul","James"],"correta":0,"explicacao":"His name was Francesco, which is Francis in Italian."},
    {"tipo":"vf","enunciado":"Padre Pio was born in a little town in Italy.","correta":true,"explicacao":"He was born in Pietrelcina, into a simple family of farmers."},
    {"tipo":"multipla","enunciado":"In which country did Padre Pio live?","opcoes":["Italy","Brazil","United States"],"correta":0,"explicacao":"He spent his whole life in Italy."},
    {"tipo":"vf","enunciado":"Padre Pio lived in the same friary for many years.","correta":true,"explicacao":"He stayed many, many years in the friary of San Giovanni Rotondo."},
    {"tipo":"multipla","enunciado":"What did Padre Pio love to do most?","opcoes":["Pray","Travel","Play"],"correta":0,"explicacao":"He prayed the rosary many times a day."},
    {"tipo":"vf","enunciado":"Padre Pio was never a priest.","correta":false,"explicacao":"He was a priest, and he celebrated Mass with great love."},
    {"tipo":"multipla","enunciado":"What was Padre Pio like?","opcoes":["Humble and simple","Rich and vain","Angry and selfish"],"correta":0,"explicacao":"Even though he was famous, he lived like a simple friar."},
    {"tipo":"vf","enunciado":"Padre Pio is a saint today.","correta":true,"explicacao":"The Church declared that he is in Heaven with God."},
  ],
  'pio-2': [
    {"tipo":"multipla","enunciado":"Where do we ask God's forgiveness with the help of the priest?","opcoes":["In Confession","At lunch","On a trip"],"correta":0,"explicacao":"Padre Pio spent hours in Confession, where Jesus forgives our sins."},
    {"tipo":"ordenar","enunciado":"Put together Padre Pio's advice:","blocos":["Pray,","hope","and don't worry"],"explicacao":"He taught people to trust God in everything."},
    {"tipo":"multipla","enunciado":"What did Padre Pio call the rosary?","opcoes":["The weapon","The toy","The necklace"],"correta":0,"explicacao":"For him, the rosary was a weapon of prayer that defeats evil."},
    {"tipo":"vf","enunciado":"Many people waited in line to go to confession with Padre Pio.","correta":true,"explicacao":"People came from many countries to find God's forgiveness."},
    {"tipo":"multipla","enunciado":"Why did Padre Pio ask people to get together?","opcoes":["To pray together","To fight","To go shopping"],"correta":0,"explicacao":"Padre Pio's Prayer Groups still exist today."},
    {"tipo":"vf","enunciado":"Padre Pio said prayer is very important.","correta":true,"explicacao":"For him, praying is talking with God and opening your heart."},
    {"tipo":"multipla","enunciado":"What does God do when we say sorry with all our heart?","opcoes":["He forgives","He stays angry forever","He doesn't listen"],"correta":0,"explicacao":"God is a Father, and he forgives those who are sorry."},
    {"tipo":"vf","enunciado":"Padre Pio celebrated Mass with great tenderness.","correta":true,"explicacao":"Many people were moved just by seeing his love at Mass."},
    {"tipo":"vf","enunciado":"Padre Pio thought praying was a waste of time.","correta":false,"explicacao":"He said that prayer is the best weapon we have."},
    {"tipo":"multipla","enunciado":"Whom did Padre Pio welcome in the confessional?","opcoes":["Rich and poor, all the same","Only kings","Only artists"],"correta":0,"explicacao":"He welcomed everyone with the same kindness."},
  ],
  'pio-3': [
    {"tipo":"vf","enunciado":"Padre Pio built a hospital to care for the sick.","correta":true,"explicacao":"The hospital's name means House for the Relief of Suffering."},
    {"tipo":"multipla","enunciado":"What did Padre Pio build for the sick?","opcoes":["A hospital","A park","A stadium"],"correta":0,"explicacao":"He wanted the sick to be treated with love and good medicine."},
    {"tipo":"multipla","enunciado":"Which pope declared Padre Pio a saint?","opcoes":["John Paul II","Benedict XVI","Francis"],"correta":0,"explicacao":"Pope John Paul II declared Padre Pio a saint in front of a huge crowd."},
    {"tipo":"vf","enunciado":"John Paul II met Padre Pio when he was still a young priest.","correta":true,"explicacao":"Years later, he himself declared Padre Pio a saint."},
    {"tipo":"multipla","enunciado":"Where is Padre Pio's hospital?","opcoes":["Near his friary","On an island","In another country"],"correta":0,"explicacao":"The hospital is next to the friary where he lived, in Italy."},
    {"tipo":"vf","enunciado":"Padre Pio's hospital still cares for many sick people today.","correta":true,"explicacao":"It is a gift of love that keeps on helping people."},
    {"tipo":"multipla","enunciado":"How did Padre Pio want the sick to be treated?","opcoes":["With love and care","In a hurry","With scorn"],"correta":0,"explicacao":"For him, caring for a sick person is caring for Jesus himself."},
    {"tipo":"vf","enunciado":"Many pilgrims visit the place where Padre Pio lived.","correta":true,"explicacao":"People from all over the world go there to pray."},
    {"tipo":"multipla","enunciado":"A pilgrim is someone who:","opcoes":["Travels to pray at a holy place","Sells fish","Paints pictures"],"correta":0,"explicacao":"Pilgrims journey to meet God."},
    {"tipo":"vf","enunciado":"Padre Pio only cared about healthy people.","correta":false,"explicacao":"He had enormous love for the sick and for those who suffered."},
  ],
  'maria-1': [
    {"tipo":"multipla","enunciado":"Which angel brought God's message to Mary?","opcoes":["Gabriel","Michael","Raphael"],"correta":0,"explicacao":"The angel Gabriel told Mary that she would be the mother of Jesus."},
    {"tipo":"vf","enunciado":"Mary said yes to God.","correta":true,"explicacao":"She answered: behold the handmaid of the Lord; be it done unto me according to your word."},
    {"tipo":"multipla","enunciado":"In which town did Mary live when the angel came?","opcoes":["Nazareth","Bethlehem","Rome"],"correta":0,"explicacao":"Nazareth was a small and simple town."},
    {"tipo":"vf","enunciado":"The angel said to Mary: Hail, full of grace.","correta":true,"explicacao":"The Hail Mary prayer begins with these words."},
    {"tipo":"multipla","enunciado":"What name did the angel say the baby would have?","opcoes":["Jesus","Moses","David"],"correta":0,"explicacao":"Jesus is the Son of God who came to live among us."},
    {"tipo":"vf","enunciado":"Mary got scared and said no to God.","correta":false,"explicacao":"Mary trusted God and said yes with all her heart."},
    {"tipo":"multipla","enunciado":"Which relative of Mary was also expecting a baby?","opcoes":["Elizabeth","Martha","Magdalene"],"correta":0,"explicacao":"Elizabeth was Mary's cousin, and she was expecting John the Baptist."},
    {"tipo":"vf","enunciado":"The angel said that nothing is impossible for God.","correta":true,"explicacao":"God does wonderful things in the lives of those who trust him."},
    {"tipo":"multipla","enunciado":"Which prayer begins with the angel's words?","opcoes":["The Hail Mary","The Our Father","The Glory Be"],"correta":0,"explicacao":"When we pray the Hail Mary, we repeat the angel's greeting."},
    {"tipo":"vf","enunciado":"Mary is the mother of Jesus.","correta":true,"explicacao":"And Jesus gave us Mary to be our mother too."},
  ],
  'maria-2': [
    {"tipo":"multipla","enunciado":"Whom did Mary go to visit right after the angel's visit?","opcoes":["Her cousin Elizabeth","King Herod","A shepherd"],"correta":0,"explicacao":"Mary hurried to help Elizabeth, who was expecting a baby."},
    {"tipo":"vf","enunciado":"When Mary arrived, Elizabeth's baby jumped for joy inside his mother's tummy.","correta":true,"explicacao":"John the Baptist was already happy that Jesus had come."},
    {"tipo":"multipla","enunciado":"Which baby was Elizabeth expecting?","opcoes":["John the Baptist","Peter","Paul"],"correta":0,"explicacao":"John the Baptist would prepare the way for Jesus."},
    {"tipo":"vf","enunciado":"Elizabeth said that Mary is blessed among women.","correta":true,"explicacao":"We repeat these words in the Hail Mary."},
    {"tipo":"multipla","enunciado":"Mary sang a prayer of joy. How does it begin?","opcoes":["My soul magnifies the Lord","Our Father, who art in heaven","Glory to God in the highest"],"correta":0,"explicacao":"This song of Mary is called the Magnificat."},
    {"tipo":"ordenar","enunciado":"Put together the beginning of Mary's song:","blocos":["My soul","magnifies","the Lord"],"explicacao":"Mary thanks God for the beautiful things he has done."},
    {"tipo":"multipla","enunciado":"What did Mary do at Elizabeth's house?","opcoes":["She helped her cousin","She went sightseeing","She went to sleep"],"correta":0,"explicacao":"Mary stayed about three months, helping Elizabeth with great love."},
    {"tipo":"vf","enunciado":"In her song, Mary says that God looks kindly on the humble.","correta":true,"explicacao":"God loves the little ones and those who are simple of heart."},
    {"tipo":"vf","enunciado":"Mary became proud and thought she was better than everyone.","correta":false,"explicacao":"Mary was humble and gave all the glory to God."},
    {"tipo":"multipla","enunciado":"What does Mary teach us to be?","opcoes":["Humble","Proud","Selfish"],"correta":0,"explicacao":"Whoever is humble lets God do wonderful things in their life."},
  ],
  'maria-3': [
    {"tipo":"multipla","enunciado":"On the cross, whose mother did Jesus give Mary to be?","opcoes":["The disciple John's","A soldier's","No one's"],"correta":0,"explicacao":"Jesus said to John: behold your mother, and so Mary is the mother of us all."},
    {"tipo":"vf","enunciado":"When we pray the rosary, we remember the life of Jesus and Mary.","correta":true,"explicacao":"Each mystery of the rosary tells a little piece of that story."},
    {"tipo":"multipla","enunciado":"Who is the patroness of Brazil?","opcoes":["Our Lady Aparecida","Our Lady of Lourdes","Our Lady of Guadalupe"],"correta":0,"explicacao":"The image of Aparecida was found by fishermen in a river."},
    {"tipo":"vf","enunciado":"The image of Our Lady Aparecida was found by fishermen.","correta":true,"explicacao":"They cast their net into the river and found the image."},
    {"tipo":"multipla","enunciado":"At Fátima, to how many children did Our Lady appear?","opcoes":["Three","One","Ten"],"correta":0,"explicacao":"Lúcia, Francisco and Jacinta were little shepherds."},
    {"tipo":"vf","enunciado":"The shepherd children of Fátima were very rich grown-ups.","correta":false,"explicacao":"They were simple children who took care of sheep."},
    {"tipo":"multipla","enunciado":"At Lourdes, to which girl did Our Lady appear?","opcoes":["Bernadette","Thérèse","Clare"],"correta":0,"explicacao":"Bernadette was a poor and very honest girl."},
    {"tipo":"vf","enunciado":"Mary was taken up to Heaven body and soul.","correta":true,"explicacao":"This feast is called the Assumption of Our Lady."},
    {"tipo":"multipla","enunciado":"What did Mary tell the servants at the wedding feast in Cana?","opcoes":["Do whatever he tells you","Go away","Bring more bread"],"correta":0,"explicacao":"It is Mary's best advice: do what Jesus asks."},
    {"tipo":"vf","enunciado":"Mary is called Mother of the Church.","correta":true,"explicacao":"She takes care of all God's children, as a mother takes care of her family."},
  ],
  'bento-1': [
    {"tipo":"multipla","enunciado":"What was Saint Benedict's motto?","opcoes":["Pray and work","Rest and play","Study and travel"],"correta":0,"explicacao":"In Latin it is Ora et labora: pray and work."},
    {"tipo":"vf","enunciado":"Saint Benedict is the patron of Europe.","correta":true,"explicacao":"His monks helped bring the faith all across Europe."},
    {"tipo":"multipla","enunciado":"In which country was Saint Benedict born?","opcoes":["Italy","Brazil","Japan"],"correta":0,"explicacao":"Benedict was born in an Italian town called Nursia."},
    {"tipo":"vf","enunciado":"Tradition says Saint Benedict had a twin sister, Saint Scholastica.","correta":true,"explicacao":"Both of them loved God very much."},
    {"tipo":"multipla","enunciado":"Where did Benedict go to pray alone when he was young?","opcoes":["To a cave","To a ship","To a castle"],"correta":0,"explicacao":"He lived in a cave, praying in silence, near Subiaco."},
    {"tipo":"vf","enunciado":"Benedict left the big city to be closer to God.","correta":true,"explicacao":"He left Rome to pray in peace."},
    {"tipo":"multipla","enunciado":"What do we call someone who lives in a monastery, praying and working?","opcoes":["A monk","A sailor","A firefighter"],"correta":0,"explicacao":"Monks pray together several times a day."},
    {"tipo":"vf","enunciado":"Saint Benedict lived not long ago, in the time of cell phones.","correta":false,"explicacao":"Saint Benedict lived a long, long time ago, long before our grandparents."},
    {"tipo":"multipla","enunciado":"What big house did Benedict build for the monks?","opcoes":["A monastery","A palace","A castle"],"correta":0,"explicacao":"His most famous monastery is on Monte Cassino."},
    {"tipo":"vf","enunciado":"Benedict taught that working is also a way to praise God.","correta":true,"explicacao":"Whoever works with love is serving God."},
  ],
  'bento-2': [
    {"tipo":"multipla","enunciado":"Saint Benedict wrote a book for the monks. What is it called?","opcoes":["The Rule","The Map","The Recipe"],"correta":0,"explicacao":"The Rule teaches how to live together, praying and working."},
    {"tipo":"vf","enunciado":"Many monasteries still follow the Rule of Saint Benedict today.","correta":true,"explicacao":"For many, many years it has guided monks and nuns."},
    {"tipo":"multipla","enunciado":"What is the first word of the Rule?","opcoes":["Listen","Run","Sleep"],"correta":0,"explicacao":"Benedict begins by asking: listen, my son, with the ear of your heart."},
    {"tipo":"vf","enunciado":"According to the Rule, every visitor should be welcomed as if he were Jesus.","correta":true,"explicacao":"Welcoming people well is a way of loving Jesus."},
    {"tipo":"multipla","enunciado":"What is the monk who takes care of the whole monastery called?","opcoes":["The abbot","The captain","The mayor"],"correta":0,"explicacao":"Abbot means father: he takes care of the monks like a father."},
    {"tipo":"ordenar","enunciado":"Put together Saint Benedict's words:","blocos":["That in all things","God may be","glorified"],"explicacao":"Everything we do can be for the glory of God."},
    {"tipo":"vf","enunciado":"For Saint Benedict, prayer comes before everything.","correta":true,"explicacao":"He taught: let nothing be put before prayer."},
    {"tipo":"multipla","enunciado":"What do the monks do together several times a day?","opcoes":["They pray","They dance","They travel"],"correta":0,"explicacao":"They sing psalms and praise God at different times of the day."},
    {"tipo":"vf","enunciado":"The Rule teaches the monks to fight with one another.","correta":false,"explicacao":"The Rule teaches peace, obedience and love among brothers."},
    {"tipo":"multipla","enunciado":"Where do the monks live?","opcoes":["In a monastery","In a circus","On a boat"],"correta":0,"explicacao":"The monastery is the monks' home, where they pray and work."},
  ],
  'bento-3': [
    {"tipo":"vf","enunciado":"The Saint Benedict medal has a prayer to keep evil away.","correta":true,"explicacao":"Its little letters are requests to God for protection."},
    {"tipo":"multipla","enunciado":"Where was Saint Benedict's most famous monastery?","opcoes":["Monte Cassino","Rio de Janeiro","Paris"],"correta":0,"explicacao":"The monastery of Monte Cassino is on top of a mountain, in Italy."},
    {"tipo":"multipla","enunciado":"What appears on the Saint Benedict medal?","opcoes":["A cross","An anchor","A fish"],"correta":0,"explicacao":"The cross reminds us that Jesus defeated evil through love."},
    {"tipo":"vf","enunciado":"In an old story, a raven took away from Benedict a loaf of bread with poison in it.","correta":true,"explicacao":"That is why the raven appears in pictures of Saint Benedict."},
    {"tipo":"multipla","enunciado":"Which bird appears in pictures of Saint Benedict?","opcoes":["A raven","A parrot","A chicken"],"correta":0,"explicacao":"The raven reminds us how God protected Benedict."},
    {"tipo":"vf","enunciado":"The medal says: may the holy cross be my light.","correta":true,"explicacao":"In Latin: Crux sacra sit mihi lux."},
    {"tipo":"multipla","enunciado":"Who wrote the story of Saint Benedict?","opcoes":["Pope Saint Gregory","A king","A soldier"],"correta":0,"explicacao":"Pope Gregory told Benedict's life in a book."},
    {"tipo":"vf","enunciado":"The Saint Benedict medal is a good-luck charm.","correta":false,"explicacao":"The medal is not a charm: it reminds us to pray and trust God."},
    {"tipo":"multipla","enunciado":"What is the Saint Benedict medal for?","opcoes":["To remember God and ask for protection","To win games","To get rich"],"correta":0,"explicacao":"It helps us remember that God protects us."},
    {"tipo":"vf","enunciado":"When we make the sign of the cross, we remember that Jesus protects us.","correta":true,"explicacao":"Benedict made the sign of the cross with great faith."},
  ],
  'clara-1': [
    {"tipo":"multipla","enunciado":"Who helped Clare follow Jesus?","opcoes":["Saint Francis","Saint Benedict","Saint Anthony"],"correta":0,"explicacao":"Francis was from the same town and taught Clare to live poor, like Jesus."},
    {"tipo":"vf","enunciado":"Clare started a family of sisters who pray, the Poor Clares.","correta":true,"explicacao":"The Poor Clare sisters still live all over the world."},
    {"tipo":"multipla","enunciado":"What kind of family did Clare come from?","opcoes":["Rich","Poor","A family of fishermen"],"correta":0,"explicacao":"Clare left a comfortable home to follow Jesus."},
    {"tipo":"vf","enunciado":"Clare left home at night to follow Jesus.","correta":true,"explicacao":"It was a brave decision, full of love for God."},
    {"tipo":"multipla","enunciado":"In which town was Clare born?","opcoes":["Assisi","Lisbon","Paris"],"correta":0,"explicacao":"Clare was born in Assisi, the same town as Saint Francis."},
    {"tipo":"vf","enunciado":"Francis cut Clare's hair to show that she belonged completely to God.","correta":true,"explicacao":"It was the way to show that Clare had chosen Jesus."},
    {"tipo":"multipla","enunciado":"Which of Clare's sisters also went to follow Jesus with her?","opcoes":["Agnes","Rita","Monica"],"correta":0,"explicacao":"Agnes followed Clare a few days later."},
    {"tipo":"vf","enunciado":"Clare wanted to be rich and famous.","correta":false,"explicacao":"Clare chose to be poor so that Jesus would be her treasure."},
    {"tipo":"multipla","enunciado":"Where did Clare live all her life with her sisters?","opcoes":["At San Damiano","In a castle","On a ship"],"correta":0,"explicacao":"San Damiano was the little church Francis had repaired."},
    {"tipo":"vf","enunciado":"Clare and Francis were friends in the faith.","correta":true,"explicacao":"They helped each other love Jesus more."},
  ],
  'clara-2': [
    {"tipo":"multipla","enunciado":"What did Clare hold in her hands when soldiers came to the convent?","opcoes":["The Host, which is Jesus","A sword","A shield"],"correta":0,"explicacao":"Clare trusted in Jesus present in the Host."},
    {"tipo":"vf","enunciado":"Even though she was sick, Clare faced the soldiers with faith.","correta":true,"explicacao":"She did not use weapons: she used prayer."},
    {"tipo":"multipla","enunciado":"What did the soldiers do after Clare prayed?","opcoes":["They went away","They had a party","They moved in"],"correta":0,"explicacao":"The story tells that they ran away, and the sisters were kept safe."},
    {"tipo":"vf","enunciado":"Clare wrote letters full of advice to a princess named Agnes.","correta":true,"explicacao":"Agnes of Prague also left everything to follow the poor Jesus."},
    {"tipo":"multipla","enunciado":"What was Clare's advice in her letters?","opcoes":["To look at Jesus with love","To buy lots of things","To be angry all the time"],"correta":0,"explicacao":"Clare taught people to look at Jesus with their heart."},
    {"tipo":"ordenar","enunciado":"Put together Clare's story:","blocos":["The soldiers arrive","Clare prays with Jesus","The soldiers run away"],"explicacao":"Clare's prayer protected the sisters."},
    {"tipo":"vf","enunciado":"Clare wrote a rule so that the sisters could live poor and praying.","correta":true,"explicacao":"The Pope approved the rule shortly before Clare went to Heaven."},
    {"tipo":"multipla","enunciado":"What did Clare ask the Pope for all her life?","opcoes":["To be allowed to live poor","Lots of money","A palace"],"correta":0,"explicacao":"Clare wanted to live only with God, without keeping riches."},
    {"tipo":"vf","enunciado":"Clare liked to keep jewels and money.","correta":false,"explicacao":"Clare's treasure was Jesus, not riches."},
    {"tipo":"multipla","enunciado":"Clare loved Jesus in the Eucharist. Where do we receive the Eucharist?","opcoes":["At Mass","At the market","At school"],"correta":0,"explicacao":"At Mass, Jesus gives himself to us in Holy Communion."},
  ],
  'clara-3': [
    {"tipo":"vf","enunciado":"Saint Clare is the patroness of television.","correta":true,"explicacao":"When she was sick, she saw the Mass from far away, as if on a screen."},
    {"tipo":"multipla","enunciado":"What was Clare's greatest treasure?","opcoes":["Jesus","Gold","Land"],"correta":0,"explicacao":"For Clare, whoever has Jesus has everything."},
    {"tipo":"multipla","enunciado":"Why is Clare the patroness of television?","opcoes":["She saw Mass from far away, sick in bed","She liked movies","She invented television"],"correta":0,"explicacao":"God let her follow the Mass without getting out of bed."},
    {"tipo":"vf","enunciado":"The name Clare reminds us of light and brightness.","correta":true,"explicacao":"Clare's life lit up many people."},
    {"tipo":"multipla","enunciado":"What are the sisters who follow Saint Clare called?","opcoes":["Poor Clares","Carmelites","Benedictines"],"correta":0,"explicacao":"The name Poor Clares comes from Clare's name."},
    {"tipo":"vf","enunciado":"Clare was declared a saint very soon after she died.","correta":true,"explicacao":"People already knew she was a saint."},
    {"tipo":"multipla","enunciado":"How did Clare live?","opcoes":["Simply and joyfully","With luxury and vanity","With anger"],"correta":0,"explicacao":"She was poor, but very joyful."},
    {"tipo":"vf","enunciado":"Clare was sad about leaving her riches.","correta":false,"explicacao":"Clare was happy because she had Jesus in her heart."},
    {"tipo":"multipla","enunciado":"What did Clare do for many hours a day?","opcoes":["She prayed","She slept","She went for walks"],"correta":0,"explicacao":"Clare prayed a lot and took care of her sisters lovingly."},
    {"tipo":"vf","enunciado":"Clare served her sisters and cared for those who were sick.","correta":true,"explicacao":"Even though she was the mother abbess, she washed the sisters' feet and served everyone."},
  ],
  'jpii-1': [
    {"tipo":"multipla","enunciado":"Which country did Pope John Paul II come from?","opcoes":["Poland","Italy","Brazil"],"correta":0,"explicacao":"He was born in Poland, a country in Europe."},
    {"tipo":"vf","enunciado":"John Paul II's name was Karol.","correta":true,"explicacao":"Karol is the Polish way of saying Charles."},
    {"tipo":"multipla","enunciado":"What famous advice did John Paul II give everyone?","opcoes":["Be not afraid!","Be quiet!","Go to sleep!"],"correta":0,"explicacao":"He wanted no one to be afraid of opening their heart to Jesus."},
    {"tipo":"vf","enunciado":"When he was young, Karol worked breaking stones in a quarry.","correta":true,"explicacao":"He knew how hard everyday work can be."},
    {"tipo":"multipla","enunciado":"What did Karol like to do when he was young?","opcoes":["Theater and sports","Fighting","Sitting still"],"correta":0,"explicacao":"He did theater and loved skiing in the mountains."},
    {"tipo":"vf","enunciado":"John Paul II was pope for many years.","correta":true,"explicacao":"He guided the Church for a long time, visiting the whole world."},
    {"tipo":"multipla","enunciado":"Whose shepherd is the Pope?","opcoes":["The whole Church's","Just one country's","Only the priests'"],"correta":0,"explicacao":"The Pope takes care of all the Catholics in the world."},
    {"tipo":"vf","enunciado":"John Paul II never left Rome.","correta":false,"explicacao":"He traveled the whole world, bringing Jesus to many peoples."},
    {"tipo":"multipla","enunciado":"How did John Paul II like to be close to people?","opcoes":["By traveling and visiting","By staying locked at home","By hiding"],"correta":0,"explicacao":"He visited many, many countries."},
    {"tipo":"vf","enunciado":"John Paul II is a saint today.","correta":true,"explicacao":"The Church declared that he is in Heaven, with God."},
  ],
  'jpii-2': [
    {"tipo":"vf","enunciado":"John Paul II created World Youth Day.","correta":true,"explicacao":"It is a big gathering of young people from all over the world with the Pope."},
    {"tipo":"multipla","enunciado":"Which short prayer appears on the image of the Merciful Jesus?","opcoes":["Jesus, I trust in you","Good morning, Jesus","See you later, Jesus"],"correta":0,"explicacao":"It is a simple way of saying that we trust in Jesus' love."},
    {"tipo":"multipla","enunciado":"Which friend of the Merciful Jesus did John Paul II declare a saint?","opcoes":["Saint Faustina","Saint Rita","Saint Clare"],"correta":0,"explicacao":"Faustina was a nun from Poland, like him."},
    {"tipo":"vf","enunciado":"John Paul II visited Brazil.","correta":true,"explicacao":"He came to Brazil three times and was welcomed with great joy."},
    {"tipo":"multipla","enunciado":"What did John Paul II call young people?","opcoes":["Watchmen of the morning","Lazybones","Lost children"],"correta":0,"explicacao":"A watchman waits for the sun to rise, and the sun is Jesus."},
    {"tipo":"vf","enunciado":"John Paul II loved young people very much.","correta":true,"explicacao":"He said young people are the hope of the Church."},
    {"tipo":"ordenar","enunciado":"Put together the Pope's words to young people:","blocos":["You are","the hope","of the Church"],"explicacao":"He believed young people can change the world with Jesus."},
    {"tipo":"multipla","enunciado":"Whose friends did the Pope want young people to be?","opcoes":["Jesus'","Only famous people's","No one's"],"correta":0,"explicacao":"For him, Jesus is the best friend anyone can have."},
    {"tipo":"vf","enunciado":"John Paul II thought saints only existed long ago.","correta":false,"explicacao":"He showed that there are saints today too, and that you can be one as well."},
    {"tipo":"multipla","enunciado":"What is the gathering of young people with the Pope called?","opcoes":["World Youth Day","The World Cup","A June festival"],"correta":0,"explicacao":"At World Youth Day, young people from many countries pray and sing together."},
  ],
  'jpii-3': [
    {"tipo":"vf","enunciado":"John Paul II forgave the man who shot him.","correta":true,"explicacao":"He visited that man in prison and spoke with him like a brother."},
    {"tipo":"multipla","enunciado":"What new mysteries of the rosary did John Paul II create?","opcoes":["The luminous mysteries","The mysteries of the sea","The mysteries of the stars"],"correta":0,"explicacao":"They recall moments in Jesus' life, like his baptism and the wedding at Cana."},
    {"tipo":"multipla","enunciado":"What did the Pope do after he was attacked?","opcoes":["He forgave","He was full of hatred","He wanted revenge"],"correta":0,"explicacao":"Forgiving is Jesus' way of defeating evil."},
    {"tipo":"vf","enunciado":"John Paul II thanked Our Lady for saving him.","correta":true,"explicacao":"He said Our Lady protected him that day."},
    {"tipo":"multipla","enunciado":"Which title of Our Lady did the Pope thank for saving him?","opcoes":["Our Lady of Fátima","Our Lady of Mount Carmel","Our Lady of Light"],"correta":0,"explicacao":"The attack happened on the feast of Our Lady of Fátima."},
    {"tipo":"vf","enunciado":"When he was old and sick, John Paul II kept on working.","correta":true,"explicacao":"He showed that even illness can be offered to God with love."},
    {"tipo":"multipla","enunciado":"What did the people shout at John Paul II's farewell?","opcoes":["Saint now!","Go away!","Silence!"],"correta":0,"explicacao":"The people were sure he was a saint."},
    {"tipo":"vf","enunciado":"John Paul II was declared a saint on the same day as Pope John XXIII.","correta":true,"explicacao":"It was a celebration with two saintly popes."},
    {"tipo":"multipla","enunciado":"What was John Paul II's favorite prayer?","opcoes":["The rosary","The Christmas novena","The Stations of the Cross"],"correta":0,"explicacao":"He himself said the rosary was his favorite prayer."},
    {"tipo":"vf","enunciado":"Forgiving means keeping anger in your heart.","correta":false,"explicacao":"Forgiving means letting go of anger and letting God heal your heart."},
  ],
  'rita-1': [
    {"tipo":"multipla","enunciado":"Saint Rita is called the saint of...","opcoes":["Impossible causes","Travel","Sports"],"correta":0,"explicacao":"When something seems impossible, we ask Rita to pray for us."},
    {"tipo":"vf","enunciado":"Rita was married and had children before becoming a nun.","correta":true,"explicacao":"She was a saint as a wife, as a mother and as a nun."},
    {"tipo":"multipla","enunciado":"In which country was Rita born?","opcoes":["Italy","Spain","Japan"],"correta":0,"explicacao":"Rita was born in a village in Italy called Roccaporena."},
    {"tipo":"vf","enunciado":"Ever since she was a girl, Rita wanted to give her life to God.","correta":true,"explicacao":"But she obeyed her parents, got married and lived with great faith."},
    {"tipo":"multipla","enunciado":"What was Rita's husband like at first?","opcoes":["Angry and difficult","Very calm","Very shy"],"correta":0,"explicacao":"Rita was patient and prayed a lot for him."},
    {"tipo":"vf","enunciado":"With patience and prayer, Rita helped her husband become kinder.","correta":true,"explicacao":"Her love touched his heart."},
    {"tipo":"multipla","enunciado":"How many children did Rita have?","opcoes":["Two","Ten","None"],"correta":0,"explicacao":"She had two boys and taught them to love God."},
    {"tipo":"vf","enunciado":"Rita shouted and fought with everyone.","correta":false,"explicacao":"Rita was gentle and answered with patience and love."},
    {"tipo":"multipla","enunciado":"Which flower reminds us of Saint Rita?","opcoes":["The rose","The sunflower","The daisy"],"correta":0,"explicacao":"Because of a rose that bloomed in winter."},
    {"tipo":"vf","enunciado":"Rita prayed for her family.","correta":true,"explicacao":"Prayer was Rita's strength at home."},
  ],
  'rita-2': [
    {"tipo":"multipla","enunciado":"When Rita's husband died in a fight, what did she choose?","opcoes":["To forgive","To take revenge","To run away"],"correta":0,"explicacao":"Rita chose forgiveness, even though her heart was hurting."},
    {"tipo":"vf","enunciado":"Rita forgave the people who hurt her husband.","correta":true,"explicacao":"Rita's forgiveness brought peace to the families."},
    {"tipo":"multipla","enunciado":"What did Rita want the families to do?","opcoes":["Make peace","Keep fighting","Move to another town"],"correta":0,"explicacao":"She prayed and worked so that everyone would live in peace."},
    {"tipo":"vf","enunciado":"Rita helped the enemy families make peace.","correta":true,"explicacao":"Tradition says that after this she was able to enter the convent."},
    {"tipo":"multipla","enunciado":"Which virtue is Rita most remembered for?","opcoes":["Forgiveness","Hurry","Vanity"],"correta":0,"explicacao":"Forgiving is a gift that heals the heart."},
    {"tipo":"ordenar","enunciado":"Put together the prayer to Saint Rita:","blocos":["Saint Rita,","advocate","of impossible causes"],"explicacao":"An advocate is someone who speaks up for us: Rita prays for us before God."},
    {"tipo":"vf","enunciado":"Forgiving means that the wrong doesn't matter.","correta":false,"explicacao":"Forgiving doesn't mean saying the wrong is right: it means not keeping hatred in your heart."},
    {"tipo":"multipla","enunciado":"What helped Rita to forgive?","opcoes":["Prayer","Anger","Fear"],"correta":0,"explicacao":"By praying, Rita found the strength to forgive."},
    {"tipo":"vf","enunciado":"Whoever forgives has a lighter heart.","correta":true,"explicacao":"Forgiveness takes a very heavy weight off the heart."},
    {"tipo":"multipla","enunciado":"After the families made peace, where did Rita go to live?","opcoes":["In a convent","In a castle","On a ship"],"correta":0,"explicacao":"Rita became a nun in the convent of Cascia."},
  ],
  'rita-3': [
    {"tipo":"vf","enunciado":"Rita received a wound on her forehead, like one from a thorn of Jesus' crown.","correta":true,"explicacao":"She wanted to feel a little of Jesus' pain, out of love."},
    {"tipo":"multipla","enunciado":"In which town is Saint Rita's convent?","opcoes":["Cascia","Lisbon","Paris"],"correta":0,"explicacao":"That is why she is called Rita of Cascia."},
    {"tipo":"multipla","enunciado":"What bloomed in winter when Rita asked?","opcoes":["A rose","A sunflower","A daisy"],"correta":0,"explicacao":"Tradition says a rose was found in the garden, in the middle of winter."},
    {"tipo":"vf","enunciado":"Tradition says Rita asked for figs in winter, and they appeared.","correta":true,"explicacao":"God did this kindness for his sick friend."},
    {"tipo":"multipla","enunciado":"In front of whom was Rita praying when she received the thorn?","opcoes":["Jesus on the cross","A king","A mirror"],"correta":0,"explicacao":"She was praying while looking at Jesus crucified."},
    {"tipo":"vf","enunciado":"Many pilgrims visit Saint Rita in Cascia.","correta":true,"explicacao":"Many people go there to ask her to pray for us."},
    {"tipo":"multipla","enunciado":"Why is the rose the symbol of Saint Rita?","opcoes":["It bloomed in winter when she asked","She sold flowers","She only planted roses"],"correta":0,"explicacao":"The rose reminds us that nothing is impossible for God."},
    {"tipo":"vf","enunciado":"Rita complained about her wound all the time.","correta":false,"explicacao":"Rita offered her pain to Jesus, with patience."},
    {"tipo":"multipla","enunciado":"When we ask God for something difficult, whom can we ask to pray with us?","opcoes":["Saint Rita","A magician","Luck"],"correta":0,"explicacao":"Rita prays for us with God."},
    {"tipo":"vf","enunciado":"Saint Rita lived a long time ago, but she is still much loved today.","correta":true,"explicacao":"In many churches there is a statue of Saint Rita with roses."},
  ],
  'judas-1': [
    {"tipo":"multipla","enunciado":"How many apostles did Jesus choose?","opcoes":["Twelve","Three","A hundred"],"correta":0,"explicacao":"Jude Thaddeus was one of Jesus' twelve closest friends."},
    {"tipo":"vf","enunciado":"Saint Jude Thaddeus is the same Judas who betrayed Jesus.","correta":false,"explicacao":"They are two different people: Jude Thaddeus was faithful to Jesus to the end."},
    {"tipo":"multipla","enunciado":"With which apostle is Saint Jude Thaddeus celebrated on the same day?","opcoes":["Saint Simon","Saint George","Saint John"],"correta":0,"explicacao":"The two apostles are remembered together."},
    {"tipo":"vf","enunciado":"At the Last Supper, Jude Thaddeus asked Jesus a question.","correta":true,"explicacao":"He wanted to understand how Jesus would show himself to his friends."},
    {"tipo":"multipla","enunciado":"What did Jesus answer Jude Thaddeus?","opcoes":["That he would come and live in those who love him","That he was going on a trip","That he was tired"],"correta":0,"explicacao":"Jesus and the Father make their home in the heart of whoever loves Jesus."},
    {"tipo":"vf","enunciado":"The name Thaddeus helps us not to mix up the two Judases.","correta":true,"explicacao":"That way we know we are talking about the faithful apostle."},
    {"tipo":"multipla","enunciado":"What is an apostle?","opcoes":["A friend sent by Jesus","A Roman soldier","A king"],"correta":0,"explicacao":"Apostle means someone who is sent: he brings Jesus to others."},
    {"tipo":"vf","enunciado":"According to tradition, Jude Thaddeus gave his life out of love for Jesus.","correta":true,"explicacao":"He was faithful to the end, telling people about Jesus."},
    {"tipo":"multipla","enunciado":"According to tradition, what was Jude Thaddeus to Jesus?","opcoes":["A relative","A neighbor","A stranger"],"correta":0,"explicacao":"Many believe he was Jesus' cousin."},
    {"tipo":"vf","enunciado":"Tradition says Jude Thaddeus told people about Jesus in faraway lands.","correta":true,"explicacao":"After Jesus went up to Heaven, he went out into the world talking about God."},
  ],
  'judas-2': [
    {"tipo":"multipla","enunciado":"Which book of the Bible has Jude's name?","opcoes":["The Letter of Jude","The Book of Psalms","The Gospel of Mark"],"correta":0,"explicacao":"It is a very short letter in the New Testament."},
    {"tipo":"vf","enunciado":"The Letter of Jude is very short.","correta":true,"explicacao":"It has only one chapter."},
    {"tipo":"multipla","enunciado":"In which part of the Bible is the Letter of Jude?","opcoes":["In the New Testament","In the Old Testament","In the Book of Psalms"],"correta":0,"explicacao":"The New Testament tells the story of Jesus and the first Christians."},
    {"tipo":"vf","enunciado":"The Letter of Jude asks Christians to take care of their faith.","correta":true,"explicacao":"It asks us to care for our faith like a treasure."},
    {"tipo":"multipla","enunciado":"What does the letter ask us to do for people who have doubts?","opcoes":["Have compassion on them","Fight with them","Laugh at them"],"correta":0,"explicacao":"Compassion means treating others with kindness and patience."},
    {"tipo":"ordenar","enunciado":"Put together the advice of the Letter of Jude:","blocos":["Keep yourselves","in the love","of God"],"explicacao":"Staying in God's love is what matters most."},
    {"tipo":"vf","enunciado":"The Letter of Jude comes right before the last book of the Bible.","correta":true,"explicacao":"The last book of the Bible is Revelation."},
    {"tipo":"multipla","enunciado":"How does the Letter of Jude end?","opcoes":["With praise to God","With a list of names","With a war story"],"correta":0,"explicacao":"It ends by giving glory to God, who keeps us safe."},
    {"tipo":"vf","enunciado":"The Letter of Jude tells us to look down on people who have doubts.","correta":false,"explicacao":"The letter asks for compassion: helping those who are confused, with kindness."},
    {"tipo":"multipla","enunciado":"Why is the Letter of Jude called a catholic letter?","opcoes":["It is for all Christians","It is only for priests","It is a secret"],"correta":0,"explicacao":"Catholic means for everyone, all over the world."},
  ],
  'judas-3': [
    {"tipo":"vf","enunciado":"Saint Jude Thaddeus is called the saint of difficult causes.","correta":true,"explicacao":"When everything seems hard, we ask him to pray for us."},
    {"tipo":"multipla","enunciado":"What appears above Saint Jude's head in pictures?","opcoes":["A flame","A hat","A crown"],"correta":0,"explicacao":"The flame reminds us of the Holy Spirit, who came down on the apostles."},
    {"tipo":"multipla","enunciado":"Whose face does Saint Jude carry on his chest in pictures?","opcoes":["Jesus' face","A king's face","An angel's face"],"correta":0,"explicacao":"He carries Jesus close to his heart."},
    {"tipo":"vf","enunciado":"In São Paulo there is a much-visited shrine of Saint Jude Thaddeus.","correta":true,"explicacao":"Every day, many people go there to pray."},
    {"tipo":"multipla","enunciado":"Which feast does the flame above Saint Jude remind us of?","opcoes":["Pentecost","Christmas","Easter"],"correta":0,"explicacao":"At Pentecost, the Holy Spirit came as tongues of fire."},
    {"tipo":"vf","enunciado":"Asking a saint to pray for us means replacing God with the saint.","correta":false,"explicacao":"Only God is worshiped; the saints are friends who pray for us."},
    {"tipo":"multipla","enunciado":"When we ask Saint Jude for help, what does he do?","opcoes":["He prays to God for us","He does magic","Nothing"],"correta":0,"explicacao":"The saints are God's friends and pray together with us."},
    {"tipo":"vf","enunciado":"The saints are God's friends.","correta":true,"explicacao":"They lived with great love and are now with God in Heaven."},
    {"tipo":"multipla","enunciado":"Which one is a short prayer to Saint Jude?","opcoes":["Saint Jude Thaddeus, pray for us","Saint Jude Thaddeus, let's play","Saint Jude Thaddeus, see you tomorrow"],"correta":0,"explicacao":"It is a short, trusting prayer we can say at any time."},
    {"tipo":"vf","enunciado":"Having hope means trusting that God takes care of us.","correta":true,"explicacao":"Saint Jude is the apostle of hope."},
  ],
  'avila-1': [
    {"tipo":"multipla","enunciado":"In which country was Saint Teresa of Ávila born?","opcoes":["Spain","Italy","Brazil"],"correta":0,"explicacao":"She was born in the city of Ávila, in Spain."},
    {"tipo":"vf","enunciado":"As a child, Teresa ran away with her brother, dreaming of giving her life for Jesus.","correta":true,"explicacao":"An uncle found the two of them on the way and took them back home."},
    {"tipo":"multipla","enunciado":"Teresa was a Carmelite nun. What do Carmelites do a lot?","opcoes":["Pray","Run","Travel by plane"],"correta":0,"explicacao":"Carmelites spend a lot of time praying in silence."},
    {"tipo":"vf","enunciado":"Teresa opened many new houses for the sisters to pray in.","correta":true,"explicacao":"She founded many convents across Spain."},
    {"tipo":"multipla","enunciado":"How did Teresa travel around Spain?","opcoes":["By cart","By train","By car"],"correta":0,"explicacao":"She traveled in simple carts, on difficult roads."},
    {"tipo":"vf","enunciado":"Teresa had weak health, but she worked hard for God.","correta":true,"explicacao":"Not even illness made Teresa give up."},
    {"tipo":"multipla","enunciado":"What was the first convent Teresa founded?","opcoes":["Saint Joseph's","San Damiano","Monte Cassino"],"correta":0,"explicacao":"The convent of Saint Joseph is in Ávila."},
    {"tipo":"vf","enunciado":"Teresa was always serious and never joked.","correta":false,"explicacao":"Teresa was joyful and made the sisters laugh."},
    {"tipo":"multipla","enunciado":"What did Teresa teach the sisters to do?","opcoes":["Pray with their hearts","Get rich","Fight"],"correta":0,"explicacao":"For Teresa, praying is talking with a friend."},
    {"tipo":"vf","enunciado":"Saint Teresa is a Doctor of the Church, a great teacher of the faith.","correta":true,"explicacao":"She was the first woman to receive this title."},
  ],
  'avila-2': [
    {"tipo":"multipla","enunciado":"What did Teresa compare our soul to?","opcoes":["A castle","A box","A car"],"correta":0,"explicacao":"A beautiful castle, with God living right at the center."},
    {"tipo":"ordenar","enunciado":"Put together Teresa's poem:","blocos":["Let nothing disturb you,","let nothing frighten you,","God alone is enough"],"explicacao":"When we have God, we don't need to be afraid."},
    {"tipo":"multipla","enunciado":"How many dwelling places does Teresa's castle have?","opcoes":["Seven","Two","A hundred"],"correta":0,"explicacao":"Each dwelling place is a step closer to God."},
    {"tipo":"vf","enunciado":"For Teresa, God lives at the center of the castle of the soul.","correta":true,"explicacao":"God is inside us, very close."},
    {"tipo":"multipla","enunciado":"According to Teresa, what is the door into the castle?","opcoes":["Prayer","Money","Fame"],"correta":0,"explicacao":"By praying, we enter the castle and find God."},
    {"tipo":"vf","enunciado":"Teresa wrote books to teach the sisters how to pray.","correta":true,"explicacao":"One of them is called The Way of Perfection."},
    {"tipo":"vf","enunciado":"Teresa said the soul is ugly and dark.","correta":false,"explicacao":"Teresa said the soul is as beautiful as a crystal castle."},
    {"tipo":"multipla","enunciado":"What was the castle Teresa imagined made of?","opcoes":["Crystal or diamond","Sand","Cardboard"],"correta":0,"explicacao":"It is a way of saying that God made us very beautiful inside."},
    {"tipo":"vf","enunciado":"Whoever has God doesn't need to be afraid of anything.","correta":true,"explicacao":"Teresa wrote: whoever has God lacks nothing."},
    {"tipo":"multipla","enunciado":"Where can we find God, according to Teresa?","opcoes":["Inside our heart","Only in the blue sky","Nowhere"],"correta":0,"explicacao":"God is closer than we imagine."},
  ],
  'avila-3': [
    {"tipo":"multipla","enunciado":"For Teresa, praying is:","opcoes":["Talking with a friend who loves us","Repeating words without thinking","Only asking for presents"],"correta":0,"explicacao":"Teresa said praying is talking with God the way friends do."},
    {"tipo":"vf","enunciado":"Saint John of the Cross was Teresa's friend and helper.","correta":true,"explicacao":"The two worked together to renew the life of the Carmelite sisters and friars."},
    {"tipo":"multipla","enunciado":"Where did Teresa say God is also found?","opcoes":["Among the pots and pans in the kitchen","Only in palaces","Far away from us"],"correta":0,"explicacao":"Even while washing the dishes, we can be with God."},
    {"tipo":"vf","enunciado":"Teresa told how an angel touched her heart with an arrow of fire.","correta":true,"explicacao":"It was a sign of God's enormous love for her."},
    {"tipo":"multipla","enunciado":"An artist made a famous statue of Teresa. Who is with her?","opcoes":["An angel","A lion","A king"],"correta":0,"explicacao":"The statue shows the angel who touched her heart with God's love."},
    {"tipo":"vf","enunciado":"Teresa was traveling when she went to Heaven.","correta":true,"explicacao":"To the very end, she worked for the sisters with great love."},
    {"tipo":"multipla","enunciado":"What is the best way to be God's friend, according to Teresa?","opcoes":["Talk with him every day","Forget about him","Only ask for things"],"correta":0,"explicacao":"Friends talk all the time, and God loves to listen to us."},
    {"tipo":"vf","enunciado":"Teresa thought we can only pray inside a church.","correta":false,"explicacao":"We can pray anywhere: at home, at school and even in the kitchen."},
    {"tipo":"multipla","enunciado":"Who was Teresa's best friend?","opcoes":["Jesus","A king","A queen"],"correta":0,"explicacao":"Teresa talked with Jesus every day."},
    {"tipo":"vf","enunciado":"Teresa's books help people all over the world to pray.","correta":true,"explicacao":"That is why she is called a teacher of prayer."},
  ],
});
