// ============================================================
//  LUMINA SANCTI — Trilhas em espanhol
// ============================================================
// Carregado só quando a pessoa escolhe Español no site.
// Mesma ordem e mesma quantidade de atividades do português (trilhas.js):
// na múltipla escolha as opções ficam na mesma ordem, para "correta"
// continuar valendo; no "ordenar", os blocos já vêm na ordem certa da
// frase neste idioma. Trilha que ainda não está aqui aparece em português.

window.TRILHAS_TRADUZIDAS = window.TRILHAS_TRADUZIDAS || {};
window.TRILHAS_TRADUZIDAS.es = Object.assign(window.TRILHAS_TRADUZIDAS.es || {}, {
  'santo-francisco': {
    santo: "San Francisco de Asís",
    titulo: "San Francisco de Asís",
    descricao: "El pobre de Asís que abrazó a toda la creación.",
    medalha: "Pobreza",
    medalhaCompleta: "Medalla de la Pobreza",
    virtude: "Pobreza",
    licoes: {
      'francisco-1': {
        titulo: "El joven de Asís",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿En qué ciudad de Italia nació San Francisco?","opcoes":["Asís","Roma","Padua","Milán"],"correta":0,"explicacao":"Francisco nació en Asís, en Umbría, hacia 1181."},
          {"tipo":"vf","enunciado":"Antes de su conversión, Francisco soñaba con ser caballero.","correta":true,"explicacao":"Partió a la guerra soñando con la gloria militar antes de escuchar la llamada de Dios."},
          {"tipo":"multipla","enunciado":"¿Cuál era la profesión del padre de Francisco, Pietro di Bernardone?","opcoes":["Comerciante de telas","Herrero","Soldado","Agricultor"],"correta":0,"explicacao":"Pietro era un rico comerciante de telas de Asís."},
          {"tipo":"vf","enunciado":"Francisco estuvo preso durante una guerra entre Asís y Perugia.","correta":true,"explicacao":"Fue prisionero cerca de un año, tras la batalla de Collestrada, en 1202."},
          {"tipo":"multipla","enunciado":"¿Qué hizo Francisco al encontrar a un leproso en el camino?","opcoes":["Lo abrazó y lo besó","Huyó asustado","Llamó a los guardias","Le tiró monedas desde lejos"],"correta":0,"explicacao":"Venció su propio asco: lo que era amargo se le volvió dulce, como contó en su Testamento."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Francisco antes de su conversión:","blocos":["Joven rico y amigo de las fiestas","Prisionero de guerra","Encuentro con el leproso"],"explicacao":"La conversión fue llegando poco a poco, después de la prisión y la enfermedad."},
          {"tipo":"vf","enunciado":"Ante el obispo de Asís, Francisco devolvió a su padre hasta la ropa que llevaba puesta.","correta":true,"explicacao":"Renunció a la herencia y dijo que desde entonces solo llamaría padre al Padre del Cielo."},
          {"tipo":"multipla","enunciado":"¿Qué tipo de vida eligió Francisco después de su conversión?","opcoes":["Pobreza total, como Jesús","Vida de noble","Carrera militar","Comercio con su padre"],"correta":0,"explicacao":"Quiso vivir el Evangelio al pie de la letra, sin nada propio."},
          {"tipo":"vf","enunciado":"Francisco nació en una familia pobre.","correta":false,"explicacao":"Nació en una familia rica; la pobreza fue una elección suya por amor a Cristo."},
          {"tipo":"multipla","enunciado":"¿Qué nombre le dio su madre a Francisco en el bautismo?","opcoes":["Giovanni (Juan)","Pietro","Bernardo","León"],"correta":0,"explicacao":"Su madre lo bautizó Giovanni; su padre empezó a llamarlo Francesco."},
        ],
      },
      'francisco-2': {
        titulo: "Repara mi Iglesia",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué le pidió a Francisco el Crucifijo de San Damián?","opcoes":["Ve y repara mi Iglesia","Construye un castillo","Vuelve con tu padre","Parte hacia Jerusalén"],"correta":0,"explicacao":"Francisco entendió primero que se trataba de las piedras; después comprendió que era la Iglesia viva."},
          {"tipo":"ordenar","enunciado":"Ordena la oración de San Francisco:","blocos":["Señor, hazme","un instrumento","de tu paz"],"explicacao":"Es la oración sencilla atribuida al santo de Asís."},
          {"tipo":"multipla","enunciado":"¿Qué hizo Francisco primero después de escuchar al Crucifijo?","opcoes":["Reconstruyó iglesitas con sus propias manos","Fundó una universidad","Viajó a Roma como embajador","Se hizo obispo"],"correta":0,"explicacao":"Cargó piedras y restauró San Damián y otras capillas."},
          {"tipo":"vf","enunciado":"Francisco vendió telas de su padre para ayudar a reconstruir San Damián.","correta":true,"explicacao":"Vendió telas y un caballo en Foligno, lo que enojó mucho a su padre."},
          {"tipo":"multipla","enunciado":"¿Qué papa aprobó la primera regla de Francisco?","opcoes":["Inocencio III","Gregorio Magno","León XIII","Pío X"],"correta":0,"explicacao":"Inocencio III aprobó la forma de vida de los frailes hacia 1209."},
          {"tipo":"vf","enunciado":"Francisco fue ordenado sacerdote.","correta":false,"explicacao":"Por humildad, permaneció diácono toda su vida."},
          {"tipo":"multipla","enunciado":"¿Cómo se llama a los seguidores de Francisco?","opcoes":["Franciscanos o Frailes Menores","Benedictinos","Jesuitas","Dominicos"],"correta":0,"explicacao":"La Orden de los Frailes Menores nació con Francisco."},
          {"tipo":"ordenar","enunciado":"Ordena la llamada del Crucifijo:","blocos":["Francisco,","ve y repara","mi casa"],"explicacao":"La frase continúa: que, como ves, se está cayendo en ruinas."},
          {"tipo":"vf","enunciado":"Francisco amaba mucho la pequeña iglesia de la Porciúncula.","correta":true,"explicacao":"Allí creció la fraternidad y allí quiso morir."},
          {"tipo":"multipla","enunciado":"¿Qué significa Frailes Menores?","opcoes":["Hermanos pequeños y humildes","Frailes jóvenes","Frailes de poca fe","Frailes de poca estatura"],"correta":0,"explicacao":"Menores porque querían ser los últimos, al servicio de todos."},
        ],
      },
      'francisco-3': {
        titulo: "Hermano sol, hermana luna",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué cántico de Francisco alaba a Dios por las criaturas?","opcoes":["El Cántico de las Criaturas","El Te Deum","El Magníficat","La Salve"],"correta":0,"explicacao":"El Cántico del Hermano Sol alaba a Dios por el sol, la luna, el agua y la tierra."},
          {"tipo":"vf","enunciado":"San Francisco recibió los estigmas en el monte Alverna.","correta":true,"explicacao":"En 1224 recibió las llagas de Cristo en el monte Alverna."},
          {"tipo":"multipla","enunciado":"¿Con qué animal feroz hizo las paces Francisco en la ciudad de Gubbio?","opcoes":["Un lobo","Un oso","Un león","Un jabalí"],"correta":0,"explicacao":"El lobo de Gubbio dejó de atacar y los vecinos empezaron a alimentarlo."},
          {"tipo":"vf","enunciado":"Francisco montó el primer belén viviente, en Greccio.","correta":true,"explicacao":"Fue en la noche de Navidad, para que la gente viera con sus propios ojos la humildad de Belén."},
          {"tipo":"multipla","enunciado":"¿En qué año montó Francisco el belén de Greccio?","opcoes":["1223","1098","1350","1500"],"correta":0,"explicacao":"En la Navidad de 1223, tres años antes de su muerte."},
          {"tipo":"vf","enunciado":"Según la tradición, Francisco predicó incluso a los pájaros.","correta":true,"explicacao":"Es una de las escenas más conocidas de su vida."},
          {"tipo":"multipla","enunciado":"Entre otras causas, ¿de qué es patrono Francisco?","opcoes":["De la ecología y los animales","De los banqueros","De los militares","De los navegantes"],"correta":0,"explicacao":"Juan Pablo II lo proclamó patrono de la ecología en 1979."},
          {"tipo":"ordenar","enunciado":"Ordena el comienzo del Cántico de las Criaturas:","blocos":["Altísimo,","omnipotente,","buen Señor"],"explicacao":"Así comienza la alabanza del Hermano Sol."},
          {"tipo":"vf","enunciado":"Francisco llamaba hermana a la muerte.","correta":true,"explicacao":"En el Cántico, alaba a Dios por la hermana muerte corporal."},
          {"tipo":"multipla","enunciado":"¿En qué año murió Francisco?","opcoes":["1226","1181","1300","1450"],"correta":0,"explicacao":"Murió en la Porciúncula el 3 de octubre de 1226; su fiesta es el día 4."},
        ],
      },
    },
  },
  'santo-jose': {
    santo: "San José",
    titulo: "San José",
    descricao: "El guardián silencioso del Redentor.",
    medalha: "Fidelidad",
    medalhaCompleta: "Medalla de la Fidelidad",
    virtude: "Fidelidad",
    licoes: {
      'jose-1': {
        titulo: "El justo",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Cuál era el oficio de San José?","opcoes":["Carpintero","Pescador","Escriba","Pastor"],"correta":0,"explicacao":"El Evangelio lo llama el carpintero."},
          {"tipo":"vf","enunciado":"Los Evangelios no recogen ninguna palabra de San José.","correta":true,"explicacao":"José es el santo del silencio obediente."},
          {"tipo":"multipla","enunciado":"¿Cómo describe el Evangelio a José?","opcoes":["Hombre justo","Rey poderoso","Sacerdote del Templo","Profeta"],"correta":0,"explicacao":"Mateo 1,19 lo llama hombre justo."},
          {"tipo":"vf","enunciado":"José descendía del rey David.","correta":true,"explicacao":"Por eso a Jesús se le llama hijo de David."},
          {"tipo":"multipla","enunciado":"¿Qué pensó hacer José al saber que María esperaba un hijo?","opcoes":["Dejarla en secreto, sin exponerla","Denunciarla en público","Huir a Egipto","Buscar al sumo sacerdote"],"correta":0,"explicacao":"Justo y bondadoso, no quiso exponerla a la vergüenza."},
          {"tipo":"vf","enunciado":"Un ángel se le apareció en sueños a José para explicarle que el niño venía del Espíritu Santo.","correta":true,"explicacao":"Es lo que narra Mateo 1,20."},
          {"tipo":"multipla","enunciado":"¿Qué nombre le mandó el ángel a José ponerle al niño?","opcoes":["Jesús","Emmanuel","Juan","David"],"correta":0,"explicacao":"Jesús quiere decir Dios salva, porque él salvaría a su pueblo de sus pecados."},
          {"tipo":"ordenar","enunciado":"Ordena las palabras del ángel a José:","blocos":["José, hijo de David,","no temas recibir","a María, tu esposa"],"explicacao":"Palabras de Mateo 1,20."},
          {"tipo":"vf","enunciado":"José obedeció al ángel y recibió a María en su casa.","correta":true,"explicacao":"Mateo 1,24: hizo lo que el ángel del Señor le había mandado."},
          {"tipo":"multipla","enunciado":"¿En qué ciudad nació Jesús, cuando José y María fueron a empadronarse?","opcoes":["Belén","Nazaret","Jerusalén","Cafarnaún"],"correta":0,"explicacao":"Belén, la ciudad de David."},
        ],
      },
      'jose-2': {
        titulo: "La huida a Egipto",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Cómo recibió José el aviso de huir a Egipto?","opcoes":["En sueños, por un ángel","Por una carta","Por María","Por un profeta"],"correta":0,"explicacao":"El ángel del Señor se le apareció en sueños."},
          {"tipo":"vf","enunciado":"La Sagrada Familia huyó por causa de Herodes.","correta":true,"explicacao":"Herodes mandó matar a los niños de Belén."},
          {"tipo":"multipla","enunciado":"¿A qué país huyó la Sagrada Familia?","opcoes":["Egipto","Grecia","Persia","Italia"],"correta":0,"explicacao":"Huyeron a Egipto para salvar la vida del niño."},
          {"tipo":"vf","enunciado":"José solo volvió de Egipto después de la muerte de Herodes.","correta":true,"explicacao":"El ángel le avisó: ya murieron los que querían matar al niño."},
          {"tipo":"multipla","enunciado":"¿En qué ciudad fue a vivir la Sagrada Familia al volver?","opcoes":["Nazaret","Belén","Jericó","Roma"],"correta":0,"explicacao":"Fueron a vivir a Nazaret, en Galilea."},
          {"tipo":"vf","enunciado":"En la huida, José llevó al niño y a María durante la noche.","correta":true,"explicacao":"Mateo 2,14: se levantó de noche y partió."},
          {"tipo":"vf","enunciado":"José y María perdieron al niño Jesús en Jerusalén cuando tenía doce años.","correta":true,"explicacao":"Lucas 2 cuenta que lo buscaron durante tres días."},
          {"tipo":"multipla","enunciado":"¿Dónde encontraron a Jesús después de tres días?","opcoes":["En el Templo, entre los doctores","En el mercado","En casa de Isabel","En el desierto"],"correta":0,"explicacao":"Escuchaba a los maestros de la Ley y les hacía preguntas."},
          {"tipo":"ordenar","enunciado":"Ordena los acontecimientos:","blocos":["Nacimiento en Belén","Huida a Egipto","Regreso a Nazaret"],"explicacao":"José guió a la familia en cada paso."},
          {"tipo":"multipla","enunciado":"¿Quién llevó a Jesús a ser presentado en el Templo, junto con María?","opcoes":["José","Zacarías","Juan Bautista","Pedro"],"correta":0,"explicacao":"José y María lo presentaron al Señor, como mandaba la Ley."},
        ],
      },
      'jose-3': {
        titulo: "Patrono de la Iglesia",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿De qué es patrono San José?","opcoes":["De la Iglesia universal y de la buena muerte","De los viajeros","De los estudiantes","De los músicos"],"correta":0,"explicacao":"Pío IX lo declaró patrono de la Iglesia universal en 1870."},
          {"tipo":"ordenar","enunciado":"Ordena la invocación:","blocos":["San José,","protector","de la Sagrada Familia"],"explicacao":"José cuidó de Jesús y de María."},
          {"tipo":"multipla","enunciado":"¿Qué día celebra la Iglesia la solemnidad de San José?","opcoes":["19 de marzo","25 de diciembre","15 de agosto","1 de noviembre"],"correta":0,"explicacao":"El 19 de marzo es la solemnidad de San José, esposo de María."},
          {"tipo":"vf","enunciado":"El 1 de mayo celebramos a San José Obrero.","correta":true,"explicacao":"La fiesta recuerda la dignidad del trabajo."},
          {"tipo":"multipla","enunciado":"¿Qué papa creó la fiesta de San José Obrero?","opcoes":["Pío XII","Pío IX","Juan XXIII","Benedicto XVI"],"correta":0,"explicacao":"Pío XII la instituyó en 1955."},
          {"tipo":"vf","enunciado":"San José es invocado como patrono de la buena muerte.","correta":true,"explicacao":"La tradición dice que murió asistido por Jesús y María."},
          {"tipo":"multipla","enunciado":"¿Por qué San José es patrono de la buena muerte?","opcoes":["La tradición dice que murió junto a Jesús y María","Porque fue mártir","Porque vivió cien años","Porque murió en Roma"],"correta":0,"explicacao":"No hay muerte más hermosa que en los brazos de Jesús y María."},
          {"tipo":"vf","enunciado":"El papa Francisco escribió la carta Con corazón de padre, sobre San José.","correta":true,"explicacao":"La carta Patris corde es de 2020."},
          {"tipo":"ordenar","enunciado":"Ordena la jaculatoria:","blocos":["Jesús, José y María,","os doy el corazón","y el alma mía"],"explicacao":"Una oración breve muy querida por las familias católicas."},
          {"tipo":"multipla","enunciado":"Según el Evangelio, ¿qué oficio aprendió Jesús en casa?","opcoes":["Carpintero","Pescador","Pastor","Escriba"],"correta":0,"explicacao":"Marcos 6,3 llama a Jesús el carpintero."},
        ],
      },
    },
  },
  'santa-teresinha': {
    santo: "Santa Teresita del Niño Jesús",
    titulo: "Santa Teresita",
    descricao: "El caminito de la confianza.",
    medalha: "Pequeñez",
    medalhaCompleta: "Medalla de la Pequeñez",
    virtude: "Confianza",
    licoes: {
      'teresinha-1': {
        titulo: "La florecilla de Lisieux",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿En qué ciudad francesa fue carmelita Teresita?","opcoes":["Lisieux","Lourdes","París","Nevers"],"correta":0,"explicacao":"Entró en el Carmelo de Lisieux a los 15 años."},
          {"tipo":"vf","enunciado":"Teresita murió joven, a los 24 años.","correta":true,"explicacao":"Murió de tuberculosis en 1897."},
          {"tipo":"multipla","enunciado":"¿Cuál era el nombre de bautismo de Santa Teresita?","opcoes":["Marie-Françoise-Thérèse Martin","Teresa Sánchez","Marie Bernarde","Jeanne Martin"],"correta":0,"explicacao":"Nació como Marie-Françoise-Thérèse Martin."},
          {"tipo":"vf","enunciado":"Los padres de Teresita, Luis y Celia Martin, también fueron canonizados.","correta":true,"explicacao":"Fueron proclamados santos en 2015."},
          {"tipo":"multipla","enunciado":"¿En qué año nació Santa Teresita?","opcoes":["1873","1800","1920","1750"],"correta":0,"explicacao":"Nació el 2 de enero de 1873."},
          {"tipo":"vf","enunciado":"Teresita le pidió al papa León XIII entrar pronto en el Carmelo.","correta":true,"explicacao":"En una audiencia en Roma, en 1887, se lo pidió en persona."},
          {"tipo":"multipla","enunciado":"¿Cuántas hermanas de Teresita también se hicieron religiosas?","opcoes":["Cuatro","Ninguna","Una","Diez"],"correta":0,"explicacao":"María, Paulina, Leonia y Celina: todas se consagraron a Dios."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Teresita:","blocos":["Nace en Alençon","Entra en el Carmelo de Lisieux","Muere a los 24 años"],"explicacao":"Una vida corta y llena de amor."},
          {"tipo":"vf","enunciado":"Teresita nació en Alençon, en Francia.","correta":true,"explicacao":"Después la familia se mudó a Lisieux."},
          {"tipo":"multipla","enunciado":"¿Qué nombre religioso recibió Teresita en el Carmelo?","opcoes":["Teresa del Niño Jesús y de la Santa Faz","Teresa de Jesús","María del Corazón","Clara de la Cruz"],"correta":0,"explicacao":"El nombre une la infancia de Jesús y su Pasión."},
        ],
      },
      'teresinha-2': {
        titulo: "El caminito",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿En qué consiste el caminito?","opcoes":["Hacer cosas pequeñas con gran amor","Hacer grandes penitencias","Peregrinar mucho","Estudiar teología"],"correta":0,"explicacao":"Santidad escondida en lo cotidiano, con confianza de niño."},
          {"tipo":"ordenar","enunciado":"Ordena la frase de Teresita:","blocos":["Mi vocación","es el amor","en el corazón de la Iglesia"],"explicacao":"Frase de Historia de un alma."},
          {"tipo":"multipla","enunciado":"¿Con qué invento moderno comparó Teresita el caminito?","opcoes":["Un ascensor","Un tren","Un avión","Un reloj"],"correta":0,"explicacao":"El ascensor que la subiría al Cielo eran los brazos de Jesús."},
          {"tipo":"vf","enunciado":"Para Teresita, los pequeños sacrificios ofrecidos con amor agradan a Dios.","correta":true,"explicacao":"Lo que vale no es el tamaño del gesto, sino el amor."},
          {"tipo":"multipla","enunciado":"¿Cómo se veía Teresita ante Dios?","opcoes":["Como una niña en brazos de su Padre","Como una reina","Como una jueza","Como una guerrera"],"correta":0,"explicacao":"La infancia espiritual es confiar como un niño."},
          {"tipo":"vf","enunciado":"Teresita prometió pasar su cielo haciendo el bien en la tierra.","correta":true,"explicacao":"Y muchos dicen recibir gracias por su intercesión."},
          {"tipo":"ordenar","enunciado":"Ordena la promesa de Teresita:","blocos":["Quiero pasar","mi cielo","haciendo el bien en la tierra"],"explicacao":"Una de las frases más famosas de la santa."},
          {"tipo":"multipla","enunciado":"¿Qué lluvia prometió enviar Teresita desde el Cielo?","opcoes":["Lluvia de rosas","Lluvia de estrellas","Lluvia de oro","Lluvia de pan"],"correta":0,"explicacao":"Las rosas simbolizan las gracias que ella alcanza."},
          {"tipo":"vf","enunciado":"El caminito exige hacer cosas extraordinarias.","correta":false,"explicacao":"Es justo lo contrario: cosas pequeñas, hechas con gran amor."},
          {"tipo":"multipla","enunciado":"¿Qué virtud está en el centro del caminito?","opcoes":["La confianza y el amor","El miedo","La fama","La riqueza"],"correta":0,"explicacao":"Confiar en el amor misericordioso de Dios."},
        ],
      },
      'teresinha-3': {
        titulo: "Doctora y misionera",
        conteudo: [
          {"tipo":"vf","enunciado":"Teresita es patrona de las misiones aunque nunca salió del convento.","correta":true,"explicacao":"Rezaba y ofrecía sacrificios por los misioneros."},
          {"tipo":"multipla","enunciado":"¿Qué libro, escrito por ella misma, cuenta su vida?","opcoes":["Historia de un alma","Confesiones","Castillo interior","Imitación de Cristo"],"correta":0,"explicacao":"Historia de un alma se publicó después de su muerte."},
          {"tipo":"multipla","enunciado":"¿Qué papa declaró a Teresita Doctora de la Iglesia?","opcoes":["Juan Pablo II","Pío X","León XIII","Francisco"],"correta":0,"explicacao":"Fue en 1997, cien años después de su muerte."},
          {"tipo":"vf","enunciado":"Teresita es patrona de las misiones junto con San Francisco Javier.","correta":true,"explicacao":"Pío XI los proclamó patronos de las misiones en 1927."},
          {"tipo":"multipla","enunciado":"¿En qué año fue canonizada Teresita?","opcoes":["1925","1897","1965","2000"],"correta":0,"explicacao":"Pío XI la canonizó en 1925."},
          {"tipo":"vf","enunciado":"Teresita rezaba por sacerdotes misioneros y les escribía cartas.","correta":true,"explicacao":"Los llamaba sus hermanos espirituales."},
          {"tipo":"multipla","enunciado":"¿Qué enfermedad causó la muerte de Teresita?","opcoes":["Tuberculosis","Gripe","Malaria","Viruela"],"correta":0,"explicacao":"Sufrió mucho, pero con paz y confianza."},
          {"tipo":"ordenar","enunciado":"Ordena las últimas palabras de Teresita:","blocos":["Dios mío,","yo os","amo"],"explicacao":"Murió mirando el crucifijo, el 30 de septiembre de 1897."},
          {"tipo":"vf","enunciado":"Teresita es una de las cuatro mujeres Doctoras de la Iglesia.","correta":true,"explicacao":"Junto con Teresa de Ávila, Catalina de Siena e Hildegarda de Bingen."},
          {"tipo":"multipla","enunciado":"¿Cuál es la fiesta de Santa Teresita?","opcoes":["1 de octubre","19 de marzo","13 de junio","4 de octubre"],"correta":0,"explicacao":"Se celebra el 1 de octubre."},
        ],
      },
    },
  },
  'santo-antonio': {
    santo: "San Antonio de Padua",
    titulo: "San Antonio de Padua",
    descricao: "El martillo de los herejes y amigo de los pobres.",
    medalha: "Sabiduría",
    medalhaCompleta: "Medalla de la Sabiduría",
    virtude: "Sabiduría",
    licoes: {
      'antonio-1': {
        titulo: "De Lisboa a Padua",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Dónde nació San Antonio?","opcoes":["Lisboa","Padua","Asís","Sevilla"],"correta":0,"explicacao":"Nació en Lisboa, Portugal, en 1195."},
          {"tipo":"vf","enunciado":"San Antonio entró en la orden franciscana.","correta":true,"explicacao":"Dejó a los canónigos agustinos por los franciscanos."},
          {"tipo":"multipla","enunciado":"¿Cuál era el nombre de bautismo de San Antonio?","opcoes":["Fernando","Francisco","Pedro","Luis"],"correta":0,"explicacao":"Se llamaba Fernando; adoptó el nombre de Antonio al hacerse franciscano."},
          {"tipo":"vf","enunciado":"Antonio decidió hacerse franciscano al ver los cuerpos de frailes martirizados en Marruecos.","correta":true,"explicacao":"El ejemplo de los cinco mártires de 1220 lo marcó profundamente."},
          {"tipo":"multipla","enunciado":"¿Adónde partió Antonio como misionero?","opcoes":["Marruecos","Japón","Brasil","India"],"correta":0,"explicacao":"Quería predicar y dar la vida por Cristo en África."},
          {"tipo":"vf","enunciado":"Una tormenta llevó el barco de Antonio hasta Sicilia.","correta":true,"explicacao":"Enfermo, volvía a casa cuando el barco fue desviado hacia Italia."},
          {"tipo":"multipla","enunciado":"¿Cerca de qué ciudad italiana murió Antonio?","opcoes":["Padua","Roma","Nápoles","Venecia"],"correta":0,"explicacao":"Murió en Arcella, junto a Padua, en 1231."},
          {"tipo":"ordenar","enunciado":"Ordena el camino de Antonio:","blocos":["Nace en Lisboa","Se hace franciscano","Muere cerca de Padua"],"explicacao":"De Portugal a Italia, siempre predicando."},
          {"tipo":"vf","enunciado":"Antonio fue canonizado menos de un año después de morir.","correta":true,"explicacao":"Gregorio IX lo canonizó en 1232."},
          {"tipo":"multipla","enunciado":"¿Qué día se celebra a San Antonio?","opcoes":["13 de junio","24 de junio","29 de junio","8 de diciembre"],"correta":0,"explicacao":"El 13 de junio, que abre las fiestas de junio en Brasil."},
        ],
      },
      'antonio-2': {
        titulo: "Doctor evangélico",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Cómo se recuerda sobre todo a San Antonio?","opcoes":["Como gran predicador","Como rey","Como ermitaño","Como mártir"],"correta":0,"explicacao":"Su predicación bíblica le valió el título de Doctor Evangélico."},
          {"tipo":"ordenar","enunciado":"Ordena el pedido popular:","blocos":["San Antonio,","ayúdame a encontrar","lo que perdí"],"explicacao":"Se le invoca como el santo de las cosas perdidas."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿a quién predicó Antonio cuando la gente no quiso escucharlo?","opcoes":["A los peces","A los árboles","A las piedras","A los caballos"],"correta":0,"explicacao":"En Rímini, los peces habrían sacado la cabeza del agua para escucharlo."},
          {"tipo":"vf","enunciado":"Antonio fue declarado Doctor de la Iglesia.","correta":true,"explicacao":"Pío XII lo declaró Doctor en 1946."},
          {"tipo":"multipla","enunciado":"¿Cuál es el título de Antonio como Doctor de la Iglesia?","opcoes":["Doctor Evangélico","Doctor Angélico","Doctor Seráfico","Doctor de la Gracia"],"correta":0,"explicacao":"Por el amor y el conocimiento que tenía del Evangelio."},
          {"tipo":"vf","enunciado":"San Francisco le pidió a Antonio que enseñara teología a los frailes.","correta":true,"explicacao":"En una carta, Francisco lo autorizó, pidiéndole que no apagara el espíritu de oración."},
          {"tipo":"multipla","enunciado":"¿Qué apodo le dio el papa Gregorio IX a Antonio?","opcoes":["Arca del Testamento","Martillo de Dios","León de Judá","Luz de Oriente"],"correta":0,"explicacao":"Porque conocía la Biblia casi de memoria."},
          {"tipo":"ordenar","enunciado":"Ordena la predicación a los peces:","blocos":["La gente no quiso escuchar,","Antonio fue a la orilla del mar","y los peces lo escucharon"],"explicacao":"Una lección sobre la dureza del corazón humano."},
          {"tipo":"vf","enunciado":"Antonio sabía de memoria grandes partes de la Biblia.","correta":true,"explicacao":"Su predicación estaba tejida toda con la Palabra de Dios."},
          {"tipo":"multipla","enunciado":"¿Qué papa declaró a Antonio Doctor de la Iglesia?","opcoes":["Pío XII","Gregorio IX","León XIII","Juan Pablo II"],"correta":0,"explicacao":"Pío XII, en 1946."},
        ],
      },
      'antonio-3': {
        titulo: "Amigo de los pobres",
        conteudo: [
          {"tipo":"vf","enunciado":"El Pan de los Pobres es una obra de caridad ligada a San Antonio.","correta":true,"explicacao":"La devoción sostiene obras para los necesitados."},
          {"tipo":"multipla","enunciado":"¿Cómo se le representa comúnmente?","opcoes":["Con el Niño Jesús y un lirio","Con una espada","Con una corona","Con un león"],"correta":0,"explicacao":"El lirio simboliza la pureza; el Niño recuerda su visión."},
          {"tipo":"multipla","enunciado":"¿Por qué en Brasil llaman a San Antonio el santo casamentero?","opcoes":["Por la devoción popular de pedirle un buen matrimonio","Porque se casó","Porque celebró bodas de reyes","Porque era juez"],"correta":0,"explicacao":"Es una devoción del pueblo, muy viva en las fiestas de junio."},
          {"tipo":"vf","enunciado":"El lirio de las imágenes de San Antonio simboliza la pureza.","correta":true,"explicacao":"Recuerda su vida casta y su corazón limpio."},
          {"tipo":"multipla","enunciado":"Además de un buen matrimonio, ¿qué le pide más la devoción popular a San Antonio?","opcoes":["Encontrar objetos perdidos","Ganar la lotería","Vencer guerras","Hacerse famoso"],"correta":0,"explicacao":"Se le invoca como el santo de las cosas perdidas."},
          {"tipo":"vf","enunciado":"San Antonio es muy celebrado en las fiestas de junio de Brasil.","correta":true,"explicacao":"Junto con San Juan y San Pedro."},
          {"tipo":"multipla","enunciado":"¿En qué mes son las fiestas de San Antonio en Brasil?","opcoes":["Junio","Diciembre","Febrero","Abril"],"correta":0,"explicacao":"El 13 de junio."},
          {"tipo":"ordenar","enunciado":"Ordena los santos de junio por la fecha de su fiesta:","blocos":["San Antonio (13)","San Juan (24)","San Pedro (29)"],"explicacao":"Los tres grandes santos de junio."},
          {"tipo":"vf","enunciado":"El Niño Jesús en brazos de Antonio recuerda una visión que tuvo.","correta":true,"explicacao":"Según la tradición, el Niño se le apareció mientras rezaba."},
          {"tipo":"multipla","enunciado":"¿En qué año murió Antonio?","opcoes":["1231","1195","1300","1500"],"correta":0,"explicacao":"El 13 de junio de 1231, con unos 36 años."},
        ],
      },
    },
  },
  'padre-pio': {
    santo: "San Padre Pío",
    titulo: "San Padre Pío",
    descricao: "Reza, espera y no te preocupes.",
    medalha: "Penitencia",
    medalhaCompleta: "Medalla de la Penitencia",
    virtude: "Penitencia",
    licoes: {
      'pio-1': {
        titulo: "El fraile de Pietrelcina",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿A qué orden pertenecía el Padre Pío?","opcoes":["Capuchinos","Dominicos","Jesuitas","Benedictinos"],"correta":0,"explicacao":"Fue fraile capuchino en San Giovanni Rotondo."},
          {"tipo":"vf","enunciado":"El Padre Pío llevó los estigmas durante unos 50 años.","correta":true,"explicacao":"Recibió las llagas en 1918."},
          {"tipo":"multipla","enunciado":"¿Cuál era el nombre de bautismo del Padre Pío?","opcoes":["Francesco Forgione","Giovanni Bosco","Pietro Martini","Angelo Roncalli"],"correta":0,"explicacao":"Nació como Francesco Forgione, en 1887."},
          {"tipo":"vf","enunciado":"El Padre Pío nació en Pietrelcina, en el sur de Italia.","correta":true,"explicacao":"Un pueblo pequeño, en una familia campesina."},
          {"tipo":"multipla","enunciado":"¿En qué año recibió el Padre Pío los estigmas visibles?","opcoes":["1918","1887","1950","1968"],"correta":0,"explicacao":"El 20 de septiembre de 1918."},
          {"tipo":"vf","enunciado":"El Padre Pío vivió gran parte de su vida en San Giovanni Rotondo.","correta":true,"explicacao":"Se quedó allí más de cincuenta años."},
          {"tipo":"multipla","enunciado":"¿En qué año murió el Padre Pío?","opcoes":["1968","1918","1999","2002"],"correta":0,"explicacao":"Murió el 23 de septiembre de 1968."},
          {"tipo":"ordenar","enunciado":"Ordena la vida del Padre Pío:","blocos":["Nace en Pietrelcina","Recibe los estigmas","Es canonizado"],"explicacao":"De fraile sencillo a santo del mundo entero."},
          {"tipo":"vf","enunciado":"El Padre Pío nunca fue ordenado sacerdote.","correta":false,"explicacao":"Fue ordenado sacerdote en 1910."},
          {"tipo":"multipla","enunciado":"¿Cuál es la fiesta de San Padre Pío?","opcoes":["23 de septiembre","4 de octubre","25 de mayo","2 de noviembre"],"correta":0,"explicacao":"El día en que partió al Cielo."},
        ],
      },
      'pio-2': {
        titulo: "El confesionario",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué ministerio marcó la vida del Padre Pío?","opcoes":["La confesión","La enseñanza universitaria","La diplomacia","La música"],"correta":0,"explicacao":"Pasaba horas confesando a los peregrinos."},
          {"tipo":"ordenar","enunciado":"Ordena el consejo del santo:","blocos":["Reza,","espera","y no te preocupes"],"explicacao":"Frase famosa del Padre Pío."},
          {"tipo":"multipla","enunciado":"¿Cómo llamaba el Padre Pío al Rosario?","opcoes":["El arma","El adorno","La costumbre","El amuleto"],"correta":0,"explicacao":"Para él, el Rosario era el arma del cristiano."},
          {"tipo":"vf","enunciado":"El Padre Pío pasaba muchas horas al día confesando.","correta":true,"explicacao":"A veces más de diez horas en un solo día."},
          {"tipo":"multipla","enunciado":"¿Qué grupos impulsó el Padre Pío por el mundo?","opcoes":["Grupos de Oración","Clubes de lectura","Órdenes de caballería","Equipos deportivos"],"correta":0,"explicacao":"Los Grupos de Oración del Padre Pío existen hasta hoy en varios países."},
          {"tipo":"vf","enunciado":"Venía gente de muchos países para confesarse con el Padre Pío.","correta":true,"explicacao":"Las filas ante su confesionario eran enormes."},
          {"tipo":"multipla","enunciado":"Según el Padre Pío, ¿qué es la oración?","opcoes":["La mejor arma que tenemos","Una pérdida de tiempo","Algo solo de sacerdotes","Algo solo para los domingos"],"correta":0,"explicacao":"Decía que la oración es la llave que abre el corazón de Dios."},
          {"tipo":"ordenar","enunciado":"Ordena la frase del Padre Pío:","blocos":["La oración","es la mejor arma","que tenemos"],"explicacao":"Un consejo que repetía muchas veces."},
          {"tipo":"vf","enunciado":"El Padre Pío celebraba la misa con gran devoción.","correta":true,"explicacao":"Muchos se emocionaban solo con asistir a su misa."},
          {"tipo":"multipla","enunciado":"¿Qué sacramento celebraba más el Padre Pío en el confesionario?","opcoes":["La Confesión","El Matrimonio","La Confirmación","El Orden"],"correta":0,"explicacao":"La Confesión, sacramento de la misericordia de Dios."},
        ],
      },
      'pio-3': {
        titulo: "Casa Alivio del Sufrimiento",
        conteudo: [
          {"tipo":"vf","enunciado":"El Padre Pío fundó un hospital para los enfermos.","correta":true,"explicacao":"La Casa Sollievo della Sofferenza, es decir, Casa Alivio del Sufrimiento."},
          {"tipo":"multipla","enunciado":"¿En qué año fue canonizado?","opcoes":["2002","1987","1968","2015"],"correta":0,"explicacao":"Juan Pablo II lo canonizó en 2002."},
          {"tipo":"multipla","enunciado":"¿Qué papa canonizó al Padre Pío?","opcoes":["Juan Pablo II","Pablo VI","Benedicto XVI","Francisco"],"correta":0,"explicacao":"Juan Pablo II, en 2002."},
          {"tipo":"vf","enunciado":"La Casa Alivio del Sufrimiento se inauguró en 1956.","correta":true,"explicacao":"El hospital se inauguró el 5 de mayo de 1956."},
          {"tipo":"multipla","enunciado":"¿Dónde está la Casa Alivio del Sufrimiento?","opcoes":["San Giovanni Rotondo","Roma","Asís","Padua"],"correta":0,"explicacao":"Junto al convento donde vivió el Padre Pío."},
          {"tipo":"vf","enunciado":"Karol Wojtyła, el futuro Juan Pablo II, se encontró con el Padre Pío siendo un joven sacerdote.","correta":true,"explicacao":"Fue en 1947, cuando Karol estudiaba en Roma."},
          {"tipo":"multipla","enunciado":"¿En qué año fue beatificado el Padre Pío?","opcoes":["1999","1968","1950","2010"],"correta":0,"explicacao":"Beatificado en 1999 y canonizado en 2002."},
          {"tipo":"ordenar","enunciado":"Ordena los pasos hasta los altares:","blocos":["Muerte en 1968","Beatificación en 1999","Canonización en 2002"],"explicacao":"Treinta y cuatro años después de morir, fue proclamado santo."},
          {"tipo":"vf","enunciado":"Los peregrinos pueden visitar el cuerpo del Padre Pío en San Giovanni Rotondo.","correta":true,"explicacao":"El santuario recibe a millones de peregrinos."},
          {"tipo":"multipla","enunciado":"¿Qué obra de caridad fundó el Padre Pío?","opcoes":["Un hospital","Una universidad","Un banco","Un periódico"],"correta":0,"explicacao":"Para cuidar a los enfermos con amor y con la mejor medicina."},
        ],
      },
    },
  },
  'nossa-senhora': {
    santo: "Nuestra Señora",
    titulo: "Nuestra Señora",
    descricao: "El sí que abrió el Cielo.",
    medalha: "Humildad",
    medalhaCompleta: "Medalla de la Humildad",
    virtude: "Humildad",
    licoes: {
      'maria-1': {
        titulo: "La Anunciación",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué ángel le anunció a María?","opcoes":["Gabriel","Miguel","Rafael","Uriel"],"correta":0,"explicacao":"El arcángel Gabriel, en Nazaret."},
          {"tipo":"ordenar","enunciado":"Ordena la respuesta de María:","blocos":["He aquí la esclava del Señor,","hágase en mí","según tu palabra"],"explicacao":"El fiat de María, su sí a Dios."},
          {"tipo":"multipla","enunciado":"¿En qué ciudad tuvo lugar la Anunciación?","opcoes":["Nazaret","Belén","Jerusalén","Caná"],"correta":0,"explicacao":"En una pequeña ciudad de Galilea."},
          {"tipo":"vf","enunciado":"El ángel saludó a María diciendo: Alégrate, llena de gracia, el Señor está contigo.","correta":true,"explicacao":"Lucas 1,28."},
          {"tipo":"multipla","enunciado":"¿Qué nombre dijo el ángel que María pondría al niño?","opcoes":["Jesús","Juan","David","Moisés"],"correta":0,"explicacao":"Lucas 1,31."},
          {"tipo":"vf","enunciado":"María le preguntó al ángel cómo sucedería aquello.","correta":true,"explicacao":"No por falta de fe, sino para entender y responder de corazón."},
          {"tipo":"multipla","enunciado":"¿Qué pariente de María también esperaba un hijo?","opcoes":["Isabel","Ana","Marta","Sara"],"correta":0,"explicacao":"Isabel, que ya era anciana, esperaba a Juan Bautista."},
          {"tipo":"multipla","enunciado":"¿Qué día celebra la Iglesia la Anunciación?","opcoes":["25 de marzo","25 de diciembre","15 de agosto","8 de septiembre"],"correta":0,"explicacao":"Nueve meses antes de Navidad."},
          {"tipo":"vf","enunciado":"El ángel le dijo a María que para Dios nada es imposible.","correta":true,"explicacao":"Lucas 1,37."},
          {"tipo":"ordenar","enunciado":"Ordena el saludo del ángel:","blocos":["Dios te salve, María,","llena eres de gracia,","el Señor es contigo"],"explicacao":"Es el comienzo del Avemaría."},
        ],
      },
      'maria-2': {
        titulo: "El Magníficat",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Dónde proclamó María el Magníficat?","opcoes":["En la visita a Isabel","En el Templo","En Belén","En el Calvario"],"correta":0,"explicacao":"En la Visitación a su prima Isabel."},
          {"tipo":"vf","enunciado":"El Magníficat exalta a los humildes y derriba a los poderosos.","correta":true,"explicacao":"Dios derriba del trono a los poderosos y enaltece a los humildes."},
          {"tipo":"multipla","enunciado":"¿Cómo comienza el cántico de María?","opcoes":["Proclama mi alma la grandeza del Señor","Padre nuestro que estás en el cielo","Gloria a Dios en el cielo","Creo en Dios Padre"],"correta":0,"explicacao":"En latín, Magnificat anima mea Dominum."},
          {"tipo":"vf","enunciado":"Al oír el saludo de María, el niño saltó en el seno de Isabel.","correta":true,"explicacao":"Juan Bautista ya se alegraba con la llegada de Jesús."},
          {"tipo":"multipla","enunciado":"¿Qué hijo esperaba Isabel?","opcoes":["Juan Bautista","Santiago","Andrés","Pedro"],"correta":0,"explicacao":"El precursor que prepararía el camino de Jesús."},
          {"tipo":"vf","enunciado":"Isabel llamó a María bendita entre las mujeres.","correta":true,"explicacao":"Lucas 1,42."},
          {"tipo":"ordenar","enunciado":"Ordena el comienzo del Magníficat:","blocos":["Proclama","mi alma","la grandeza del Señor"],"explicacao":"María alaba a Dios por las maravillas que hizo en ella."},
          {"tipo":"multipla","enunciado":"¿Cuánto tiempo se quedó María con Isabel?","opcoes":["Unos tres meses","Un día","Diez años","Una semana"],"correta":0,"explicacao":"Lucas 1,56."},
          {"tipo":"vf","enunciado":"En el Magníficat, María dice que todas las generaciones la llamarán bienaventurada.","correta":true,"explicacao":"Lucas 1,48."},
          {"tipo":"multipla","enunciado":"¿Qué día se celebra la Visitación de la Virgen?","opcoes":["31 de mayo","2 de febrero","1 de enero","12 de octubre"],"correta":0,"explicacao":"Cerrando el mes de mayo, dedicado a María."},
        ],
      },
      'maria-3': {
        titulo: "Madre de la Iglesia",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿A quién le confió Jesús a María desde la cruz?","opcoes":["Al discípulo amado","A Pedro","A Santiago","A Nicodemo"],"correta":0,"explicacao":"Ahí tienes a tu madre, le dijo a Juan."},
          {"tipo":"vf","enunciado":"El Rosario medita misterios de la vida de Jesús y de María.","correta":true,"explicacao":"Son cuatro series de misterios."},
          {"tipo":"multipla","enunciado":"¿Quién es la patrona de Brasil?","opcoes":["Nuestra Señora Aparecida","Nuestra Señora de Fátima","Nuestra Señora de Lourdes","Nuestra Señora de Guadalupe"],"correta":0,"explicacao":"Su imagen fue encontrada por pescadores en el río Paraíba del Sur."},
          {"tipo":"vf","enunciado":"La fiesta de Nuestra Señora Aparecida es el 12 de octubre.","correta":true,"explicacao":"Es feriado nacional en Brasil."},
          {"tipo":"multipla","enunciado":"En Fátima, ¿a cuántos pastorcitos se apareció la Virgen?","opcoes":["Tres","Uno","Doce","Siete"],"correta":0,"explicacao":"Lucía, Francisco y Jacinta, en 1917."},
          {"tipo":"vf","enunciado":"La Asunción enseña que María fue llevada al Cielo en cuerpo y alma.","correta":true,"explicacao":"Es un dogma proclamado por Pío XII en 1950."},
          {"tipo":"multipla","enunciado":"¿Qué día se celebra la Asunción de la Virgen?","opcoes":["15 de agosto","8 de diciembre","25 de marzo","1 de mayo"],"correta":0,"explicacao":"En Brasil, la solemnidad suele trasladarse al domingo siguiente."},
          {"tipo":"ordenar","enunciado":"Ordena el pedido de María en Caná:","blocos":["Haced","lo que","él os diga"],"explicacao":"Juan 2,5: el consejo de María para todos nosotros."},
          {"tipo":"vf","enunciado":"En Lourdes, la Virgen se apareció a Santa Bernardita.","correta":true,"explicacao":"Fueron dieciocho apariciones, en 1858."},
          {"tipo":"multipla","enunciado":"¿Qué celebramos el 8 de diciembre?","opcoes":["La Inmaculada Concepción","La Asunción","La Anunciación","La Natividad de María"],"correta":0,"explicacao":"María fue preservada del pecado original desde su concepción."},
        ],
      },
    },
  },
  'sao-bento': {
    santo: "San Benito",
    titulo: "San Benito",
    descricao: "Ora et labora: orden para la vida.",
    medalha: "Orden",
    medalhaCompleta: "Medalla del Orden",
    virtude: "Disciplina",
    licoes: {
      'bento-1': {
        titulo: "Padre del monacato",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué lema resume la regla benedictina?","opcoes":["Ora et labora","Carpe diem","Sola fide","Veni vidi vici"],"correta":0,"explicacao":"Reza y trabaja."},
          {"tipo":"vf","enunciado":"San Benito es patrono de Europa.","correta":true,"explicacao":"Proclamado por Pablo VI en 1964."},
          {"tipo":"multipla","enunciado":"¿En qué ciudad italiana nació San Benito?","opcoes":["Nursia","Asís","Milán","Nápoles"],"correta":0,"explicacao":"Nursia, hoy Norcia, en Umbría."},
          {"tipo":"vf","enunciado":"Según la tradición, Benito tenía una hermana gemela, Santa Escolástica.","correta":true,"explicacao":"Ella también se consagró a Dios."},
          {"tipo":"multipla","enunciado":"¿Dónde vivió Benito como ermitaño, en una cueva?","opcoes":["Subiaco","Cluny","Lisboa","París"],"correta":0,"explicacao":"Vivió tres años en una cueva cerca de Subiaco."},
          {"tipo":"vf","enunciado":"Benito dejó los estudios en Roma para buscar a Dios en la soledad.","correta":true,"explicacao":"No quiso perderse en la vida desordenada de la ciudad."},
          {"tipo":"multipla","enunciado":"¿En qué siglo vivió San Benito?","opcoes":["Siglo VI","Siglo XIII","Siglo I","Siglo XIX"],"correta":0,"explicacao":"Vivió aproximadamente entre el 480 y el 547."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Benito:","blocos":["Estudios en Roma","Ermitaño en Subiaco","Monasterio de Montecasino"],"explicacao":"De la soledad nació una gran familia de monjes."},
          {"tipo":"vf","enunciado":"La fiesta de San Benito es el 11 de julio.","correta":true,"explicacao":"Se celebra el 11 de julio."},
          {"tipo":"multipla","enunciado":"¿Qué papa proclamó a San Benito patrono de Europa?","opcoes":["Pablo VI","Pío IX","Juan XXIII","Gregorio Magno"],"correta":0,"explicacao":"Pablo VI, en 1964."},
        ],
      },
      'bento-2': {
        titulo: "La Regla",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué organiza la Regla de San Benito?","opcoes":["La vida de los monjes","El calendario civil","La liturgia oriental","Las cruzadas"],"correta":0,"explicacao":"Oración, trabajo, lectura y hospitalidad."},
          {"tipo":"ordenar","enunciado":"Ordena la máxima benedictina:","blocos":["Que en todo","sea Dios","glorificado"],"explicacao":"Ut in omnibus glorificetur Deus."},
          {"tipo":"multipla","enunciado":"¿Cuál es la primera palabra de la Regla de San Benito?","opcoes":["Escucha","Reza","Trabaja","Calla"],"correta":0,"explicacao":"La Regla comienza: Escucha, hijo."},
          {"tipo":"vf","enunciado":"Muchos monasterios siguen usando hoy la Regla de San Benito.","correta":true,"explicacao":"Desde hace casi 1500 años guía a monjes y monjas."},
          {"tipo":"multipla","enunciado":"Según la Regla, ¿cómo deben ser recibidos los huéspedes?","opcoes":["Como el mismo Cristo","Con desconfianza","Solo si pagan","Solo los domingos"],"correta":0,"explicacao":"La hospitalidad es signo de amor a Cristo."},
          {"tipo":"vf","enunciado":"La Regla enseña que nada debe anteponerse a la oración, la Obra de Dios.","correta":true,"explicacao":"Nada se anteponga a la Obra de Dios, dice el capítulo 43."},
          {"tipo":"multipla","enunciado":"¿Cómo se llama el superior de un monasterio benedictino?","opcoes":["Abad","Cardenal","Obispo","Diácono"],"correta":0,"explicacao":"Abad viene de abba, padre."},
          {"tipo":"ordenar","enunciado":"Ordena el comienzo de la Regla:","blocos":["Escucha, hijo,","los preceptos","del maestro"],"explicacao":"Una invitación a escuchar con el corazón."},
          {"tipo":"vf","enunciado":"Los monjes benedictinos hacen voto de estabilidad, que los une a su monasterio.","correta":true,"explicacao":"Así aprenden a buscar a Dios en el mismo lugar, con la misma comunidad."},
          {"tipo":"multipla","enunciado":"¿Cuántos capítulos tiene la Regla de San Benito?","opcoes":["73","10","150","365"],"correta":0,"explicacao":"Son 73 capítulos, con un prólogo."},
        ],
      },
      'bento-3': {
        titulo: "La medalla de San Benito",
        conteudo: [
          {"tipo":"vf","enunciado":"La medalla de San Benito lleva una oración de exorcismo abreviada.","correta":true,"explicacao":"Las letras representan frases latinas de protección."},
          {"tipo":"multipla","enunciado":"¿Dónde fundó San Benito su monasterio principal?","opcoes":["Montecasino","Cluny","Asís","Nuevo Subiaco"],"correta":0,"explicacao":"Montecasino, en Italia."},
          {"tipo":"multipla","enunciado":"¿Qué significan las letras C.S.P.B. de la medalla?","opcoes":["Cruz del Santo Padre Benito","Cristo Salva Por el Bautismo","Caridad, Santidad, Paz y Bien","Casa de San Pedro y Benito"],"correta":0,"explicacao":"Del latín Crux Sancti Patris Benedicti."},
          {"tipo":"vf","enunciado":"En la medalla está la frase latina Vade retro satana: apártate, Satanás.","correta":true,"explicacao":"Es una antigua oración contra el mal."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿cómo escapó Benito de una copa envenenada?","opcoes":["Hizo la señal de la cruz y la copa se rompió","Tiró la copa al río","La bebió y no le pasó nada","Un ángel se llevó la copa"],"correta":0,"explicacao":"La historia la cuenta San Gregorio Magno."},
          {"tipo":"vf","enunciado":"El cuervo de las imágenes de San Benito recuerda la historia del pan envenenado.","correta":true,"explicacao":"El cuervo se llevó lejos el pan que intentaron darle."},
          {"tipo":"multipla","enunciado":"¿Quién escribió la vida de San Benito en los Diálogos?","opcoes":["San Gregorio Magno","San Agustín","San Jerónimo","Santo Tomás de Aquino"],"correta":0,"explicacao":"El papa Gregorio Magno, en el siglo VI."},
          {"tipo":"ordenar","enunciado":"Ordena la frase grabada en la cruz de la medalla:","blocos":["La santa cruz","sea mi","luz"],"explicacao":"En latín: Crux sacra sit mihi lux."},
          {"tipo":"vf","enunciado":"La medalla de San Benito es un sacramental de la Iglesia.","correta":true,"explicacao":"Los sacramentales ayudan a vivir la fe, pero no son amuletos."},
          {"tipo":"multipla","enunciado":"¿Para qué sirve un sacramental como la medalla?","opcoes":["Para recordar a Dios y pedir su protección","Para tener suerte en el juego","Para adivinar el futuro","Para hacerse rico"],"correta":0,"explicacao":"Nos lleva a rezar y a confiar en Dios."},
        ],
      },
    },
  },
  'santa-clara': {
    santo: "Santa Clara de Asís",
    titulo: "Santa Clara de Asís",
    descricao: "La luz que eligió lo esencial.",
    medalha: "Pureza",
    medalhaCompleta: "Medalla de la Pureza",
    virtude: "Pureza",
    licoes: {
      'clara-1': {
        titulo: "La huida de Asís",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Quién ayudó a Clara a abrazar la vida religiosa?","opcoes":["San Francisco","San Benito","San Antonio","Santo Domingo"],"correta":0,"explicacao":"Francisco la acogió en la Porciúncula."},
          {"tipo":"vf","enunciado":"Clara fundó la orden de las Clarisas.","correta":true,"explicacao":"Las Damas Pobres de San Damián."},
          {"tipo":"multipla","enunciado":"¿De qué tipo de familia venía Clara?","opcoes":["Noble y rica","Campesina y pobre","De pescadores","De soldados"],"correta":0,"explicacao":"Dejó una vida cómoda para seguir a Cristo pobre."},
          {"tipo":"vf","enunciado":"Clara huyó de casa la noche del Domingo de Ramos para seguir a Cristo.","correta":true,"explicacao":"Fue en 1212, a los 18 años."},
          {"tipo":"multipla","enunciado":"¿En qué año lo dejó todo Clara para seguir a Cristo?","opcoes":["1212","1181","1300","1500"],"correta":0,"explicacao":"En la Semana Santa de 1212."},
          {"tipo":"vf","enunciado":"Francisco le cortó el cabello a Clara como signo de consagración.","correta":true,"explicacao":"Ocurrió en la Porciúncula, esa misma noche."},
          {"tipo":"multipla","enunciado":"¿Qué hermana de Clara la siguió también en la vida religiosa?","opcoes":["Santa Inés de Asís","Santa Mónica","Santa Rita","Santa Ana"],"correta":0,"explicacao":"Inés la siguió pocos días después."},
          {"tipo":"ordenar","enunciado":"Ordena la noche de la huida de Clara:","blocos":["Sale de casa de noche","Encuentra a Francisco en la Porciúncula","Se consagra a Dios"],"explicacao":"Una decisión valiente por amor a Jesús."},
          {"tipo":"vf","enunciado":"Clara vivió más de 40 años en San Damián.","correta":true,"explicacao":"Desde 1212 hasta su muerte, en 1253."},
          {"tipo":"multipla","enunciado":"¿Cómo se llamaban las primeras hermanas de Clara?","opcoes":["Damas Pobres","Hermanas de la Caridad","Carmelitas","Benedictinas"],"correta":0,"explicacao":"Las Damas Pobres de San Damián."},
        ],
      },
      'clara-2': {
        titulo: "La Eucaristía que protege",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Con qué habría alejado Clara a los invasores del convento?","opcoes":["El Santísimo Sacramento","Una espada","Un ejército","Un muro nuevo"],"correta":0,"explicacao":"Alzó la custodia ante los soldados."},
          {"tipo":"ordenar","enunciado":"Ordena el consejo de Clara:","blocos":["Míralo,","considéralo,","contémplalo"],"explicacao":"De su carta a Santa Inés de Praga."},
          {"tipo":"multipla","enunciado":"¿Quiénes eran los soldados que atacaron el convento de Clara?","opcoes":["Sarracenos al servicio del emperador","Vikingos","Romanos antiguos","Caballeros franceses"],"correta":0,"explicacao":"Soldados sarracenos al servicio de Federico II, hacia 1240."},
          {"tipo":"vf","enunciado":"Aun enferma, Clara enfrentó a los invasores con la Eucaristía.","correta":true,"explicacao":"Confió en Jesús presente en el Santísimo Sacramento."},
          {"tipo":"multipla","enunciado":"¿Con quién intercambiaba Clara cartas llenas de consejos espirituales?","opcoes":["Santa Inés de Praga","Santa Teresa de Ávila","Santa Mónica","Santa Juana de Arco"],"correta":0,"explicacao":"Inés, una princesa que también eligió la pobreza."},
          {"tipo":"vf","enunciado":"Clara fue la primera mujer que escribió una regla de vida religiosa aprobada por el Papa.","correta":true,"explicacao":"Una regla centrada en la pobreza y la oración."},
          {"tipo":"multipla","enunciado":"¿Qué privilegio defendió Clara toda la vida?","opcoes":["El privilegio de la pobreza","El privilegio de la riqueza","El privilegio de viajar","El privilegio de gobernar"],"correta":0,"explicacao":"El derecho a vivir sin posesiones, confiando solo en Dios."},
          {"tipo":"ordenar","enunciado":"Ordena la defensa del convento:","blocos":["Los soldados rodean el monasterio","Clara alza el Santísimo","Los invasores huyen"],"explicacao":"Una victoria de la fe, no de las armas."},
          {"tipo":"vf","enunciado":"La regla de Clara fue aprobada poco antes de su muerte.","correta":true,"explicacao":"Fue aprobada en 1253, dos días antes de que muriera."},
          {"tipo":"multipla","enunciado":"¿En qué año murió Santa Clara?","opcoes":["1253","1226","1300","1212"],"correta":0,"explicacao":"El 11 de agosto de 1253."},
        ],
      },
      'clara-3': {
        titulo: "Patrona",
        conteudo: [
          {"tipo":"vf","enunciado":"Santa Clara es patrona de la televisión.","correta":true,"explicacao":"Porque, estando enferma, vio la misa a distancia."},
          {"tipo":"multipla","enunciado":"¿Cuál era el tesoro de Clara?","opcoes":["La pobreza evangélica","El oro","Las tierras","Los libros"],"correta":0,"explicacao":"Luchó por el privilegio de la pobreza."},
          {"tipo":"multipla","enunciado":"¿Qué papa proclamó a Santa Clara patrona de la televisión?","opcoes":["Pío XII","Pío IX","León XIII","Juan Pablo II"],"correta":0,"explicacao":"Pío XII, en 1958."},
          {"tipo":"vf","enunciado":"Santa Clara se celebra el 11 de agosto.","correta":true,"explicacao":"El día de su muerte."},
          {"tipo":"multipla","enunciado":"¿Qué recuerda el nombre de Clara?","opcoes":["La luz y la claridad","La fuerza","La riqueza","El silencio"],"correta":0,"explicacao":"Una vida que iluminó muchas otras."},
          {"tipo":"vf","enunciado":"Clara fue canonizada solo dos años después de morir.","correta":true,"explicacao":"Fue canonizada en 1255."},
          {"tipo":"multipla","enunciado":"¿Cómo se llama la orden fundada por Clara?","opcoes":["Orden de Santa Clara, las Clarisas","Orden de Predicadores","Compañía de Jesús","Orden de San Benito"],"correta":0,"explicacao":"Las Clarisas están hoy en el mundo entero."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Clara:","blocos":["Deja a su familia rica","Vive en San Damián","Es proclamada santa"],"explicacao":"Pobreza, oración y alegría."},
          {"tipo":"vf","enunciado":"Clara y Francisco fueron grandes amigos en la fe.","correta":true,"explicacao":"Una amistad santa, totalmente vuelta hacia Dios."},
          {"tipo":"multipla","enunciado":"¿Qué veía Clara como la mayor riqueza?","opcoes":["Jesús pobre y crucificado","Las joyas de la familia","Los títulos de nobleza","Las tierras de la familia"],"correta":0,"explicacao":"Para ella, quien tiene a Jesús lo tiene todo."},
        ],
      },
    },
  },
  'joao-paulo-ii': {
    santo: "San Juan Pablo II",
    titulo: "San Juan Pablo II",
    descricao: "¡No tengáis miedo!",
    medalha: "Valentía",
    medalhaCompleta: "Medalla de la Valentía",
    virtude: "Valentía",
    licoes: {
      'jpii-1': {
        titulo: "El papa polaco",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿De qué país venía Juan Pablo II?","opcoes":["Polonia","Italia","Alemania","Argentina"],"correta":0,"explicacao":"Karol Wojtyła nació en Wadowice."},
          {"tipo":"ordenar","enunciado":"Ordena la invitación del inicio del pontificado:","blocos":["¡No tengáis miedo!","Abrid las puertas","a Cristo"],"explicacao":"De su homilía de 1978."},
          {"tipo":"multipla","enunciado":"¿Cuál era el nombre de bautismo de Juan Pablo II?","opcoes":["Karol Wojtyła","Joseph Ratzinger","Angelo Roncalli","Giovanni Montini"],"correta":0,"explicacao":"Karol Józef Wojtyła."},
          {"tipo":"vf","enunciado":"Durante la guerra, Karol trabajó en una cantera y en una fábrica.","correta":true,"explicacao":"Conoció de cerca la vida de los obreros."},
          {"tipo":"multipla","enunciado":"¿En qué año fue elegido papa?","opcoes":["1978","1958","2005","1963"],"correta":0,"explicacao":"El 16 de octubre de 1978."},
          {"tipo":"vf","enunciado":"A Karol le gustaban el teatro y deportes como el esquí y el piragüismo.","correta":true,"explicacao":"Fue actor en su juventud y siempre amó la naturaleza."},
          {"tipo":"multipla","enunciado":"¿Cuál era su ciudad natal?","opcoes":["Wadowice","Cracovia","Varsovia","Roma"],"correta":0,"explicacao":"Nació en Wadowice, en 1920."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Karol:","blocos":["Nace en Wadowice","Arzobispo de Cracovia","Papa en 1978"],"explicacao":"De Polonia al mundo entero."},
          {"tipo":"vf","enunciado":"Su pontificado fue uno de los más largos de la historia, casi 27 años.","correta":true,"explicacao":"De 1978 a 2005."},
          {"tipo":"multipla","enunciado":"¿En qué año murió Juan Pablo II?","opcoes":["2005","1999","2010","2014"],"correta":0,"explicacao":"El 2 de abril de 2005, víspera del Domingo de la Divina Misericordia."},
        ],
      },
      'jpii-2': {
        titulo: "Los jóvenes",
        conteudo: [
          {"tipo":"vf","enunciado":"Juan Pablo II creó la Jornada Mundial de la Juventud.","correta":true,"explicacao":"La primera Jornada internacional fue en 1987."},
          {"tipo":"multipla","enunciado":"¿Qué devoción difundió junto con Santa Faustina?","opcoes":["La Divina Misericordia","El Escapulario","El Vía Crucis","La Novena de Navidad"],"correta":0,"explicacao":"Instituyó el Domingo de la Divina Misericordia."},
          {"tipo":"multipla","enunciado":"¿Qué santa polaca, ligada a la Divina Misericordia, canonizó?","opcoes":["Santa Faustina Kowalska","Santa Teresita","Santa Edith Stein","Santa Eduviges"],"correta":0,"explicacao":"Fue canonizada en el año 2000."},
          {"tipo":"vf","enunciado":"Juan Pablo II visitó Brasil más de una vez.","correta":true,"explicacao":"Estuvo en Brasil en 1980, 1991 y 1997."},
          {"tipo":"multipla","enunciado":"¿Cuántas veces vino Juan Pablo II a Brasil?","opcoes":["Tres","Una","Diez","Ninguna"],"correta":0,"explicacao":"Tres viajes apostólicos."},
          {"tipo":"vf","enunciado":"Llamó a los jóvenes centinelas de la mañana.","correta":true,"explicacao":"En la Jornada Mundial de la Juventud del año 2000, en Roma."},
          {"tipo":"multipla","enunciado":"¿En qué año se instituyó el Domingo de la Divina Misericordia?","opcoes":["2000","1978","1987","2005"],"correta":0,"explicacao":"El mismo día de la canonización de Santa Faustina."},
          {"tipo":"ordenar","enunciado":"Ordena la frase a los jóvenes:","blocos":["Vosotros sois","la esperanza","de la Iglesia"],"explicacao":"Confiaba mucho en la juventud."},
          {"tipo":"vf","enunciado":"Juan Pablo II canonizó a muchos santos, mostrando que la santidad es posible hoy.","correta":true,"explicacao":"Canonizó a cientos de santos de todos los continentes."},
          {"tipo":"multipla","enunciado":"¿Cómo se conoce su enseñanza sobre el amor humano?","opcoes":["Teología del Cuerpo","Suma Teológica","Confesiones","Imitación de Cristo"],"correta":0,"explicacao":"Una serie de catequesis dadas entre 1979 y 1984."},
        ],
      },
      'jpii-3': {
        titulo: "Perdón y testimonio",
        conteudo: [
          {"tipo":"vf","enunciado":"Perdonó públicamente a quien atentó contra su vida.","correta":true,"explicacao":"Visitó a Ali Ağca en la cárcel."},
          {"tipo":"multipla","enunciado":"¿Qué misterios del Rosario añadió?","opcoes":["Luminosos","Gloriosos","Dolorosos","Gozosos"],"correta":0,"explicacao":"Propuestos en 2002."},
          {"tipo":"multipla","enunciado":"¿En qué año sufrió Juan Pablo II el atentado en la Plaza de San Pedro?","opcoes":["1981","1978","1995","2001"],"correta":0,"explicacao":"El 13 de mayo de 1981."},
          {"tipo":"vf","enunciado":"El atentado ocurrió el 13 de mayo, día de Nuestra Señora de Fátima.","correta":true,"explicacao":"Él vio en ello una señal de la protección de María."},
          {"tipo":"multipla","enunciado":"¿A quién atribuyó el Papa haber sobrevivido al atentado?","opcoes":["A Nuestra Señora de Fátima","Solo a los médicos","A la suerte","A un guardaespaldas"],"correta":0,"explicacao":"Dijo que una mano disparó y otra guió la bala."},
          {"tipo":"vf","enunciado":"La bala del atentado fue colocada en la corona de Nuestra Señora de Fátima.","correta":true,"explicacao":"La ofreció al santuario en acción de gracias."},
          {"tipo":"multipla","enunciado":"¿En qué año fue canonizado Juan Pablo II?","opcoes":["2014","2005","2011","2020"],"correta":0,"explicacao":"El 27 de abril de 2014."},
          {"tipo":"ordenar","enunciado":"Ordena los pasos hasta los altares:","blocos":["Muere en 2005","Beatificado en 2011","Canonizado en 2014"],"explicacao":"En su funeral, el pueblo ya gritaba: ¡santo súbito!"},
          {"tipo":"vf","enunciado":"Fue canonizado el mismo día que San Juan XXIII.","correta":true,"explicacao":"Una ceremonia con dos papas santos."},
          {"tipo":"multipla","enunciado":"¿Cuál es la fiesta de San Juan Pablo II?","opcoes":["22 de octubre","2 de abril","13 de mayo","1 de noviembre"],"correta":0,"explicacao":"El día del inicio de su pontificado, en 1978."},
        ],
      },
    },
  },
  'santa-rita': {
    santo: "Santa Rita de Casia",
    titulo: "Santa Rita de Casia",
    descricao: "La santa de las causas imposibles.",
    medalha: "Perseverancia",
    medalhaCompleta: "Medalla de la Perseverancia",
    virtude: "Perseverancia",
    licoes: {
      'rita-1': {
        titulo: "Esposa y madre",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Para qué se invoca a Santa Rita?","opcoes":["Causas imposibles","Viajes","Estudios","Cosechas"],"correta":0,"explicacao":"Es la patrona de las causas difíciles."},
          {"tipo":"vf","enunciado":"Antes de ser religiosa, Rita fue esposa y madre.","correta":true,"explicacao":"Solo entró en el convento después de enviudar."},
          {"tipo":"multipla","enunciado":"¿En qué país nació Santa Rita?","opcoes":["Italia","España","Portugal","Francia"],"correta":0,"explicacao":"En Roccaporena, cerca de Casia."},
          {"tipo":"vf","enunciado":"Rita quería ser religiosa desde joven, pero sus padres concertaron su matrimonio.","correta":true,"explicacao":"Obedeció y vivió el matrimonio con fe."},
          {"tipo":"multipla","enunciado":"¿Cómo era el marido de Rita al comienzo del matrimonio?","opcoes":["Violento y difícil","Muy tranquilo","Tímido","Bromista"],"correta":0,"explicacao":"La tradición dice que tenía un carácter muy fuerte."},
          {"tipo":"vf","enunciado":"Con paciencia y oración, Rita ayudó a su marido a cambiar de vida.","correta":true,"explicacao":"Su mansedumbre tocó el corazón de él."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿cuántos hijos tuvo Rita?","opcoes":["Dos","Uno","Cinco","Ninguno"],"correta":0,"explicacao":"Dos varones, a quienes educó en la fe."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Rita:","blocos":["Esposa y madre","Viuda","Religiosa agustina"],"explicacao":"Santa en todas las etapas de la vida."},
          {"tipo":"vf","enunciado":"Santa Rita se celebra el 22 de mayo.","correta":true,"explicacao":"El día de su muerte, en 1457."},
          {"tipo":"multipla","enunciado":"¿Qué flor es símbolo de Santa Rita?","opcoes":["La rosa","El girasol","El tulipán","El clavel"],"correta":0,"explicacao":"Por la rosa que floreció en invierno."},
        ],
      },
      'rita-2': {
        titulo: "El perdón",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué pidió Rita cuando mataron a su marido?","opcoes":["El perdón entre las familias","Venganza","Dinero","El destierro"],"correta":0,"explicacao":"Pidió la paz y el fin de la enemistad."},
          {"tipo":"ordenar","enunciado":"Ordena la oración:","blocos":["Santa Rita,","abogada","de las causas imposibles"],"explicacao":"Invocación tradicional."},
          {"tipo":"multipla","enunciado":"¿Qué le pasó al marido de Rita?","opcoes":["Lo mataron en una pelea entre familias","Se hizo monje","Se mudó lejos","Se hizo rey"],"correta":0,"explicacao":"Una enemistad entre familias le quitó la vida."},
          {"tipo":"vf","enunciado":"Rita perdonó a los asesinos de su marido.","correta":true,"explicacao":"Eligió el perdón en lugar del odio."},
          {"tipo":"multipla","enunciado":"¿Qué le pidió Rita a Dios para que sus hijos no se vengaran?","opcoes":["Que Dios se los llevara antes de cometer ese pecado","Que se hicieran ricos","Que fueran a la guerra","Que olvidaran a su padre"],"correta":0,"explicacao":"Según la tradición, los dos murieron de enfermedad, en paz con Dios."},
          {"tipo":"vf","enunciado":"Rita logró reconciliar a las familias enemigas.","correta":true,"explicacao":"La tradición dice que esa fue la condición para entrar en el convento."},
          {"tipo":"multipla","enunciado":"¿Qué virtud se recuerda más en la vida de Rita?","opcoes":["El perdón","La vanidad","La prisa","La ambición"],"correta":0,"explicacao":"El perdón que rompe el ciclo de la venganza."},
          {"tipo":"ordenar","enunciado":"Ordena el camino del perdón:","blocos":["Rita sufre la pérdida,","reza y perdona","y trae la paz"],"explicacao":"El perdón comienza en la oración."},
          {"tipo":"vf","enunciado":"Perdonar no significa aprobar el mal, sino no guardar odio en el corazón.","correta":true,"explicacao":"El perdón sana a quien perdona."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿cuál fue la condición para que Rita entrara en el convento?","opcoes":["Reconciliar a las familias rivales","Pagar una dote alta","Aprender latín","Esperar diez años"],"correta":0,"explicacao":"Solo después de la paz entre las familias fue aceptada."},
        ],
      },
      'rita-3': {
        titulo: "La espina",
        conteudo: [
          {"tipo":"vf","enunciado":"Rita recibió en la frente la herida de una espina de la corona de Cristo.","correta":true,"explicacao":"Llevó la llaga durante quince años."},
          {"tipo":"multipla","enunciado":"¿En qué orden entró Rita?","opcoes":["Agustinas","Carmelitas","Clarisas","Dominicas"],"correta":0,"explicacao":"En el monasterio agustino de Casia."},
          {"tipo":"multipla","enunciado":"¿En qué ciudad está el monasterio de Santa Rita?","opcoes":["Casia","Roma","Asís","Venecia"],"correta":0,"explicacao":"Por eso se la llama Rita de Casia."},
          {"tipo":"vf","enunciado":"Según la tradición, una rosa floreció en invierno a pedido de Rita enferma.","correta":true,"explicacao":"Fue encontrada en el jardín de la casa donde nació."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿qué frutos aparecieron también en invierno para Rita?","opcoes":["Higos","Uvas","Manzanas","Naranjas"],"correta":0,"explicacao":"Dos higos maduros, junto con la rosa."},
          {"tipo":"vf","enunciado":"El cuerpo de Santa Rita es venerado en Casia.","correta":true,"explicacao":"En el santuario construido en su honor."},
          {"tipo":"multipla","enunciado":"¿En qué año fue canonizada Santa Rita?","opcoes":["1900","1457","1600","1990"],"correta":0,"explicacao":"El 24 de mayo de 1900."},
          {"tipo":"ordenar","enunciado":"Ordena la oración de Rita ante el Crucifijo:","blocos":["Rita reza","ante Jesús crucificado","y recibe la espina"],"explicacao":"Quiso participar de los dolores de Cristo."},
          {"tipo":"vf","enunciado":"Santa Rita vivió en el siglo XV.","correta":true,"explicacao":"Vivió aproximadamente entre 1381 y 1457."},
          {"tipo":"multipla","enunciado":"¿Qué papa canonizó a Santa Rita?","opcoes":["León XIII","Pío X","Juan Pablo II","Pío XII"],"correta":0,"explicacao":"León XIII, en el año jubilar de 1900."},
        ],
      },
    },
  },
  'sao-judas': {
    santo: "San Judas Tadeo",
    titulo: "San Judas Tadeo",
    descricao: "Apóstol de la esperanza.",
    medalha: "Esperanza",
    medalhaCompleta: "Medalla de la Esperanza",
    virtude: "Esperanza",
    licoes: {
      'judas-1': {
        titulo: "El apóstol",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿De cuántos apóstoles fue uno San Judas Tadeo?","opcoes":["Doce","Setenta","Tres","Siete"],"correta":0,"explicacao":"Forma parte del colegio de los Doce."},
          {"tipo":"vf","enunciado":"Judas Tadeo es el mismo que Judas Iscariote.","correta":false,"explicacao":"Son personas distintas; Tadeo permaneció fiel."},
          {"tipo":"multipla","enunciado":"¿Con qué apóstol se celebra a Judas Tadeo el mismo día?","opcoes":["San Simón","San Pedro","San Juan","Santo Tomás"],"correta":0,"explicacao":"Los dos se celebran juntos el 28 de octubre."},
          {"tipo":"vf","enunciado":"En la Última Cena, Judas Tadeo le hizo una pregunta a Jesús.","correta":true,"explicacao":"Juan 14,22 habla de Judas, no el Iscariote."},
          {"tipo":"multipla","enunciado":"¿Qué le preguntó a Jesús Judas, no el Iscariote, en la Última Cena?","opcoes":["Por qué se manifestaría a ellos y no al mundo","Dónde sería la cena","Cuándo volvería","Quién lo traicionaría"],"correta":0,"explicacao":"Jesús respondió que vendría a morar en quien lo ama."},
          {"tipo":"vf","enunciado":"El nombre Tadeo ayuda a distinguir a este apóstol de Judas Iscariote.","correta":true,"explicacao":"Así nadie confunde al apóstol fiel con el traidor."},
          {"tipo":"multipla","enunciado":"Según la tradición, ¿cómo murió Judas Tadeo?","opcoes":["Como mártir","De viejo en Roma","En un naufragio","En una cárcel de Jerusalén"],"correta":0,"explicacao":"Dio la vida por el Evangelio."},
          {"tipo":"ordenar","enunciado":"Ordena la pregunta de la Última Cena:","blocos":["Señor, ¿por qué","te manifestarás a nosotros","y no al mundo?"],"explicacao":"Juan 14,22."},
          {"tipo":"vf","enunciado":"Según la tradición, Judas Tadeo era pariente de Jesús.","correta":true,"explicacao":"Muchos lo consideran primo del Señor."},
          {"tipo":"multipla","enunciado":"¿Cómo llama Lucas a Judas Tadeo en la lista de los apóstoles?","opcoes":["Judas de Santiago","Judas el zelote","Judas de Belén","Judas el pescador"],"correta":0,"explicacao":"Lucas 6,16: Judas de Santiago."},
        ],
      },
      'judas-2': {
        titulo: "La carta",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Hay en el Nuevo Testamento una carta atribuida a él?","opcoes":["Sí, la Carta de Judas","No","Dos cartas","Un evangelio"],"correta":0,"explicacao":"Es una de las cartas católicas."},
          {"tipo":"ordenar","enunciado":"Ordena la invocación:","blocos":["San Judas Tadeo,","apóstol","de las causas difíciles"],"explicacao":"Una devoción muy viva en Brasil."},
          {"tipo":"multipla","enunciado":"¿Cuántos capítulos tiene la Carta de Judas?","opcoes":["Uno","Diez","Cinco","Veinte"],"correta":0,"explicacao":"Es una carta breve, de un solo capítulo."},
          {"tipo":"vf","enunciado":"La Carta de Judas pide a los cristianos que luchen por la fe.","correta":true,"explicacao":"Judas 3: combatir por la fe transmitida a los santos."},
          {"tipo":"multipla","enunciado":"¿En qué parte de la Biblia está la Carta de Judas?","opcoes":["Nuevo Testamento","Antiguo Testamento","Libro de los Salmos","Libros de los Reyes"],"correta":0,"explicacao":"Entre las cartas del Nuevo Testamento."},
          {"tipo":"vf","enunciado":"En la Biblia, la Carta de Judas va justo antes del Apocalipsis.","correta":true,"explicacao":"Es el penúltimo libro de la Biblia."},
          {"tipo":"multipla","enunciado":"¿Qué pide la Carta de Judas respecto a los que dudan?","opcoes":["Tener compasión de ellos","Expulsarlos","Ignorarlos","Castigarlos"],"correta":0,"explicacao":"Judas 22."},
          {"tipo":"ordenar","enunciado":"Ordena el consejo de la Carta:","blocos":["Manteneos","en el amor","de Dios"],"explicacao":"Judas 21."},
          {"tipo":"vf","enunciado":"La Carta de Judas termina con una alabanza a Dios.","correta":true,"explicacao":"Un hermoso himno de gloria a Dios."},
          {"tipo":"multipla","enunciado":"¿Por qué algunas cartas se llaman cartas católicas?","opcoes":["Porque se dirigen a todos los cristianos","Porque son solo para sacerdotes","Porque son solo para judíos","Porque son solo para romanos"],"correta":0,"explicacao":"Católico quiere decir universal."},
        ],
      },
      'judas-3': {
        titulo: "Devoción",
        conteudo: [
          {"tipo":"vf","enunciado":"Su fiesta se celebra el 28 de octubre.","correta":true,"explicacao":"Junto con San Simón."},
          {"tipo":"multipla","enunciado":"¿Cómo se le representa con frecuencia?","opcoes":["Con una llama sobre la cabeza","Con un ancla","Con un león","Con un libro cerrado"],"correta":0,"explicacao":"La llama recuerda Pentecostés."},
          {"tipo":"multipla","enunciado":"¿Para qué se invoca más a San Judas Tadeo?","opcoes":["Causas difíciles y desesperadas","Viajes en avión","Buenas cosechas","Victorias en el fútbol"],"correta":0,"explicacao":"Es el apóstol de la esperanza."},
          {"tipo":"vf","enunciado":"Muchos fieles visitan el Santuario de San Judas Tadeo, en São Paulo.","correta":true,"explicacao":"Es uno de los santuarios más visitados de la ciudad."},
          {"tipo":"multipla","enunciado":"¿Qué imagen suele llevar Judas Tadeo en el pecho?","opcoes":["El rostro de Jesús","Una llave","Un pez","Una campana"],"correta":0,"explicacao":"Un medallón con el rostro de Cristo."},
          {"tipo":"vf","enunciado":"La llama sobre su cabeza recuerda la venida del Espíritu Santo en Pentecostés.","correta":true,"explicacao":"Estaba con los apóstoles en el Cenáculo."},
          {"tipo":"multipla","enunciado":"¿Qué objeto aparece con él en muchas imágenes?","opcoes":["Un hacha o una alabarda","Un violín","Un ancla","Una balanza"],"correta":0,"explicacao":"Recuerda el instrumento de su martirio."},
          {"tipo":"ordenar","enunciado":"Ordena la invocación:","blocos":["San Judas Tadeo,","ruega","por nosotros"],"explicacao":"Una oración breve de confianza."},
          {"tipo":"vf","enunciado":"Tener devoción a un santo es pedirle que interceda por nosotros ante Dios.","correta":true,"explicacao":"Los santos son amigos de Dios que rezan por nosotros."},
          {"tipo":"multipla","enunciado":"¿Qué significa pedir la intercesión de un santo?","opcoes":["Pedirle que rece a Dios por nosotros","Adorarlo en lugar de Dios","Hacer magia","Intercambiar favores con él"],"correta":0,"explicacao":"Solo Dios es adorado; los santos rezan con nosotros y por nosotros."},
        ],
      },
    },
  },
  'teresa-avila': {
    santo: "Santa Teresa de Ávila",
    titulo: "Santa Teresa de Ávila",
    descricao: "Maestra de la oración y del castillo interior.",
    medalha: "Oración",
    medalhaCompleta: "Medalla de la Oración",
    virtude: "Oración",
    licoes: {
      'avila-1': {
        titulo: "La reformadora",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué orden reformó Santa Teresa?","opcoes":["Carmelitas","Benedictinos","Franciscanos","Jesuitas"],"correta":0,"explicacao":"Fundó los Carmelitas Descalzos."},
          {"tipo":"vf","enunciado":"Teresa de Ávila es Doctora de la Iglesia.","correta":true,"explicacao":"Primera mujer declarada Doctora, en 1970."},
          {"tipo":"multipla","enunciado":"¿En qué país nació Santa Teresa de Ávila?","opcoes":["España","Italia","Francia","Portugal"],"correta":0,"explicacao":"En Ávila, en España."},
          {"tipo":"vf","enunciado":"De niña, Teresa huyó con su hermano soñando con ser mártir.","correta":true,"explicacao":"Un tío los encontró en el camino y los llevó de vuelta."},
          {"tipo":"multipla","enunciado":"¿En qué año nació Santa Teresa?","opcoes":["1515","1215","1815","1415"],"correta":0,"explicacao":"El 28 de marzo de 1515."},
          {"tipo":"vf","enunciado":"Teresa fundó varios monasterios de Carmelitas Descalzas.","correta":true,"explicacao":"Fundó diecisiete monasterios por toda España."},
          {"tipo":"multipla","enunciado":"¿Cuál fue el primer monasterio reformado que fundó Teresa?","opcoes":["San José de Ávila","Montecasino","San Damián","Lisieux"],"correta":0,"explicacao":"En 1562, en Ávila."},
          {"tipo":"ordenar","enunciado":"Ordena la vida de Teresa:","blocos":["Nace en Ávila","Funda el monasterio de San José","Es proclamada Doctora de la Iglesia"],"explicacao":"De la España del siglo XVI a toda la Iglesia."},
          {"tipo":"vf","enunciado":"Teresa viajó mucho por España, aun con la salud frágil.","correta":true,"explicacao":"En carretas sencillas, por caminos difíciles."},
          {"tipo":"multipla","enunciado":"¿Cuál es la fiesta de Santa Teresa de Ávila?","opcoes":["15 de octubre","1 de octubre","19 de marzo","22 de mayo"],"correta":0,"explicacao":"Se celebra el 15 de octubre."},
        ],
      },
      'avila-2': {
        titulo: "Castillo interior",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Qué es el Castillo Interior?","opcoes":["El alma con sus moradas","Un convento","Una fortaleza real","Una ciudad"],"correta":0,"explicacao":"Siete moradas hasta la unión con Dios."},
          {"tipo":"ordenar","enunciado":"Ordena el poema de Teresa:","blocos":["Nada te turbe,","nada te espante,","solo Dios basta"],"explicacao":"El marcapáginas de Santa Teresa."},
          {"tipo":"multipla","enunciado":"¿Cuántas moradas tiene el Castillo Interior?","opcoes":["Siete","Tres","Doce","Cuarenta"],"correta":0,"explicacao":"Siete moradas hasta la unión con Dios."},
          {"tipo":"vf","enunciado":"En el Castillo Interior, Dios habita en el centro del alma.","correta":true,"explicacao":"La vida de oración es caminar hacia ese centro."},
          {"tipo":"multipla","enunciado":"Según Teresa, ¿cuál es la puerta de entrada al castillo?","opcoes":["La oración","El dinero","La fama","El estudio solo"],"correta":0,"explicacao":"La puerta para entrar en el castillo es la oración."},
          {"tipo":"vf","enunciado":"Teresa escribió el libro Camino de perfección para sus hermanas.","correta":true,"explicacao":"Una guía para la vida de oración."},
          {"tipo":"multipla","enunciado":"¿Cuál de estos libros escribió Santa Teresa?","opcoes":["Libro de la Vida","Confesiones","Suma Teológica","Filotea"],"correta":0,"explicacao":"En él cuenta su propia historia con Dios."},
          {"tipo":"ordenar","enunciado":"Ordena el final del poema:","blocos":["Quien a Dios tiene","nada le falta:","solo Dios basta"],"explicacao":"El final del famoso Nada te turbe."},
          {"tipo":"vf","enunciado":"Teresa compara el alma con un castillo hecho de diamante o de un cristal muy claro.","correta":true,"explicacao":"Una imagen de la belleza del alma creada por Dios."},
          {"tipo":"multipla","enunciado":"¿Qué enseña Teresa a buscar dentro de nosotros?","opcoes":["La presencia de Dios","El orgullo","La riqueza","El miedo"],"correta":0,"explicacao":"Dios está más cerca de lo que imaginamos."},
        ],
      },
      'avila-3': {
        titulo: "Amistad con Dios",
        conteudo: [
          {"tipo":"multipla","enunciado":"¿Cómo define Teresa la oración?","opcoes":["Tratar de amistad con quien sabemos nos ama","Recitar fórmulas","Pedir bienes","Solo guardar silencio"],"correta":0,"explicacao":"La definición clásica del Libro de la Vida."},
          {"tipo":"vf","enunciado":"Teresa tuvo como discípulo a San Juan de la Cruz.","correta":true,"explicacao":"Juntos reformaron el Carmelo."},
          {"tipo":"multipla","enunciado":"¿Qué experiencia de Teresa muestra la famosa escultura de Bernini?","opcoes":["La transverberación del corazón","Los estigmas","La levitación","La bilocación"],"correta":0,"explicacao":"Contó que un ángel le atravesó el corazón con un dardo de fuego."},
          {"tipo":"vf","enunciado":"Teresa decía que Dios también anda entre los pucheros de la cocina.","correta":true,"explicacao":"Dios está en las tareas sencillas del día a día."},
          {"tipo":"multipla","enunciado":"¿Qué frase de Teresa recuerda que Dios está en el día a día?","opcoes":["Entre los pucheros anda el Señor","Dios solo está en el templo","Dios vive lejos","A Dios no le importa el trabajo"],"correta":0,"explicacao":"Está en el Libro de las Fundaciones."},
          {"tipo":"vf","enunciado":"Teresa murió en Alba de Tormes, en España.","correta":true,"explicacao":"En 1582, durante un viaje."},
          {"tipo":"multipla","enunciado":"¿En qué año murió Teresa?","opcoes":["1582","1515","1622","1700"],"correta":0,"explicacao":"En octubre de 1582."},
          {"tipo":"ordenar","enunciado":"Ordena la definición de oración:","blocos":["La oración es tratar de amistad","con quien sabemos","nos ama"],"explicacao":"La definición del Libro de la Vida."},
          {"tipo":"vf","enunciado":"Teresa fue canonizada en 1622.","correta":true,"explicacao":"Cuarenta años después de morir."},
          {"tipo":"multipla","enunciado":"¿Con qué santos fue canonizada Teresa el mismo día?","opcoes":["Ignacio de Loyola y Francisco Javier","Francisco y Clara","Pedro y Pablo","Benito y Escolástica"],"correta":0,"explicacao":"Junto también con Isidro Labrador y Felipe Neri."},
        ],
      },
    },
  },
});
