// ============================================================
//  LUMINA SANCTI — Trilhas em inglês
// ============================================================
// Carregado só quando a pessoa escolhe English no site.
// Mesma ordem e mesma quantidade de atividades do português (trilhas.js):
// na múltipla escolha as opções ficam na mesma ordem, para "correta"
// continuar valendo; no "ordenar", os blocos já vêm na ordem certa da
// frase neste idioma. Trilha que ainda não está aqui aparece em português.

window.TRILHAS_TRADUZIDAS = window.TRILHAS_TRADUZIDAS || {};
window.TRILHAS_TRADUZIDAS.en = Object.assign(window.TRILHAS_TRADUZIDAS.en || {}, {
  'santo-francisco': {
    santo: "Saint Francis of Assisi",
    titulo: "Saint Francis of Assisi",
    descricao: "The poor man of Assisi who embraced all of creation.",
    medalha: "Poverty",
    medalhaCompleta: "Medal of Poverty",
    virtude: "Poverty",
    licoes: {
      'francisco-1': {
        titulo: "The young man of Assisi",
        conteudo: [
          {"tipo":"multipla","enunciado":"In which Italian city was Saint Francis born?","opcoes":["Assisi","Rome","Padua","Milan"],"correta":0,"explicacao":"Francis was born in Assisi, in Umbria, around 1181."},
          {"tipo":"vf","enunciado":"Before his conversion, Francis dreamed of being a knight.","correta":true,"explicacao":"He went off to war dreaming of military glory before he heard God's call."},
          {"tipo":"multipla","enunciado":"What was the profession of Francis's father, Pietro di Bernardone?","opcoes":["Cloth merchant","Blacksmith","Soldier","Farmer"],"correta":0,"explicacao":"Pietro was a rich cloth merchant from Assisi."},
          {"tipo":"vf","enunciado":"Francis was taken prisoner during a war between Assisi and Perugia.","correta":true,"explicacao":"He was a prisoner for about a year, after the battle of Collestrada, in 1202."},
          {"tipo":"multipla","enunciado":"What did Francis do when he met a leper on the road?","opcoes":["He embraced and kissed him","He ran away in fear","He called the guards","He tossed him coins from a distance"],"correta":0,"explicacao":"He overcame his own disgust: what had been bitter became sweet, as he wrote in his Testament."},
          {"tipo":"ordenar","enunciado":"Put Francis's life before his conversion in order:","blocos":["A rich young man fond of parties","A prisoner of war","The meeting with the leper"],"explicacao":"His conversion happened little by little, after prison and illness."},
          {"tipo":"vf","enunciado":"Before the bishop of Assisi, Francis gave back to his father even the clothes he was wearing.","correta":true,"explicacao":"He gave up his inheritance and said that from then on he would call only the Father in Heaven his father."},
          {"tipo":"multipla","enunciado":"What kind of life did Francis choose after his conversion?","opcoes":["Total poverty, like Jesus","The life of a nobleman","A military career","Trading with his father"],"correta":0,"explicacao":"He wanted to live the Gospel to the letter, owning nothing."},
          {"tipo":"vf","enunciado":"Francis was born into a poor family.","correta":false,"explicacao":"He was born into a rich family; poverty was his own choice, out of love for Christ."},
          {"tipo":"multipla","enunciado":"What name did Francis's mother give him at baptism?","opcoes":["Giovanni (John)","Pietro","Bernardo","Leo"],"correta":0,"explicacao":"His mother had him baptized Giovanni; his father began calling him Francesco."},
        ],
      },
      'francisco-2': {
        titulo: "Repair my Church",
        conteudo: [
          {"tipo":"multipla","enunciado":"What did the Crucifix of San Damiano ask of Francis?","opcoes":["Go and repair my Church","Build a castle","Go back to your father","Leave for Jerusalem"],"correta":0,"explicacao":"Francis first understood it as the stone building; later he realized it meant the living Church."},
          {"tipo":"ordenar","enunciado":"Put the prayer of Saint Francis in order:","blocos":["Lord, make me","an instrument","of your peace"],"explicacao":"It is the simple prayer attributed to the saint of Assisi."},
          {"tipo":"multipla","enunciado":"What did Francis do first after hearing the Crucifix?","opcoes":["He rebuilt small churches with his own hands","He founded a university","He went to Rome as an ambassador","He became a bishop"],"correta":0,"explicacao":"He carried stones and restored San Damiano and other chapels."},
          {"tipo":"vf","enunciado":"Francis sold his father's cloth to help rebuild San Damiano.","correta":true,"explicacao":"He sold cloth and a horse in Foligno, which made his father very angry."},
          {"tipo":"multipla","enunciado":"Which pope approved Francis's first rule?","opcoes":["Innocent III","Gregory the Great","Leo XIII","Pius X"],"correta":0,"explicacao":"Innocent III approved the friars' way of life around 1209."},
          {"tipo":"vf","enunciado":"Francis was ordained a priest.","correta":false,"explicacao":"Out of humility, he remained a deacon all his life."},
          {"tipo":"multipla","enunciado":"What are Francis's followers called?","opcoes":["Franciscans, or Friars Minor","Benedictines","Jesuits","Dominicans"],"correta":0,"explicacao":"The Order of Friars Minor was born with Francis."},
          {"tipo":"ordenar","enunciado":"Put the call of the Crucifix in order:","blocos":["Francis,","go and repair","my house"],"explicacao":"The sentence continues: which, as you see, is falling into ruin."},
          {"tipo":"vf","enunciado":"Francis dearly loved the little church of the Portiuncula.","correta":true,"explicacao":"It was there that the brotherhood grew, and there that he wished to die."},
          {"tipo":"multipla","enunciado":"What does Friars Minor mean?","opcoes":["Little and humble brothers","Young friars","Friars of little faith","Short friars"],"correta":0,"explicacao":"Minor because they wanted to be the last, at the service of all."},
        ],
      },
      'francisco-3': {
        titulo: "Brother Sun, Sister Moon",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which canticle by Francis praises God for his creatures?","opcoes":["The Canticle of the Creatures","The Te Deum","The Magnificat","The Hail, Holy Queen"],"correta":0,"explicacao":"The Canticle of Brother Sun praises God for the sun, the moon, water and earth."},
          {"tipo":"vf","enunciado":"Saint Francis received the stigmata on Mount La Verna.","correta":true,"explicacao":"In 1224 he received the wounds of Christ on Mount La Verna."},
          {"tipo":"multipla","enunciado":"With which fierce animal did Francis make peace in the town of Gubbio?","opcoes":["A wolf","A bear","A lion","A wild boar"],"correta":0,"explicacao":"The wolf of Gubbio stopped attacking, and the townspeople began to feed it."},
          {"tipo":"vf","enunciado":"Francis set up the first living nativity scene, in Greccio.","correta":true,"explicacao":"It was on Christmas night, so that people could see with their own eyes the humility of Bethlehem."},
          {"tipo":"multipla","enunciado":"In what year did Francis set up the nativity scene at Greccio?","opcoes":["1223","1098","1350","1500"],"correta":0,"explicacao":"At Christmas 1223, three years before his death."},
          {"tipo":"vf","enunciado":"According to tradition, Francis preached even to the birds.","correta":true,"explicacao":"It is one of the best-known scenes of his life."},
          {"tipo":"multipla","enunciado":"Among other causes, what is Francis the patron of?","opcoes":["Ecology and animals","Bankers","Soldiers","Sailors"],"correta":0,"explicacao":"John Paul II proclaimed him patron of ecology in 1979."},
          {"tipo":"ordenar","enunciado":"Put the beginning of the Canticle of the Creatures in order:","blocos":["Most High,","all-powerful,","good Lord"],"explicacao":"This is how the praise of Brother Sun begins."},
          {"tipo":"vf","enunciado":"Francis called death his sister.","correta":true,"explicacao":"In the Canticle, he praises God for Sister Bodily Death."},
          {"tipo":"multipla","enunciado":"In what year did Francis die?","opcoes":["1226","1181","1300","1450"],"correta":0,"explicacao":"He died at the Portiuncula on October 3, 1226; his feast is on the 4th."},
        ],
      },
    },
  },
  'santo-jose': {
    santo: "Saint Joseph",
    titulo: "Saint Joseph",
    descricao: "The silent guardian of the Redeemer.",
    medalha: "Faithfulness",
    medalhaCompleta: "Medal of Faithfulness",
    virtude: "Faithfulness",
    licoes: {
      'jose-1': {
        titulo: "The just man",
        conteudo: [
          {"tipo":"multipla","enunciado":"What was Saint Joseph's trade?","opcoes":["Carpenter","Fisherman","Scribe","Shepherd"],"correta":0,"explicacao":"The Gospel calls him the carpenter."},
          {"tipo":"vf","enunciado":"Not a single word of Saint Joseph is recorded in the Gospels.","correta":true,"explicacao":"Joseph is the saint of obedient silence."},
          {"tipo":"multipla","enunciado":"How does the Gospel describe Joseph?","opcoes":["A just man","A powerful king","A priest of the Temple","A prophet"],"correta":0,"explicacao":"Matthew 1:19 calls him a just man."},
          {"tipo":"vf","enunciado":"Joseph was a descendant of King David.","correta":true,"explicacao":"That is why Jesus is called the son of David."},
          {"tipo":"multipla","enunciado":"What did Joseph think of doing when he learned that Mary was expecting a child?","opcoes":["Sending her away quietly, without exposing her","Denouncing her in public","Fleeing to Egypt","Going to the high priest"],"correta":0,"explicacao":"Just and kind, he did not want to expose her to shame."},
          {"tipo":"vf","enunciado":"An angel appeared to Joseph in a dream to explain that the child came from the Holy Spirit.","correta":true,"explicacao":"This is what Matthew 1:20 tells."},
          {"tipo":"multipla","enunciado":"What name did the angel tell Joseph to give the child?","opcoes":["Jesus","Emmanuel","John","David"],"correta":0,"explicacao":"Jesus means God saves, for he would save his people from their sins."},
          {"tipo":"ordenar","enunciado":"Put the angel's words to Joseph in order:","blocos":["Joseph, son of David,","do not be afraid to take","Mary as your wife"],"explicacao":"Words from Matthew 1:20."},
          {"tipo":"vf","enunciado":"Joseph obeyed the angel and took Mary into his home.","correta":true,"explicacao":"Matthew 1:24: he did as the angel of the Lord had commanded him."},
          {"tipo":"multipla","enunciado":"In which town was Jesus born, when Joseph and Mary went to be registered in the census?","opcoes":["Bethlehem","Nazareth","Jerusalem","Capernaum"],"correta":0,"explicacao":"Bethlehem, the city of David."},
        ],
      },
      'jose-2': {
        titulo: "The flight into Egypt",
        conteudo: [
          {"tipo":"multipla","enunciado":"How was Joseph warned to flee to Egypt?","opcoes":["In a dream, by an angel","By a letter","Through Mary","Through a prophet"],"correta":0,"explicacao":"The angel of the Lord appeared to him in a dream."},
          {"tipo":"vf","enunciado":"The Holy Family fled because of Herod.","correta":true,"explicacao":"Herod ordered the killing of the boys of Bethlehem."},
          {"tipo":"multipla","enunciado":"To which country did the Holy Family flee?","opcoes":["Egypt","Greece","Persia","Italy"],"correta":0,"explicacao":"They fled to Egypt to save the child's life."},
          {"tipo":"vf","enunciado":"Joseph returned from Egypt only after Herod's death.","correta":true,"explicacao":"The angel told him: those who sought the child's life are dead."},
          {"tipo":"multipla","enunciado":"In which town did the Holy Family settle on their return?","opcoes":["Nazareth","Bethlehem","Jericho","Rome"],"correta":0,"explicacao":"They went to live in Nazareth, in Galilee."},
          {"tipo":"vf","enunciado":"During the flight, Joseph took the child and Mary by night.","correta":true,"explicacao":"Matthew 2:14: he rose by night and departed."},
          {"tipo":"vf","enunciado":"Joseph and Mary lost the child Jesus in Jerusalem when he was twelve.","correta":true,"explicacao":"Luke 2 tells that they searched for him for three days."},
          {"tipo":"multipla","enunciado":"Where did they find Jesus after three days?","opcoes":["In the Temple, among the teachers","In the market","At Elizabeth's house","In the desert"],"correta":0,"explicacao":"He was listening to the teachers of the Law and asking them questions."},
          {"tipo":"ordenar","enunciado":"Put the events in order:","blocos":["Birth in Bethlehem","Flight into Egypt","Return to Nazareth"],"explicacao":"Joseph guided the family at every step."},
          {"tipo":"multipla","enunciado":"Who, together with Mary, brought Jesus to be presented in the Temple?","opcoes":["Joseph","Zechariah","John the Baptist","Peter"],"correta":0,"explicacao":"Joseph and Mary presented him to the Lord, as the Law required."},
        ],
      },
      'jose-3': {
        titulo: "Patron of the Church",
        conteudo: [
          {"tipo":"multipla","enunciado":"Saint Joseph is the patron of what?","opcoes":["The universal Church and a happy death","Travelers","Students","Musicians"],"correta":0,"explicacao":"Pius IX declared him patron of the universal Church in 1870."},
          {"tipo":"ordenar","enunciado":"Put the invocation in order:","blocos":["Saint Joseph,","protector","of the Holy Family"],"explicacao":"Joseph watched over Jesus and Mary."},
          {"tipo":"multipla","enunciado":"On what day does the Church celebrate the solemnity of Saint Joseph?","opcoes":["March 19","December 25","August 15","November 1"],"correta":0,"explicacao":"March 19 is the solemnity of Saint Joseph, husband of Mary."},
          {"tipo":"vf","enunciado":"On May 1 we celebrate Saint Joseph the Worker.","correta":true,"explicacao":"The feast recalls the dignity of work."},
          {"tipo":"multipla","enunciado":"Which pope created the feast of Saint Joseph the Worker?","opcoes":["Pius XII","Pius IX","John XXIII","Benedict XVI"],"correta":0,"explicacao":"Pius XII instituted it in 1955."},
          {"tipo":"vf","enunciado":"Saint Joseph is invoked as patron of a happy death.","correta":true,"explicacao":"Tradition says he died with Jesus and Mary at his side."},
          {"tipo":"multipla","enunciado":"Why is Saint Joseph the patron of a happy death?","opcoes":["Tradition says he died beside Jesus and Mary","Because he was a martyr","Because he lived to be a hundred","Because he died in Rome"],"correta":0,"explicacao":"There is no more beautiful death than in the arms of Jesus and Mary."},
          {"tipo":"vf","enunciado":"Pope Francis wrote the letter With a Father's Heart, about Saint Joseph.","correta":true,"explicacao":"The letter Patris corde is from 2020."},
          {"tipo":"ordenar","enunciado":"Put the short prayer in order:","blocos":["Jesus, Mary and Joseph,","I give you","my heart and my soul"],"explicacao":"A short prayer much loved by Catholic families."},
          {"tipo":"multipla","enunciado":"According to the Gospel, what trade did Jesus learn at home?","opcoes":["Carpenter","Fisherman","Shepherd","Scribe"],"correta":0,"explicacao":"Mark 6:3 calls Jesus the carpenter."},
        ],
      },
    },
  },
  'santa-teresinha': {
    santo: "Saint Thérèse of the Child Jesus",
    titulo: "Saint Thérèse",
    descricao: "The little way of trust.",
    medalha: "Littleness",
    medalhaCompleta: "Medal of Littleness",
    virtude: "Trust",
    licoes: {
      'teresinha-1': {
        titulo: "The little flower of Lisieux",
        conteudo: [
          {"tipo":"multipla","enunciado":"In which French town was Thérèse a Carmelite?","opcoes":["Lisieux","Lourdes","Paris","Nevers"],"correta":0,"explicacao":"She entered the Carmel of Lisieux at 15."},
          {"tipo":"vf","enunciado":"Thérèse died young, at the age of 24.","correta":true,"explicacao":"She died of tuberculosis in 1897."},
          {"tipo":"multipla","enunciado":"What was Saint Thérèse's baptismal name?","opcoes":["Marie-Françoise-Thérèse Martin","Teresa Sánchez","Marie Bernarde","Jeanne Martin"],"correta":0,"explicacao":"She was born Marie-Françoise-Thérèse Martin."},
          {"tipo":"vf","enunciado":"Thérèse's parents, Louis and Zélie Martin, were also canonized.","correta":true,"explicacao":"They were proclaimed saints in 2015."},
          {"tipo":"multipla","enunciado":"In what year was Saint Thérèse born?","opcoes":["1873","1800","1920","1750"],"correta":0,"explicacao":"She was born on January 2, 1873."},
          {"tipo":"vf","enunciado":"Thérèse asked Pope Leo XIII to let her enter the Carmel early.","correta":true,"explicacao":"At an audience in Rome, in 1887, she made the request in person."},
          {"tipo":"multipla","enunciado":"How many of Thérèse's sisters also became nuns?","opcoes":["Four","None","One","Ten"],"correta":0,"explicacao":"Marie, Pauline, Léonie and Céline: all of them consecrated themselves to God."},
          {"tipo":"ordenar","enunciado":"Put Thérèse's life in order:","blocos":["Born in Alençon","Enters the Carmel of Lisieux","Dies at 24"],"explicacao":"A short life, full of love."},
          {"tipo":"vf","enunciado":"Thérèse was born in Alençon, in France.","correta":true,"explicacao":"Later the family moved to Lisieux."},
          {"tipo":"multipla","enunciado":"What religious name did Thérèse receive in the Carmel?","opcoes":["Thérèse of the Child Jesus and of the Holy Face","Teresa of Jesus","Mary of the Heart","Clare of the Cross"],"correta":0,"explicacao":"The name joins the childhood of Jesus and his Passion."},
        ],
      },
      'teresinha-2': {
        titulo: "The little way",
        conteudo: [
          {"tipo":"multipla","enunciado":"What is the little way?","opcoes":["Doing small things with great love","Doing great penances","Going on many pilgrimages","Studying theology"],"correta":0,"explicacao":"Holiness hidden in everyday life, with a child's trust."},
          {"tipo":"ordenar","enunciado":"Put Thérèse's words in order:","blocos":["My vocation","is love","in the heart of the Church"],"explicacao":"Words from Story of a Soul."},
          {"tipo":"multipla","enunciado":"To which modern invention did Thérèse compare the little way?","opcoes":["An elevator","A train","An airplane","A clock"],"correta":0,"explicacao":"The elevator that would carry her up to Heaven was the arms of Jesus."},
          {"tipo":"vf","enunciado":"For Thérèse, small sacrifices offered with love please God.","correta":true,"explicacao":"What matters is not the size of the gesture, but the love."},
          {"tipo":"multipla","enunciado":"How did Thérèse see herself before God?","opcoes":["Like a child in her Father's arms","Like a queen","Like a judge","Like a warrior"],"correta":0,"explicacao":"Spiritual childhood means trusting like a child."},
          {"tipo":"vf","enunciado":"Thérèse promised to spend her Heaven doing good on earth.","correta":true,"explicacao":"And many say they receive graces through her intercession."},
          {"tipo":"ordenar","enunciado":"Put Thérèse's promise in order:","blocos":["I want to spend","my Heaven","doing good on earth"],"explicacao":"One of the saint's most famous sayings."},
          {"tipo":"multipla","enunciado":"What kind of shower did Thérèse promise to send from Heaven?","opcoes":["A shower of roses","A shower of stars","A shower of gold","A shower of bread"],"correta":0,"explicacao":"The roses stand for the graces she obtains for us."},
          {"tipo":"vf","enunciado":"The little way requires doing extraordinary things.","correta":false,"explicacao":"Just the opposite: small things, done with great love."},
          {"tipo":"multipla","enunciado":"Which virtue is at the center of the little way?","opcoes":["Trust and love","Fear","Fame","Wealth"],"correta":0,"explicacao":"Trusting in God's merciful love."},
        ],
      },
      'teresinha-3': {
        titulo: "Doctor and missionary",
        conteudo: [
          {"tipo":"vf","enunciado":"Thérèse is patroness of the missions even though she never left her convent.","correta":true,"explicacao":"She prayed and offered sacrifices for missionaries."},
          {"tipo":"multipla","enunciado":"Which book, written by Thérèse herself, tells her life?","opcoes":["Story of a Soul","Confessions","The Interior Castle","The Imitation of Christ"],"correta":0,"explicacao":"Story of a Soul was published after her death."},
          {"tipo":"multipla","enunciado":"Which pope declared Thérèse a Doctor of the Church?","opcoes":["John Paul II","Pius X","Leo XIII","Francis"],"correta":0,"explicacao":"It was in 1997, a hundred years after her death."},
          {"tipo":"vf","enunciado":"Thérèse is patroness of the missions together with Saint Francis Xavier.","correta":true,"explicacao":"Pius XI proclaimed them patrons of the missions in 1927."},
          {"tipo":"multipla","enunciado":"In what year was Thérèse canonized?","opcoes":["1925","1897","1965","2000"],"correta":0,"explicacao":"Pius XI canonized her in 1925."},
          {"tipo":"vf","enunciado":"Thérèse prayed for missionary priests and wrote letters to them.","correta":true,"explicacao":"She called them her spiritual brothers."},
          {"tipo":"multipla","enunciado":"Which illness caused Thérèse's death?","opcoes":["Tuberculosis","Flu","Malaria","Smallpox"],"correta":0,"explicacao":"She suffered greatly, but with peace and trust."},
          {"tipo":"ordenar","enunciado":"Put Thérèse's last words in order:","blocos":["My God,","I","love you"],"explicacao":"She died looking at the crucifix, on September 30, 1897."},
          {"tipo":"vf","enunciado":"Thérèse is one of the four women Doctors of the Church.","correta":true,"explicacao":"Together with Teresa of Ávila, Catherine of Siena and Hildegard of Bingen."},
          {"tipo":"multipla","enunciado":"What is the feast day of Saint Thérèse?","opcoes":["October 1","March 19","June 13","October 4"],"correta":0,"explicacao":"It is celebrated on October 1."},
        ],
      },
    },
  },
  'santo-antonio': {
    santo: "Saint Anthony of Padua",
    titulo: "Saint Anthony of Padua",
    descricao: "The hammer of heretics and friend of the poor.",
    medalha: "Wisdom",
    medalhaCompleta: "Medal of Wisdom",
    virtude: "Wisdom",
    licoes: {
      'antonio-1': {
        titulo: "From Lisbon to Padua",
        conteudo: [
          {"tipo":"multipla","enunciado":"Where was Saint Anthony born?","opcoes":["Lisbon","Padua","Assisi","Seville"],"correta":0,"explicacao":"He was born in Lisbon, Portugal, in 1195."},
          {"tipo":"vf","enunciado":"Saint Anthony joined the Franciscan order.","correta":true,"explicacao":"He left the Augustinian canons for the Franciscans."},
          {"tipo":"multipla","enunciado":"What was Saint Anthony's baptismal name?","opcoes":["Fernando","Francisco","Pedro","Luís"],"correta":0,"explicacao":"His name was Fernando; he took the name Anthony when he became a Franciscan."},
          {"tipo":"vf","enunciado":"Anthony decided to become a Franciscan after seeing the bodies of friars martyred in Morocco.","correta":true,"explicacao":"The example of the five martyrs of 1220 moved him deeply."},
          {"tipo":"multipla","enunciado":"Where did Anthony set out as a missionary?","opcoes":["Morocco","Japan","Brazil","India"],"correta":0,"explicacao":"He wanted to preach and give his life for Christ in Africa."},
          {"tipo":"vf","enunciado":"A storm carried Anthony's ship to Sicily.","correta":true,"explicacao":"Ill, he was returning home when the ship was driven off course to Italy."},
          {"tipo":"multipla","enunciado":"Near which Italian city did Anthony die?","opcoes":["Padua","Rome","Naples","Venice"],"correta":0,"explicacao":"He died at Arcella, near Padua, in 1231."},
          {"tipo":"ordenar","enunciado":"Put Anthony's path in order:","blocos":["Born in Lisbon","Becomes a Franciscan","Dies near Padua"],"explicacao":"From Portugal to Italy, always preaching."},
          {"tipo":"vf","enunciado":"Anthony was canonized less than a year after he died.","correta":true,"explicacao":"Gregory IX canonized him in 1232."},
          {"tipo":"multipla","enunciado":"On what day is Saint Anthony celebrated?","opcoes":["June 13","June 24","June 29","December 8"],"correta":0,"explicacao":"June 13, which opens the June festivals in Brazil."},
        ],
      },
      'antonio-2': {
        titulo: "Evangelical Doctor",
        conteudo: [
          {"tipo":"multipla","enunciado":"Saint Anthony is remembered above all as...","opcoes":["A great preacher","A king","A hermit","A martyr"],"correta":0,"explicacao":"His biblical preaching earned him the title of Evangelical Doctor."},
          {"tipo":"ordenar","enunciado":"Put the popular prayer in order:","blocos":["Saint Anthony,","help me find","what I have lost"],"explicacao":"He is invoked as the saint of lost things."},
          {"tipo":"multipla","enunciado":"According to tradition, to whom did Anthony preach when people refused to listen?","opcoes":["To the fish","To the trees","To the stones","To the horses"],"correta":0,"explicacao":"In Rimini, the fish are said to have lifted their heads out of the water to listen to him."},
          {"tipo":"vf","enunciado":"Anthony was declared a Doctor of the Church.","correta":true,"explicacao":"Pius XII declared him a Doctor in 1946."},
          {"tipo":"multipla","enunciado":"What is Anthony's title as a Doctor of the Church?","opcoes":["Evangelical Doctor","Angelic Doctor","Seraphic Doctor","Doctor of Grace"],"correta":0,"explicacao":"Because of his love for the Gospel and his knowledge of it."},
          {"tipo":"vf","enunciado":"Saint Francis asked Anthony to teach theology to the friars.","correta":true,"explicacao":"In a letter, Francis allowed him to do so, asking him not to put out the spirit of prayer."},
          {"tipo":"multipla","enunciado":"What nickname did Pope Gregory IX give Anthony?","opcoes":["Ark of the Testament","Hammer of God","Lion of Judah","Light of the East"],"correta":0,"explicacao":"Because he knew the Bible almost by heart."},
          {"tipo":"ordenar","enunciado":"Put the sermon to the fish in order:","blocos":["The people would not listen,","Anthony went to the seashore","and the fish listened to him"],"explicacao":"A lesson about the hardness of the human heart."},
          {"tipo":"vf","enunciado":"Anthony knew large parts of the Bible by heart.","correta":true,"explicacao":"His preaching was woven entirely out of the Word of God."},
          {"tipo":"multipla","enunciado":"Which pope declared Anthony a Doctor of the Church?","opcoes":["Pius XII","Gregory IX","Leo XIII","John Paul II"],"correta":0,"explicacao":"Pius XII, in 1946."},
        ],
      },
      'antonio-3': {
        titulo: "Friend of the poor",
        conteudo: [
          {"tipo":"vf","enunciado":"Saint Anthony's Bread is a work of charity linked to Saint Anthony.","correta":true,"explicacao":"The devotion supports works for people in need."},
          {"tipo":"multipla","enunciado":"How is he usually depicted?","opcoes":["With the Child Jesus and a lily","With a sword","With a crown","With a lion"],"correta":0,"explicacao":"The lily symbolizes purity; the Child recalls his vision."},
          {"tipo":"multipla","enunciado":"Why is Saint Anthony called the matchmaker saint in Brazil?","opcoes":["Because of the popular devotion of asking him for a good marriage","Because he got married","Because he celebrated the weddings of kings","Because he was a judge"],"correta":0,"explicacao":"It is a devotion of the people, very much alive in the June festivals."},
          {"tipo":"vf","enunciado":"The lily in images of Saint Anthony symbolizes purity.","correta":true,"explicacao":"It recalls his chaste life and his pure heart."},
          {"tipo":"multipla","enunciado":"Besides a good marriage, what does popular devotion most often ask of Saint Anthony?","opcoes":["To find lost objects","To win the lottery","To win wars","To become famous"],"correta":0,"explicacao":"He is invoked as the saint of lost things."},
          {"tipo":"vf","enunciado":"Saint Anthony is widely celebrated in Brazil's June festivals.","correta":true,"explicacao":"Together with Saint John and Saint Peter."},
          {"tipo":"multipla","enunciado":"In which month are Saint Anthony's festivities held in Brazil?","opcoes":["June","December","February","April"],"correta":0,"explicacao":"On June 13."},
          {"tipo":"ordenar","enunciado":"Put the June saints in order of their feast days:","blocos":["Saint Anthony (13)","Saint John (24)","Saint Peter (29)"],"explicacao":"The three great saints of June."},
          {"tipo":"vf","enunciado":"The Child Jesus in Anthony's arms recalls a vision he had.","correta":true,"explicacao":"According to tradition, the Child appeared to him while he was praying."},
          {"tipo":"multipla","enunciado":"In what year did Anthony die?","opcoes":["1231","1195","1300","1500"],"correta":0,"explicacao":"On June 13, 1231, at about 36 years of age."},
        ],
      },
    },
  },
  'padre-pio': {
    santo: "Saint Padre Pio",
    titulo: "Saint Padre Pio",
    descricao: "Pray, hope and don't worry.",
    medalha: "Penance",
    medalhaCompleta: "Medal of Penance",
    virtude: "Penance",
    licoes: {
      'pio-1': {
        titulo: "The friar of Pietrelcina",
        conteudo: [
          {"tipo":"multipla","enunciado":"To which order did Padre Pio belong?","opcoes":["Capuchins","Dominicans","Jesuits","Benedictines"],"correta":0,"explicacao":"He was a Capuchin friar in San Giovanni Rotondo."},
          {"tipo":"vf","enunciado":"Padre Pio bore the stigmata for about 50 years.","correta":true,"explicacao":"He received the wounds in 1918."},
          {"tipo":"multipla","enunciado":"What was Padre Pio's baptismal name?","opcoes":["Francesco Forgione","Giovanni Bosco","Pietro Martini","Angelo Roncalli"],"correta":0,"explicacao":"He was born Francesco Forgione, in 1887."},
          {"tipo":"vf","enunciado":"Padre Pio was born in Pietrelcina, in southern Italy.","correta":true,"explicacao":"A small town, in a family of farmers."},
          {"tipo":"multipla","enunciado":"In what year did Padre Pio receive the visible stigmata?","opcoes":["1918","1887","1950","1968"],"correta":0,"explicacao":"On September 20, 1918."},
          {"tipo":"vf","enunciado":"Padre Pio lived much of his life in San Giovanni Rotondo.","correta":true,"explicacao":"He stayed there for more than fifty years."},
          {"tipo":"multipla","enunciado":"In what year did Padre Pio die?","opcoes":["1968","1918","1999","2002"],"correta":0,"explicacao":"He died on September 23, 1968."},
          {"tipo":"ordenar","enunciado":"Put Padre Pio's life in order:","blocos":["Born in Pietrelcina","Receives the stigmata","Is canonized"],"explicacao":"From a simple friar to a saint of the whole world."},
          {"tipo":"vf","enunciado":"Padre Pio was never ordained a priest.","correta":false,"explicacao":"He was ordained a priest in 1910."},
          {"tipo":"multipla","enunciado":"What is the feast day of Saint Padre Pio?","opcoes":["September 23","October 4","May 25","November 2"],"correta":0,"explicacao":"The day he went to Heaven."},
        ],
      },
      'pio-2': {
        titulo: "The confessional",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which ministry marked Padre Pio's life?","opcoes":["Confession","University teaching","Diplomacy","Music"],"correta":0,"explicacao":"He spent hours hearing the confessions of pilgrims."},
          {"tipo":"ordenar","enunciado":"Put the saint's advice in order:","blocos":["Pray,","hope","and don't worry"],"explicacao":"A famous saying of Padre Pio."},
          {"tipo":"multipla","enunciado":"What did Padre Pio call the Rosary?","opcoes":["The weapon","The ornament","The habit","The amulet"],"correta":0,"explicacao":"For him, the Rosary was the Christian's weapon."},
          {"tipo":"vf","enunciado":"Padre Pio spent many hours a day hearing confessions.","correta":true,"explicacao":"Sometimes more than ten hours in a single day."},
          {"tipo":"multipla","enunciado":"Which groups did Padre Pio encourage around the world?","opcoes":["Prayer Groups","Book clubs","Orders of knighthood","Sports teams"],"correta":0,"explicacao":"Padre Pio Prayer Groups still exist today in many countries."},
          {"tipo":"vf","enunciado":"People came from many countries to go to confession with Padre Pio.","correta":true,"explicacao":"The lines at his confessional were enormous."},
          {"tipo":"multipla","enunciado":"According to Padre Pio, what is prayer?","opcoes":["The best weapon we have","A waste of time","Something only for priests","Something only for Sundays"],"correta":0,"explicacao":"He said prayer is the key that opens God's heart."},
          {"tipo":"ordenar","enunciado":"Put Padre Pio's saying in order:","blocos":["Prayer","is the best weapon","we have"],"explicacao":"Advice he repeated many times."},
          {"tipo":"vf","enunciado":"Padre Pio celebrated Mass with great devotion.","correta":true,"explicacao":"Many people were moved just by attending his Mass."},
          {"tipo":"multipla","enunciado":"Which sacrament did Padre Pio celebrate most in the confessional?","opcoes":["Confession","Matrimony","Confirmation","Holy Orders"],"correta":0,"explicacao":"Confession, the sacrament of God's mercy."},
        ],
      },
      'pio-3': {
        titulo: "House for the Relief of Suffering",
        conteudo: [
          {"tipo":"vf","enunciado":"Padre Pio founded a hospital for the sick.","correta":true,"explicacao":"The Casa Sollievo della Sofferenza, the House for the Relief of Suffering."},
          {"tipo":"multipla","enunciado":"In what year was he canonized?","opcoes":["2002","1987","1968","2015"],"correta":0,"explicacao":"John Paul II canonized him in 2002."},
          {"tipo":"multipla","enunciado":"Which pope canonized Padre Pio?","opcoes":["John Paul II","Paul VI","Benedict XVI","Francis"],"correta":0,"explicacao":"John Paul II, in 2002."},
          {"tipo":"vf","enunciado":"The House for the Relief of Suffering was opened in 1956.","correta":true,"explicacao":"The hospital was inaugurated on May 5, 1956."},
          {"tipo":"multipla","enunciado":"Where is the House for the Relief of Suffering?","opcoes":["San Giovanni Rotondo","Rome","Assisi","Padua"],"correta":0,"explicacao":"Next to the friary where Padre Pio lived."},
          {"tipo":"vf","enunciado":"Karol Wojtyła, the future John Paul II, met Padre Pio when he was a young priest.","correta":true,"explicacao":"It was in 1947, while Karol was studying in Rome."},
          {"tipo":"multipla","enunciado":"In what year was Padre Pio beatified?","opcoes":["1999","1968","1950","2010"],"correta":0,"explicacao":"Beatified in 1999 and canonized in 2002."},
          {"tipo":"ordenar","enunciado":"Put the steps to the altar in order:","blocos":["Death in 1968","Beatification in 1999","Canonization in 2002"],"explicacao":"Thirty-four years after his death, he was proclaimed a saint."},
          {"tipo":"vf","enunciado":"Pilgrims can visit Padre Pio's body in San Giovanni Rotondo.","correta":true,"explicacao":"The shrine welcomes millions of pilgrims."},
          {"tipo":"multipla","enunciado":"Which work of charity did Padre Pio found?","opcoes":["A hospital","A university","A bank","A newspaper"],"correta":0,"explicacao":"To care for the sick with love and with the best medicine."},
        ],
      },
    },
  },
  'nossa-senhora': {
    santo: "Our Lady",
    titulo: "Our Lady",
    descricao: "The yes that opened Heaven.",
    medalha: "Humility",
    medalhaCompleta: "Medal of Humility",
    virtude: "Humility",
    licoes: {
      'maria-1': {
        titulo: "The Annunciation",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which angel brought the announcement to Mary?","opcoes":["Gabriel","Michael","Raphael","Uriel"],"correta":0,"explicacao":"The archangel Gabriel, in Nazareth."},
          {"tipo":"ordenar","enunciado":"Put Mary's answer in order:","blocos":["Behold the handmaid of the Lord;","be it done unto me","according to your word"],"explicacao":"Mary's fiat, her yes to God."},
          {"tipo":"multipla","enunciado":"In which town did the Annunciation take place?","opcoes":["Nazareth","Bethlehem","Jerusalem","Cana"],"correta":0,"explicacao":"In a small town in Galilee."},
          {"tipo":"vf","enunciado":"The angel greeted Mary, saying: Hail, full of grace, the Lord is with you.","correta":true,"explicacao":"Luke 1:28."},
          {"tipo":"multipla","enunciado":"What name did the angel say Mary would give the child?","opcoes":["Jesus","John","David","Moses"],"correta":0,"explicacao":"Luke 1:31."},
          {"tipo":"vf","enunciado":"Mary asked the angel how this would happen.","correta":true,"explicacao":"Not out of lack of faith, but to understand and to answer from the heart."},
          {"tipo":"multipla","enunciado":"Which relative of Mary was also expecting a child?","opcoes":["Elizabeth","Anne","Martha","Sarah"],"correta":0,"explicacao":"Elizabeth, who was already old, was expecting John the Baptist."},
          {"tipo":"multipla","enunciado":"On what day does the Church celebrate the Annunciation?","opcoes":["March 25","December 25","August 15","September 8"],"correta":0,"explicacao":"Nine months before Christmas."},
          {"tipo":"vf","enunciado":"The angel told Mary that nothing is impossible for God.","correta":true,"explicacao":"Luke 1:37."},
          {"tipo":"ordenar","enunciado":"Put the angel's greeting in order:","blocos":["Hail Mary,","full of grace,","the Lord is with thee"],"explicacao":"It is the beginning of the Hail Mary."},
        ],
      },
      'maria-2': {
        titulo: "The Magnificat",
        conteudo: [
          {"tipo":"multipla","enunciado":"Where did Mary proclaim the Magnificat?","opcoes":["At her visit to Elizabeth","In the Temple","In Bethlehem","On Calvary"],"correta":0,"explicacao":"At the Visitation to her cousin Elizabeth."},
          {"tipo":"vf","enunciado":"The Magnificat exalts the humble and casts down the mighty.","correta":true,"explicacao":"God casts the mighty from their thrones and lifts up the lowly."},
          {"tipo":"multipla","enunciado":"How does Mary's canticle begin?","opcoes":["My soul magnifies the Lord","Our Father, who art in heaven","Glory to God in the highest","I believe in God, the Father"],"correta":0,"explicacao":"In Latin, Magnificat anima mea Dominum."},
          {"tipo":"vf","enunciado":"On hearing Mary's greeting, the child leaped in Elizabeth's womb.","correta":true,"explicacao":"John the Baptist was already rejoicing at the coming of Jesus."},
          {"tipo":"multipla","enunciado":"Which son was Elizabeth expecting?","opcoes":["John the Baptist","James","Andrew","Peter"],"correta":0,"explicacao":"The forerunner who would prepare the way for Jesus."},
          {"tipo":"vf","enunciado":"Elizabeth called Mary blessed among women.","correta":true,"explicacao":"Luke 1:42."},
          {"tipo":"ordenar","enunciado":"Put the beginning of the Magnificat in order:","blocos":["My soul","magnifies","the Lord"],"explicacao":"Mary praises God for the wonders he has done in her."},
          {"tipo":"multipla","enunciado":"How long did Mary stay with Elizabeth?","opcoes":["About three months","One day","Ten years","One week"],"correta":0,"explicacao":"Luke 1:56."},
          {"tipo":"vf","enunciado":"In the Magnificat, Mary says that all generations will call her blessed.","correta":true,"explicacao":"Luke 1:48."},
          {"tipo":"multipla","enunciado":"On what day is the Visitation of Our Lady celebrated?","opcoes":["May 31","February 2","January 1","October 12"],"correta":0,"explicacao":"Closing the month of May, which is dedicated to Mary."},
        ],
      },
      'maria-3': {
        titulo: "Mother of the Church",
        conteudo: [
          {"tipo":"multipla","enunciado":"Whom did Jesus entrust to Mary from the cross?","opcoes":["The beloved disciple","Peter","James","Nicodemus"],"correta":0,"explicacao":"Behold, your mother, he said to John."},
          {"tipo":"vf","enunciado":"The Rosary meditates on mysteries of the life of Jesus and Mary.","correta":true,"explicacao":"There are four sets of mysteries."},
          {"tipo":"multipla","enunciado":"Who is the patroness of Brazil?","opcoes":["Our Lady Aparecida","Our Lady of Fátima","Our Lady of Lourdes","Our Lady of Guadalupe"],"correta":0,"explicacao":"Her image was found by fishermen in the Paraíba do Sul river."},
          {"tipo":"vf","enunciado":"The feast of Our Lady Aparecida is on October 12.","correta":true,"explicacao":"It is a national holiday in Brazil."},
          {"tipo":"multipla","enunciado":"At Fátima, to how many little shepherds did Our Lady appear?","opcoes":["Three","One","Twelve","Seven"],"correta":0,"explicacao":"Lúcia, Francisco and Jacinta, in 1917."},
          {"tipo":"vf","enunciado":"The Assumption teaches that Mary was taken up to Heaven body and soul.","correta":true,"explicacao":"It is a dogma proclaimed by Pius XII in 1950."},
          {"tipo":"multipla","enunciado":"On what day is the Assumption of Our Lady celebrated?","opcoes":["August 15","December 8","March 25","May 1"],"correta":0,"explicacao":"In Brazil, the solemnity is usually moved to the following Sunday."},
          {"tipo":"ordenar","enunciado":"Put Mary's words at Cana in order:","blocos":["Do","whatever","he tells you"],"explicacao":"John 2:5: Mary's advice for all of us."},
          {"tipo":"vf","enunciado":"At Lourdes, Our Lady appeared to Saint Bernadette.","correta":true,"explicacao":"There were eighteen apparitions, in 1858."},
          {"tipo":"multipla","enunciado":"What do we celebrate on December 8?","opcoes":["The Immaculate Conception","The Assumption","The Annunciation","The Birth of Mary"],"correta":0,"explicacao":"Mary was preserved from original sin from the moment of her conception."},
        ],
      },
    },
  },
  'sao-bento': {
    santo: "Saint Benedict",
    titulo: "Saint Benedict",
    descricao: "Ora et labora: order for life.",
    medalha: "Order",
    medalhaCompleta: "Medal of Order",
    virtude: "Discipline",
    licoes: {
      'bento-1': {
        titulo: "Father of monasticism",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which motto sums up the Benedictine rule?","opcoes":["Ora et labora","Carpe diem","Sola fide","Veni vidi vici"],"correta":0,"explicacao":"Pray and work."},
          {"tipo":"vf","enunciado":"Saint Benedict is the patron of Europe.","correta":true,"explicacao":"Proclaimed by Paul VI in 1964."},
          {"tipo":"multipla","enunciado":"In which Italian town was Saint Benedict born?","opcoes":["Nursia","Assisi","Milan","Naples"],"correta":0,"explicacao":"Nursia, today Norcia, in Umbria."},
          {"tipo":"vf","enunciado":"According to tradition, Benedict had a twin sister, Saint Scholastica.","correta":true,"explicacao":"She too consecrated herself to God."},
          {"tipo":"multipla","enunciado":"Where did Benedict live as a hermit, in a cave?","opcoes":["Subiaco","Cluny","Lisbon","Paris"],"correta":0,"explicacao":"He lived for three years in a cave near Subiaco."},
          {"tipo":"vf","enunciado":"Benedict left his studies in Rome to seek God in solitude.","correta":true,"explicacao":"He did not want to lose himself in the disorderly life of the city."},
          {"tipo":"multipla","enunciado":"In which century did Saint Benedict live?","opcoes":["The 6th century","The 13th century","The 1st century","The 19th century"],"correta":0,"explicacao":"He lived from about 480 to 547."},
          {"tipo":"ordenar","enunciado":"Put Benedict's life in order:","blocos":["Studies in Rome","Hermit at Subiaco","Monastery of Monte Cassino"],"explicacao":"From solitude, a great family of monks was born."},
          {"tipo":"vf","enunciado":"Saint Benedict's feast is on July 11.","correta":true,"explicacao":"It is celebrated on July 11."},
          {"tipo":"multipla","enunciado":"Which pope proclaimed Saint Benedict patron of Europe?","opcoes":["Paul VI","Pius IX","John XXIII","Gregory the Great"],"correta":0,"explicacao":"Paul VI, in 1964."},
        ],
      },
      'bento-2': {
        titulo: "The Rule",
        conteudo: [
          {"tipo":"multipla","enunciado":"What does the Rule of Saint Benedict organize?","opcoes":["The life of monks","The civil calendar","The Eastern liturgy","The crusades"],"correta":0,"explicacao":"Prayer, work, reading and hospitality."},
          {"tipo":"ordenar","enunciado":"Put the Benedictine maxim in order:","blocos":["That in all things","God may be","glorified"],"explicacao":"Ut in omnibus glorificetur Deus."},
          {"tipo":"multipla","enunciado":"What is the first word of the Rule of Saint Benedict?","opcoes":["Listen","Pray","Work","Be silent"],"correta":0,"explicacao":"The Rule begins: Listen, my son."},
          {"tipo":"vf","enunciado":"The Rule of Saint Benedict is still used today by many monasteries.","correta":true,"explicacao":"For almost 1,500 years it has guided monks and nuns."},
          {"tipo":"multipla","enunciado":"According to the Rule, how should guests be received?","opcoes":["As Christ himself","With suspicion","Only if they pay","Only on Sundays"],"correta":0,"explicacao":"Hospitality is a sign of love for Christ."},
          {"tipo":"vf","enunciado":"The Rule teaches that nothing should come before prayer, the Work of God.","correta":true,"explicacao":"Let nothing be preferred to the Work of God, says chapter 43."},
          {"tipo":"multipla","enunciado":"What is the superior of a Benedictine monastery called?","opcoes":["Abbot","Cardinal","Bishop","Deacon"],"correta":0,"explicacao":"Abbot comes from abba, father."},
          {"tipo":"ordenar","enunciado":"Put the beginning of the Rule in order:","blocos":["Listen, my son,","to the precepts","of the master"],"explicacao":"An invitation to listen with the heart."},
          {"tipo":"vf","enunciado":"Benedictine monks take a vow of stability, binding themselves to their monastery.","correta":true,"explicacao":"In this way they learn to seek God in the same place, with the same community."},
          {"tipo":"multipla","enunciado":"How many chapters does the Rule of Saint Benedict have?","opcoes":["73","10","150","365"],"correta":0,"explicacao":"There are 73 chapters, with a prologue."},
        ],
      },
      'bento-3': {
        titulo: "The Saint Benedict medal",
        conteudo: [
          {"tipo":"vf","enunciado":"The Saint Benedict medal carries a short prayer of exorcism.","correta":true,"explicacao":"The letters stand for Latin phrases of protection."},
          {"tipo":"multipla","enunciado":"Where did Saint Benedict found his main monastery?","opcoes":["Monte Cassino","Cluny","Assisi","New Subiaco"],"correta":0,"explicacao":"Monte Cassino, in Italy."},
          {"tipo":"multipla","enunciado":"What do the letters C.S.P.B. on the medal mean?","opcoes":["Cross of the Holy Father Benedict","Christ Saves Through Baptism","Charity, Sanctity, Peace and Blessing","Church of Saints Peter and Benedict"],"correta":0,"explicacao":"From the Latin Crux Sancti Patris Benedicti."},
          {"tipo":"vf","enunciado":"The medal bears the Latin phrase Vade retro satana: begone, Satan.","correta":true,"explicacao":"It is an ancient prayer against evil."},
          {"tipo":"multipla","enunciado":"According to tradition, how did Benedict escape a poisoned cup?","opcoes":["He made the sign of the cross and the cup shattered","He threw the cup into the river","He drank it and nothing happened","An angel took the cup away"],"correta":0,"explicacao":"The story is told by Saint Gregory the Great."},
          {"tipo":"vf","enunciado":"The raven in images of Saint Benedict recalls the story of the poisoned bread.","correta":true,"explicacao":"The raven carried away the bread that someone had tried to give him."},
          {"tipo":"multipla","enunciado":"Who wrote the life of Saint Benedict in the Dialogues?","opcoes":["Saint Gregory the Great","Saint Augustine","Saint Jerome","Saint Thomas Aquinas"],"correta":0,"explicacao":"Pope Gregory the Great, in the 6th century."},
          {"tipo":"ordenar","enunciado":"Put the phrase engraved on the cross of the medal in order:","blocos":["May the holy cross","be my","light"],"explicacao":"In Latin: Crux sacra sit mihi lux."},
          {"tipo":"vf","enunciado":"The Saint Benedict medal is a sacramental of the Church.","correta":true,"explicacao":"Sacramentals help us live the faith, but they are not amulets."},
          {"tipo":"multipla","enunciado":"What is a sacramental like the medal for?","opcoes":["To remember God and ask for his protection","To have luck at gambling","To predict the future","To get rich"],"correta":0,"explicacao":"It leads us to pray and to trust in God."},
        ],
      },
    },
  },
  'santa-clara': {
    santo: "Saint Clare of Assisi",
    titulo: "Saint Clare of Assisi",
    descricao: "The light that chose what is essential.",
    medalha: "Purity",
    medalhaCompleta: "Medal of Purity",
    virtude: "Purity",
    licoes: {
      'clara-1': {
        titulo: "The escape from Assisi",
        conteudo: [
          {"tipo":"multipla","enunciado":"Who helped Clare embrace religious life?","opcoes":["Saint Francis","Saint Benedict","Saint Anthony","Saint Dominic"],"correta":0,"explicacao":"Francis welcomed her at the Portiuncula."},
          {"tipo":"vf","enunciado":"Clare founded the order of the Poor Clares.","correta":true,"explicacao":"The Poor Ladies of San Damiano."},
          {"tipo":"multipla","enunciado":"What kind of family did Clare come from?","opcoes":["Noble and rich","Poor peasants","Fishermen","Soldiers"],"correta":0,"explicacao":"She left a life of comfort to follow the poor Christ."},
          {"tipo":"vf","enunciado":"Clare ran away from home on the night of Palm Sunday to follow Christ.","correta":true,"explicacao":"It was in 1212, when she was 18."},
          {"tipo":"multipla","enunciado":"In what year did Clare leave everything to follow Christ?","opcoes":["1212","1181","1300","1500"],"correta":0,"explicacao":"In Holy Week of 1212."},
          {"tipo":"vf","enunciado":"Francis cut Clare's hair as a sign of consecration.","correta":true,"explicacao":"It happened at the Portiuncula, that same night."},
          {"tipo":"multipla","enunciado":"Which of Clare's sisters also followed her into religious life?","opcoes":["Saint Agnes of Assisi","Saint Monica","Saint Rita","Saint Anne"],"correta":0,"explicacao":"Agnes followed her a few days later."},
          {"tipo":"ordenar","enunciado":"Put the night of Clare's escape in order:","blocos":["She leaves home at night","She meets Francis at the Portiuncula","She consecrates herself to God"],"explicacao":"A brave decision, made out of love for Jesus."},
          {"tipo":"vf","enunciado":"Clare lived for more than 40 years at San Damiano.","correta":true,"explicacao":"From 1212 until her death, in 1253."},
          {"tipo":"multipla","enunciado":"What were Clare's first sisters called?","opcoes":["The Poor Ladies","The Sisters of Charity","The Carmelites","The Benedictines"],"correta":0,"explicacao":"The Poor Ladies of San Damiano."},
        ],
      },
      'clara-2': {
        titulo: "The Eucharist that protects",
        conteudo: [
          {"tipo":"multipla","enunciado":"With what is Clare said to have driven invaders away from the convent?","opcoes":["The Blessed Sacrament","A sword","An army","A new wall"],"correta":0,"explicacao":"She raised the monstrance before the soldiers."},
          {"tipo":"ordenar","enunciado":"Put Clare's advice in order:","blocos":["Gaze upon him,","consider him,","contemplate him"],"explicacao":"From her letter to Saint Agnes of Prague."},
          {"tipo":"multipla","enunciado":"Who were the soldiers who attacked Clare's convent?","opcoes":["Saracens in the emperor's service","Vikings","Ancient Romans","French knights"],"correta":0,"explicacao":"Saracen soldiers in the service of Frederick II, around 1240."},
          {"tipo":"vf","enunciado":"Even though she was ill, Clare faced the invaders with the Eucharist.","correta":true,"explicacao":"She trusted in Jesus present in the Blessed Sacrament."},
          {"tipo":"multipla","enunciado":"With whom did Clare exchange letters full of spiritual advice?","opcoes":["Saint Agnes of Prague","Saint Teresa of Ávila","Saint Monica","Saint Joan of Arc"],"correta":0,"explicacao":"Agnes, a princess who also chose poverty."},
          {"tipo":"vf","enunciado":"Clare was the first woman to write a rule of religious life approved by the Pope.","correta":true,"explicacao":"A rule centered on poverty and prayer."},
          {"tipo":"multipla","enunciado":"What privilege did Clare defend all her life?","opcoes":["The privilege of poverty","The privilege of wealth","The privilege of traveling","The privilege of governing"],"correta":0,"explicacao":"The right to live without possessions, trusting in God alone."},
          {"tipo":"ordenar","enunciado":"Put the defense of the convent in order:","blocos":["Soldiers surround the monastery","Clare raises the Blessed Sacrament","The invaders flee"],"explicacao":"A victory of faith, not of weapons."},
          {"tipo":"vf","enunciado":"Clare's rule was approved shortly before her death.","correta":true,"explicacao":"It was approved in 1253, two days before she died."},
          {"tipo":"multipla","enunciado":"In what year did Saint Clare die?","opcoes":["1253","1226","1300","1212"],"correta":0,"explicacao":"On August 11, 1253."},
        ],
      },
      'clara-3': {
        titulo: "Patroness",
        conteudo: [
          {"tipo":"vf","enunciado":"Saint Clare is the patroness of television.","correta":true,"explicacao":"Because, while she was ill, she saw the Mass from a distance."},
          {"tipo":"multipla","enunciado":"What was Clare's treasure?","opcoes":["Gospel poverty","Gold","Land","Books"],"correta":0,"explicacao":"She fought for the privilege of poverty."},
          {"tipo":"multipla","enunciado":"Which pope proclaimed Saint Clare patroness of television?","opcoes":["Pius XII","Pius IX","Leo XIII","John Paul II"],"correta":0,"explicacao":"Pius XII, in 1958."},
          {"tipo":"vf","enunciado":"Saint Clare is celebrated on August 11.","correta":true,"explicacao":"The day of her death."},
          {"tipo":"multipla","enunciado":"What does the name Clare bring to mind?","opcoes":["Light and brightness","Strength","Wealth","Silence"],"correta":0,"explicacao":"A life that lit up many others."},
          {"tipo":"vf","enunciado":"Clare was canonized only two years after her death.","correta":true,"explicacao":"She was canonized in 1255."},
          {"tipo":"multipla","enunciado":"What is the order founded by Clare called?","opcoes":["The Order of Saint Clare, the Poor Clares","The Order of Preachers","The Society of Jesus","The Order of Saint Benedict"],"correta":0,"explicacao":"The Poor Clares are now all over the world."},
          {"tipo":"ordenar","enunciado":"Put Clare's life in order:","blocos":["She leaves her rich family","She lives at San Damiano","She is proclaimed a saint"],"explicacao":"Poverty, prayer and joy."},
          {"tipo":"vf","enunciado":"Clare and Francis were great friends in the faith.","correta":true,"explicacao":"A holy friendship, wholly turned toward God."},
          {"tipo":"multipla","enunciado":"What did Clare see as the greatest treasure?","opcoes":["Jesus, poor and crucified","The family jewels","Titles of nobility","The family lands"],"correta":0,"explicacao":"For her, whoever has Jesus has everything."},
        ],
      },
    },
  },
  'joao-paulo-ii': {
    santo: "Saint John Paul II",
    titulo: "Saint John Paul II",
    descricao: "Be not afraid!",
    medalha: "Courage",
    medalhaCompleta: "Medal of Courage",
    virtude: "Courage",
    licoes: {
      'jpii-1': {
        titulo: "The Polish pope",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which country did John Paul II come from?","opcoes":["Poland","Italy","Germany","Argentina"],"correta":0,"explicacao":"Karol Wojtyła was born in Wadowice."},
          {"tipo":"ordenar","enunciado":"Put the invitation from the start of his pontificate in order:","blocos":["Be not afraid!","Open the doors","to Christ"],"explicacao":"From his homily of 1978."},
          {"tipo":"multipla","enunciado":"What was John Paul II's baptismal name?","opcoes":["Karol Wojtyła","Joseph Ratzinger","Angelo Roncalli","Giovanni Montini"],"correta":0,"explicacao":"Karol Józef Wojtyła."},
          {"tipo":"vf","enunciado":"During the war, Karol worked in a quarry and in a factory.","correta":true,"explicacao":"He came to know the life of workers up close."},
          {"tipo":"multipla","enunciado":"In what year was he elected pope?","opcoes":["1978","1958","2005","1963"],"correta":0,"explicacao":"On October 16, 1978."},
          {"tipo":"vf","enunciado":"Karol loved theater and sports such as skiing and canoeing.","correta":true,"explicacao":"He was an actor in his youth and always loved nature."},
          {"tipo":"multipla","enunciado":"What was his hometown?","opcoes":["Wadowice","Kraków","Warsaw","Rome"],"correta":0,"explicacao":"He was born in Wadowice, in 1920."},
          {"tipo":"ordenar","enunciado":"Put Karol's life in order:","blocos":["Born in Wadowice","Archbishop of Kraków","Pope in 1978"],"explicacao":"From Poland to the whole world."},
          {"tipo":"vf","enunciado":"His pontificate was one of the longest in history, almost 27 years.","correta":true,"explicacao":"From 1978 to 2005."},
          {"tipo":"multipla","enunciado":"In what year did John Paul II die?","opcoes":["2005","1999","2010","2014"],"correta":0,"explicacao":"On April 2, 2005, the eve of Divine Mercy Sunday."},
        ],
      },
      'jpii-2': {
        titulo: "Young people",
        conteudo: [
          {"tipo":"vf","enunciado":"John Paul II created World Youth Day.","correta":true,"explicacao":"The first international World Youth Day was in 1987."},
          {"tipo":"multipla","enunciado":"Which devotion did he spread together with Saint Faustina?","opcoes":["The Divine Mercy","The Scapular","The Stations of the Cross","The Christmas Novena"],"correta":0,"explicacao":"He instituted Divine Mercy Sunday."},
          {"tipo":"multipla","enunciado":"Which Polish saint, linked to the Divine Mercy, did he canonize?","opcoes":["Saint Faustina Kowalska","Saint Thérèse","Saint Edith Stein","Saint Hedwig"],"correta":0,"explicacao":"She was canonized in the year 2000."},
          {"tipo":"vf","enunciado":"John Paul II visited Brazil more than once.","correta":true,"explicacao":"He was in Brazil in 1980, 1991 and 1997."},
          {"tipo":"multipla","enunciado":"How many times did John Paul II come to Brazil?","opcoes":["Three","One","Ten","None"],"correta":0,"explicacao":"Three apostolic journeys."},
          {"tipo":"vf","enunciado":"He called young people watchmen of the morning.","correta":true,"explicacao":"At World Youth Day in the year 2000, in Rome."},
          {"tipo":"multipla","enunciado":"In what year was Divine Mercy Sunday instituted?","opcoes":["2000","1978","1987","2005"],"correta":0,"explicacao":"On the same day as Saint Faustina's canonization."},
          {"tipo":"ordenar","enunciado":"Put his words to young people in order:","blocos":["You are","the hope","of the Church"],"explicacao":"He trusted young people very much."},
          {"tipo":"vf","enunciado":"John Paul II canonized many saints, showing that holiness is possible today.","correta":true,"explicacao":"He canonized hundreds of saints from every continent."},
          {"tipo":"multipla","enunciado":"How is his teaching on human love known?","opcoes":["Theology of the Body","Summa Theologica","Confessions","The Imitation of Christ"],"correta":0,"explicacao":"A series of catecheses given between 1979 and 1984."},
        ],
      },
      'jpii-3': {
        titulo: "Forgiveness and witness",
        conteudo: [
          {"tipo":"vf","enunciado":"He publicly forgave the man who tried to kill him.","correta":true,"explicacao":"He visited Ali Ağca in prison."},
          {"tipo":"multipla","enunciado":"Which mysteries of the Rosary did he add?","opcoes":["The Luminous","The Glorious","The Sorrowful","The Joyful"],"correta":0,"explicacao":"Proposed in 2002."},
          {"tipo":"multipla","enunciado":"In what year was John Paul II attacked in Saint Peter's Square?","opcoes":["1981","1978","1995","2001"],"correta":0,"explicacao":"On May 13, 1981."},
          {"tipo":"vf","enunciado":"The attack took place on May 13, the feast of Our Lady of Fátima.","correta":true,"explicacao":"He saw in this a sign of Mary's protection."},
          {"tipo":"multipla","enunciado":"To whom did the Pope attribute his survival?","opcoes":["Our Lady of Fátima","Only the doctors","Luck","A bodyguard"],"correta":0,"explicacao":"He said that one hand fired, and another guided the bullet."},
          {"tipo":"vf","enunciado":"The bullet from the attack was placed in the crown of Our Lady of Fátima.","correta":true,"explicacao":"He offered it to the shrine in thanksgiving."},
          {"tipo":"multipla","enunciado":"In what year was John Paul II canonized?","opcoes":["2014","2005","2011","2020"],"correta":0,"explicacao":"On April 27, 2014."},
          {"tipo":"ordenar","enunciado":"Put the steps to the altar in order:","blocos":["Dies in 2005","Beatified in 2011","Canonized in 2014"],"explicacao":"At his funeral, the people were already calling out: saint now!"},
          {"tipo":"vf","enunciado":"He was canonized on the same day as Saint John XXIII.","correta":true,"explicacao":"A ceremony with two saintly popes."},
          {"tipo":"multipla","enunciado":"What is the feast day of Saint John Paul II?","opcoes":["October 22","April 2","May 13","November 1"],"correta":0,"explicacao":"The day his pontificate began, in 1978."},
        ],
      },
    },
  },
  'santa-rita': {
    santo: "Saint Rita of Cascia",
    titulo: "Saint Rita of Cascia",
    descricao: "The saint of impossible causes.",
    medalha: "Perseverance",
    medalhaCompleta: "Medal of Perseverance",
    virtude: "Perseverance",
    licoes: {
      'rita-1': {
        titulo: "Wife and mother",
        conteudo: [
          {"tipo":"multipla","enunciado":"What is Saint Rita invoked for?","opcoes":["Impossible causes","Travel","Studies","Harvests"],"correta":0,"explicacao":"She is the patroness of difficult causes."},
          {"tipo":"vf","enunciado":"Before becoming a nun, Rita was a wife and mother.","correta":true,"explicacao":"She entered the convent only after she was widowed."},
          {"tipo":"multipla","enunciado":"In which country was Saint Rita born?","opcoes":["Italy","Spain","Portugal","France"],"correta":0,"explicacao":"In Roccaporena, near Cascia."},
          {"tipo":"vf","enunciado":"Rita wanted to be a nun from a young age, but her parents arranged her marriage.","correta":true,"explicacao":"She obeyed and lived her marriage with faith."},
          {"tipo":"multipla","enunciado":"What was Rita's husband like at the beginning of the marriage?","opcoes":["Violent and difficult","Very calm","Shy","Playful"],"correta":0,"explicacao":"Tradition says he had a very harsh temper."},
          {"tipo":"vf","enunciado":"With patience and prayer, Rita helped her husband change his life.","correta":true,"explicacao":"Her gentleness touched his heart."},
          {"tipo":"multipla","enunciado":"According to tradition, how many children did Rita have?","opcoes":["Two","One","Five","None"],"correta":0,"explicacao":"Two boys, whom she raised in the faith."},
          {"tipo":"ordenar","enunciado":"Put Rita's life in order:","blocos":["Wife and mother","Widow","Augustinian nun"],"explicacao":"A saint in every stage of life."},
          {"tipo":"vf","enunciado":"Saint Rita is celebrated on May 22.","correta":true,"explicacao":"The day of her death, in 1457."},
          {"tipo":"multipla","enunciado":"Which flower is the symbol of Saint Rita?","opcoes":["The rose","The sunflower","The tulip","The carnation"],"correta":0,"explicacao":"Because of the rose that bloomed in winter."},
        ],
      },
      'rita-2': {
        titulo: "Forgiveness",
        conteudo: [
          {"tipo":"multipla","enunciado":"What did Rita ask for when her husband was killed?","opcoes":["Forgiveness between the families","Revenge","Money","Exile"],"correta":0,"explicacao":"She asked for peace and for an end to the feud."},
          {"tipo":"ordenar","enunciado":"Put the prayer in order:","blocos":["Saint Rita,","advocate","of impossible causes"],"explicacao":"A traditional invocation."},
          {"tipo":"multipla","enunciado":"What happened to Rita's husband?","opcoes":["He was killed in a feud between families","He became a monk","He moved far away","He became a king"],"correta":0,"explicacao":"A feud between families took his life."},
          {"tipo":"vf","enunciado":"Rita forgave her husband's murderers.","correta":true,"explicacao":"She chose forgiveness instead of hatred."},
          {"tipo":"multipla","enunciado":"What did Rita ask of God so that her sons would not take revenge?","opcoes":["That God take them before they committed that sin","That they become rich","That they go to war","That they forget their father"],"correta":0,"explicacao":"According to tradition, both of them died of illness, at peace with God."},
          {"tipo":"vf","enunciado":"Rita managed to reconcile the feuding families.","correta":true,"explicacao":"Tradition says this was the condition for her to enter the convent."},
          {"tipo":"multipla","enunciado":"Which virtue is most remembered in Rita's life?","opcoes":["Forgiveness","Vanity","Haste","Ambition"],"correta":0,"explicacao":"The forgiveness that breaks the cycle of revenge."},
          {"tipo":"ordenar","enunciado":"Put the path of forgiveness in order:","blocos":["Rita suffers the loss,","prays and forgives","and brings peace"],"explicacao":"Forgiveness begins in prayer."},
          {"tipo":"vf","enunciado":"Forgiving does not mean approving of evil, but not keeping hatred in the heart.","correta":true,"explicacao":"Forgiveness heals the one who forgives."},
          {"tipo":"multipla","enunciado":"According to tradition, what was the condition for Rita to enter the convent?","opcoes":["Reconciling the rival families","Paying a large dowry","Learning Latin","Waiting ten years"],"correta":0,"explicacao":"Only after peace was made between the families was she accepted."},
        ],
      },
      'rita-3': {
        titulo: "The thorn",
        conteudo: [
          {"tipo":"vf","enunciado":"Rita received on her forehead the wound of a thorn from Christ's crown.","correta":true,"explicacao":"She bore the wound for fifteen years."},
          {"tipo":"multipla","enunciado":"Which order did Rita enter?","opcoes":["The Augustinians","The Carmelites","The Poor Clares","The Dominicans"],"correta":0,"explicacao":"At the Augustinian monastery of Cascia."},
          {"tipo":"multipla","enunciado":"In which town is Saint Rita's monastery?","opcoes":["Cascia","Rome","Assisi","Venice"],"correta":0,"explicacao":"That is why she is called Rita of Cascia."},
          {"tipo":"vf","enunciado":"According to tradition, a rose bloomed in winter at the request of the sick Rita.","correta":true,"explicacao":"It was found in the garden of the house where she was born."},
          {"tipo":"multipla","enunciado":"According to tradition, what fruit also appeared in winter for Rita?","opcoes":["Figs","Grapes","Apples","Oranges"],"correta":0,"explicacao":"Two ripe figs, together with the rose."},
          {"tipo":"vf","enunciado":"Saint Rita's body is venerated in Cascia.","correta":true,"explicacao":"In the shrine built in her honor."},
          {"tipo":"multipla","enunciado":"In what year was Saint Rita canonized?","opcoes":["1900","1457","1600","1990"],"correta":0,"explicacao":"On May 24, 1900."},
          {"tipo":"ordenar","enunciado":"Put Rita's prayer before the Crucifix in order:","blocos":["Rita prays","before the crucified Jesus","and receives the thorn"],"explicacao":"She wanted to share in the sufferings of Christ."},
          {"tipo":"vf","enunciado":"Saint Rita lived in the 15th century.","correta":true,"explicacao":"She lived from about 1381 to 1457."},
          {"tipo":"multipla","enunciado":"Which pope canonized Saint Rita?","opcoes":["Leo XIII","Pius X","John Paul II","Pius XII"],"correta":0,"explicacao":"Leo XIII, in the jubilee year of 1900."},
        ],
      },
    },
  },
  'sao-judas': {
    santo: "Saint Jude Thaddeus",
    titulo: "Saint Jude Thaddeus",
    descricao: "Apostle of hope.",
    medalha: "Hope",
    medalhaCompleta: "Medal of Hope",
    virtude: "Hope",
    licoes: {
      'judas-1': {
        titulo: "The apostle",
        conteudo: [
          {"tipo":"multipla","enunciado":"Saint Jude Thaddeus was one of how many apostles?","opcoes":["Twelve","Seventy","Three","Seven"],"correta":0,"explicacao":"He belongs to the college of the Twelve."},
          {"tipo":"vf","enunciado":"Jude Thaddeus is the same person as Judas Iscariot.","correta":false,"explicacao":"They are different people; Thaddeus remained faithful."},
          {"tipo":"multipla","enunciado":"With which apostle is Jude Thaddeus celebrated on the same day?","opcoes":["Saint Simon","Saint Peter","Saint John","Saint Thomas"],"correta":0,"explicacao":"The two are celebrated together on October 28."},
          {"tipo":"vf","enunciado":"At the Last Supper, Jude Thaddeus asked Jesus a question.","correta":true,"explicacao":"John 14:22 speaks of Judas, not Iscariot."},
          {"tipo":"multipla","enunciado":"What did Judas, not Iscariot, ask Jesus at the Last Supper?","opcoes":["Why he would reveal himself to them and not to the world","Where the supper would be","When he would return","Who would betray him"],"correta":0,"explicacao":"Jesus answered that he would come and make his home in those who love him."},
          {"tipo":"vf","enunciado":"The name Thaddeus helps to distinguish this apostle from Judas Iscariot.","correta":true,"explicacao":"That way no one confuses the faithful apostle with the traitor."},
          {"tipo":"multipla","enunciado":"According to tradition, how did Jude Thaddeus die?","opcoes":["As a martyr","Of old age in Rome","In a shipwreck","In a Jerusalem prison"],"correta":0,"explicacao":"He gave his life for the Gospel."},
          {"tipo":"ordenar","enunciado":"Put the question from the Last Supper in order:","blocos":["Lord, why","will you reveal yourself to us","and not to the world?"],"explicacao":"John 14:22."},
          {"tipo":"vf","enunciado":"According to tradition, Jude Thaddeus was a relative of Jesus.","correta":true,"explicacao":"Many consider him a cousin of the Lord."},
          {"tipo":"multipla","enunciado":"What does Luke call Jude Thaddeus in the list of the apostles?","opcoes":["Judas son of James","Judas the Zealot","Judas of Bethlehem","Judas the fisherman"],"correta":0,"explicacao":"Luke 6:16: Judas son of James."},
        ],
      },
      'judas-2': {
        titulo: "The letter",
        conteudo: [
          {"tipo":"multipla","enunciado":"Is there a letter in the New Testament attributed to him?","opcoes":["Yes, the Letter of Jude","No","Two letters","A Gospel"],"correta":0,"explicacao":"It is one of the catholic letters."},
          {"tipo":"ordenar","enunciado":"Put the invocation in order:","blocos":["Saint Jude Thaddeus,","apostle","of difficult causes"],"explicacao":"A devotion very much alive in Brazil."},
          {"tipo":"multipla","enunciado":"How many chapters does the Letter of Jude have?","opcoes":["One","Ten","Five","Twenty"],"correta":0,"explicacao":"It is a short letter, with a single chapter."},
          {"tipo":"vf","enunciado":"The Letter of Jude asks Christians to contend for the faith.","correta":true,"explicacao":"Jude 3: contend for the faith once delivered to the saints."},
          {"tipo":"multipla","enunciado":"In which part of the Bible is the Letter of Jude?","opcoes":["The New Testament","The Old Testament","The Book of Psalms","The Books of Kings"],"correta":0,"explicacao":"Among the letters of the New Testament."},
          {"tipo":"vf","enunciado":"In the Bible, the Letter of Jude comes right before Revelation.","correta":true,"explicacao":"It is the second-to-last book of the Bible."},
          {"tipo":"multipla","enunciado":"What does the Letter of Jude ask regarding those who doubt?","opcoes":["To have mercy on them","To expel them","To ignore them","To punish them"],"correta":0,"explicacao":"Jude 22."},
          {"tipo":"ordenar","enunciado":"Put the Letter's advice in order:","blocos":["Keep yourselves","in the love","of God"],"explicacao":"Jude 21."},
          {"tipo":"vf","enunciado":"The Letter of Jude ends with praise to God.","correta":true,"explicacao":"A beautiful hymn of glory to God."},
          {"tipo":"multipla","enunciado":"Why are some letters called catholic letters?","opcoes":["Because they are addressed to all Christians","Because they are only for priests","Because they are only for Jews","Because they are only for Romans"],"correta":0,"explicacao":"Catholic means universal."},
        ],
      },
      'judas-3': {
        titulo: "Devotion",
        conteudo: [
          {"tipo":"vf","enunciado":"His feast is celebrated on October 28.","correta":true,"explicacao":"Together with Saint Simon."},
          {"tipo":"multipla","enunciado":"How is he often depicted?","opcoes":["With a flame above his head","With an anchor","With a lion","With a closed book"],"correta":0,"explicacao":"The flame recalls Pentecost."},
          {"tipo":"multipla","enunciado":"What is Saint Jude Thaddeus most invoked for?","opcoes":["Difficult and desperate causes","Airplane trips","Good harvests","Soccer victories"],"correta":0,"explicacao":"He is the apostle of hope."},
          {"tipo":"vf","enunciado":"Many faithful visit the Shrine of Saint Jude Thaddeus in São Paulo.","correta":true,"explicacao":"It is one of the most visited shrines in the city."},
          {"tipo":"multipla","enunciado":"What image does Jude Thaddeus usually carry on his chest?","opcoes":["The face of Jesus","A key","A fish","A bell"],"correta":0,"explicacao":"A medallion with the face of Christ."},
          {"tipo":"vf","enunciado":"The flame above his head recalls the coming of the Holy Spirit at Pentecost.","correta":true,"explicacao":"He was with the apostles in the Upper Room."},
          {"tipo":"multipla","enunciado":"What object appears with him in many images?","opcoes":["An axe or a halberd","A violin","An anchor","A scale"],"correta":0,"explicacao":"It recalls the instrument of his martyrdom."},
          {"tipo":"ordenar","enunciado":"Put the invocation in order:","blocos":["Saint Jude Thaddeus,","pray","for us"],"explicacao":"A short prayer of trust."},
          {"tipo":"vf","enunciado":"Having devotion to a saint means asking him to intercede for us with God.","correta":true,"explicacao":"The saints are God's friends who pray for us."},
          {"tipo":"multipla","enunciado":"What does asking a saint's intercession mean?","opcoes":["Asking him to pray to God for us","Worshiping him instead of God","Doing magic","Trading favors with him"],"correta":0,"explicacao":"Only God is worshiped; the saints pray with us and for us."},
        ],
      },
    },
  },
  'teresa-avila': {
    santo: "Saint Teresa of Ávila",
    titulo: "Saint Teresa of Ávila",
    descricao: "Teacher of prayer and of the interior castle.",
    medalha: "Prayer",
    medalhaCompleta: "Medal of Prayer",
    virtude: "Prayer",
    licoes: {
      'avila-1': {
        titulo: "The reformer",
        conteudo: [
          {"tipo":"multipla","enunciado":"Which order did Saint Teresa reform?","opcoes":["The Carmelites","The Benedictines","The Franciscans","The Jesuits"],"correta":0,"explicacao":"She founded the Discalced Carmelites."},
          {"tipo":"vf","enunciado":"Teresa of Ávila is a Doctor of the Church.","correta":true,"explicacao":"The first woman declared a Doctor, in 1970."},
          {"tipo":"multipla","enunciado":"In which country was Saint Teresa of Ávila born?","opcoes":["Spain","Italy","France","Portugal"],"correta":0,"explicacao":"In Ávila, in Spain."},
          {"tipo":"vf","enunciado":"As a child, Teresa ran away with her brother, dreaming of becoming a martyr.","correta":true,"explicacao":"An uncle found them on the way and brought them back."},
          {"tipo":"multipla","enunciado":"In what year was Saint Teresa born?","opcoes":["1515","1215","1815","1415"],"correta":0,"explicacao":"On March 28, 1515."},
          {"tipo":"vf","enunciado":"Teresa founded several monasteries of Discalced Carmelite nuns.","correta":true,"explicacao":"She founded seventeen monasteries across Spain."},
          {"tipo":"multipla","enunciado":"What was the first reformed monastery Teresa founded?","opcoes":["Saint Joseph's in Ávila","Monte Cassino","San Damiano","Lisieux"],"correta":0,"explicacao":"In 1562, in Ávila."},
          {"tipo":"ordenar","enunciado":"Put Teresa's life in order:","blocos":["Born in Ávila","Founds the monastery of Saint Joseph","Is proclaimed a Doctor of the Church"],"explicacao":"From 16th-century Spain to the whole Church."},
          {"tipo":"vf","enunciado":"Teresa traveled a lot across Spain, even with fragile health.","correta":true,"explicacao":"In simple carts, on difficult roads."},
          {"tipo":"multipla","enunciado":"What is the feast day of Saint Teresa of Ávila?","opcoes":["October 15","October 1","March 19","May 22"],"correta":0,"explicacao":"It is celebrated on October 15."},
        ],
      },
      'avila-2': {
        titulo: "The interior castle",
        conteudo: [
          {"tipo":"multipla","enunciado":"What is the Interior Castle?","opcoes":["The soul with its dwelling places","A convent","A royal fortress","A city"],"correta":0,"explicacao":"Seven dwelling places leading to union with God."},
          {"tipo":"ordenar","enunciado":"Put Teresa's poem in order:","blocos":["Let nothing disturb you,","let nothing frighten you,","God alone suffices"],"explicacao":"Saint Teresa's bookmark."},
          {"tipo":"multipla","enunciado":"How many dwelling places does the Interior Castle have?","opcoes":["Seven","Three","Twelve","Forty"],"correta":0,"explicacao":"Seven dwelling places leading to union with God."},
          {"tipo":"vf","enunciado":"In the Interior Castle, God dwells at the center of the soul.","correta":true,"explicacao":"The life of prayer is a journey toward that center."},
          {"tipo":"multipla","enunciado":"According to Teresa, what is the door into the castle?","opcoes":["Prayer","Money","Fame","Study alone"],"correta":0,"explicacao":"The door to enter the castle is prayer."},
          {"tipo":"vf","enunciado":"Teresa wrote the book The Way of Perfection for her sisters.","correta":true,"explicacao":"A guide to the life of prayer."},
          {"tipo":"multipla","enunciado":"Which of these books was written by Saint Teresa?","opcoes":["The Book of Her Life","Confessions","Summa Theologica","Introduction to the Devout Life"],"correta":0,"explicacao":"In it she tells her own story with God."},
          {"tipo":"ordenar","enunciado":"Put the end of the poem in order:","blocos":["Whoever has God","lacks nothing:","God alone suffices"],"explicacao":"The end of the famous Let nothing disturb you."},
          {"tipo":"vf","enunciado":"Teresa compares the soul to a castle made of diamond or of very clear crystal.","correta":true,"explicacao":"An image of the beauty of the soul created by God."},
          {"tipo":"multipla","enunciado":"What does Teresa teach us to seek within ourselves?","opcoes":["The presence of God","Pride","Wealth","Fear"],"correta":0,"explicacao":"God is closer than we imagine."},
        ],
      },
      'avila-3': {
        titulo: "Friendship with God",
        conteudo: [
          {"tipo":"multipla","enunciado":"How does Teresa define prayer?","opcoes":["Friendly conversation with the one we know loves us","Reciting formulas","Asking for things","Only keeping silent"],"correta":0,"explicacao":"The classic definition from the Book of Her Life."},
          {"tipo":"vf","enunciado":"Teresa had Saint John of the Cross as a disciple.","correta":true,"explicacao":"Together they reformed the Carmel."},
          {"tipo":"multipla","enunciado":"Which experience of Teresa is shown in Bernini's famous sculpture?","opcoes":["The piercing of her heart","The stigmata","Levitation","Bilocation"],"correta":0,"explicacao":"She told how an angel pierced her heart with a dart of fire."},
          {"tipo":"vf","enunciado":"Teresa said that God walks among the pots and pans of the kitchen too.","correta":true,"explicacao":"God is present in the simple tasks of everyday life."},
          {"tipo":"multipla","enunciado":"Which saying of Teresa reminds us that God is in everyday life?","opcoes":["The Lord walks among the pots and pans too","God is only in the temple","God lives far away","God does not care about work"],"correta":0,"explicacao":"It is in the Book of the Foundations."},
          {"tipo":"vf","enunciado":"Teresa died in Alba de Tormes, in Spain.","correta":true,"explicacao":"In 1582, during a journey."},
          {"tipo":"multipla","enunciado":"In what year did Teresa die?","opcoes":["1582","1515","1622","1700"],"correta":0,"explicacao":"In October 1582."},
          {"tipo":"ordenar","enunciado":"Put the definition of prayer in order:","blocos":["Prayer is friendly conversation","with the one we know","loves us"],"explicacao":"The definition from the Book of Her Life."},
          {"tipo":"vf","enunciado":"Teresa was canonized in 1622.","correta":true,"explicacao":"Forty years after her death."},
          {"tipo":"multipla","enunciado":"With which saints was Teresa canonized on the same day?","opcoes":["Ignatius of Loyola and Francis Xavier","Francis and Clare","Peter and Paul","Benedict and Scholastica"],"correta":0,"explicacao":"Together also with Isidore the Farmer and Philip Neri."},
        ],
      },
    },
  },
});
